### ISSUE TITLE
Document Scenario folder structure in gitbook

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#109]
We should document the folder structure used for scenarios in gitbook. The folder structure is as much an input as the files contained in the structure.

We should discuss a naming convention for files too: If we always call them `buildings_age.shp` etc., then the tools for ArcGIS can be simplified a lot (just point to the scenario folder! also, the results from the properties script would not need to be given, since the tool "knows" where to put the results in the folder structure).

A few guidelines:
* flat is better than nested!
* screw `102_intermediate output` - this just messes stuff up!
* where do we store our scenarios? test-scenarios?
* how to create a new scenario? (this should be a chapter in the gitbook!!!

**Comment by JIMENOFONSECA** [comment]
Great Idea, I will make a structure in the test folder to follow, ditching 102... we will need extra space to upload the radiation file see issue #119

**Comment by daren-thomas** [comment]
Wrote Arno an email requesting funds. Waiting for answer.
