### ISSUE TITLE
prop_RC_model in demand might be empty

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#111]
If `len(prop_RC_model.index) == 0`, then this fails to assign `df`:

```
for name in prop_RC_model.index:
    if counter == 0:
        df = pd.read_csv(path_temporary_folder + '\\' + name + 'T' + '.csv')
        counter += 1
    else:
        df2 = pd.read_csv(path_temporary_folder + '\\' + name + 'T' + '.csv')
        df = df.append(df2, ignore_index=True)
df.to_csv(os.path.join(path_results, 'Total_demand.csv'), index=False, float_format='%.2f')
```

This is around line 110 in demand.py on the branch i37_*

See also this error message:

![image](https://cloud.githubusercontent.com/assets/2969564/14180913/40a8b608-f765-11e5-9b5b-888b063edc38.png)

**Comment by daren-thomas** [comment]
This can happen if the radiation file does not match the scenario! That is, the building names don't match up... I was using the radiation file from the Siemens Zug case with the shape files from the Hochschulquartier case...

**Comment by daren-thomas** [comment]
decreasing priority because bug only shows up if the wrong radiation file is used...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas should this be closed?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, no. It is a bug. Low priority, but good to know you have a bug. I can fix it when I have time. The fix is cheep: just throw an error that explains what happened and where the error might be instead of the confusing one I originally got and had to go looking...

**Comment by daren-thomas** [comment]
moving to next milestone (post-gabriels changes...)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still need to be done?

**Comment by daren-thomas** [comment]
no. i think this has been refactored into oblivion.
