### ISSUE TITLE
Rename column `Shape_Leng` in the radiation file

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#112]
Is there any reason why we can't call it `Shape_Length`?

Also... why the capitalization? Do we need to capitalize everything? It seems awfully baroque...

**Comment by JIMENOFONSECA** [comment]
no way to do it as it belongs to the way ArcGIS names the geometry of the shapefile and the maximum length of characters in a .dbf file
