### ISSUE TITLE
Update `README.md` to be more standard

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#117]
This guide here is a good start to what should be in our README.md file.

http://docs.writethedocs.org/writing/beginners-guide-to-docs/

**Comment by JIMENOFONSECA** [comment]
To avoid repetition and changes in one or the other. I suggest this readme to point to the introduction /quick start section of the manual.

**Comment by daren-thomas** [comment]
Also, we could consider having a "Roadmap" section
