### ISSUE TITLE
How are the heating/cooling systems controlled?

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/CEAforArcGIS#118]
I was looking for the code in the `demand.py` that controls the heating/cooling control systems? Is it a simple proportional control or a PI control? If so, where can I find the code?

**Comment by pjayathissa** [comment]
Also, in the ´Occupancy_COM.csv` schedule, the heating setpoint is often the same as the cooling setpoint? This would cause the model to fight against each other causing a large energy loss. Wouldn't it be better to set the cooling setpoint to something higher, such as 26C?

**Comment by amraladdin** [comment]
I agree PJ, the there should be a difference between the heating and cooling setpoints.
I'm working on another issue that also has to do with this point. I'll update you with the progress.

**Comment by JIMENOFONSECA** [comment]
No interference as the program considers heating only during winter season. no cooling is allowed during winter as well as no heating is allowed during summer. For the case study of zurich and Zug these set points where the same for commercial units. For other occupancies these set points might change. you can in principle make your schedule and run the program changing setpoints.

**Comment by pjayathissa** [comment]
I guess this would work if you limit the application of your software to Switzerland. If I run a weather file from Wellington (New Zealand) which has inversed seasons, then we would have problems. It would therefore be better to have max and min temperature set points with proportial intergral (PI) Control. You can use my [PID_Controller](https://github.com/architecture-building-systems/RC_BuildingSimulator/blob/master/simulator/PID_controller.py) if you like. It works quite well.

**Comment by daren-thomas** [comment]
I guess having a controller plugin architecture will be the way to go in the end, right?

**Comment by amraladdin** [comment]
Yes, I agree with PJ on this matter.

**Comment by amraladdin** [comment]
@JIMENOFONSECA I think we can close this issue now, would you agree?
