### ISSUE TITLE
Get license for Github

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#119]
We need space to upload radiation file and one file I'm working on Schedule_maker (>200mb) in Github. @daren-thomas  would you mind buying a license for GitHub at least temporally? until July perhaps?

**Comment by daren-thomas** [comment]
I have the green light from Arno to do this. Do we want to keep the reference case in a private repository? As opposed to the Google Drive? I like the idea a lot!

**Comment by JIMENOFONSECA** [comment]
Yep, the only thing is that nobody should upload results files. It gets a mess if there is a conflict. Last conflict for instance made me add/remove to master close to 120 files. It takes ages. Maybe we write a small rule or something?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I have bought Git LFS - find instructions to install it here: https://help.github.com/articles/installing-git-large-file-storage/

We can now upload bigger files to GitHub! Yay!

Also, I have created a reference case repository (cea-reference-case)
