### ISSUE TITLE
Simulate multi-thermal zone for buildings

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#12]

**Comment by shanshanhsieh** [comment]
Other ways to formulate 'cal_mixed_schedule'
Instead of using weighted average as implemented currently, we have to find a way to describe the mixed schedule better in Singaporean buildings with multiple zones/usages.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro this is the issue which could make more sense to work in right now as it goes in line with the needs of the spacergy project

**Comment by JIMENOFONSECA** [comment]
relates to #664 as a duplicate. closing it
