### ISSUE TITLE
Define users and credentials, based on these documentation

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#121]
@daren-thomas and @amraladdin  based on the matsim case study and your experience let's define levels of users, sandbox folders and levels of credentials. Here is the example of Matsim:

1. Users and credentials:

- MatSim counts with 4 types of users and a board of directors, each one belonging to one level of rights. This allows to have certain selection at the moment of expanding the tool. Also acknowledging that not everyone should be allowed to directly contribute to its core.
---- **Board of directors (BD).** This board are responsible of  merging to master and accepting new users. As the tool is quite young I will suggest @daren-thomas and myself are the board for now. and it

----**User level 4 is the common public**, who downloads the tool from the MatSim website and uses it for their studies, he has access to a manual and a small tutorial which explains which files to get, where to get them from, how to run it, etc. I see this user as an engineer generally, our students or a company who would like to use it for their own applications. the group of Matsim might or might not know who uses it. There must be **a disclaimer**. we do not accept any responsibility. 

——**User level 3 is a wanna to be contributor**, he is typically a researcher who gets interested and gets access to the source code through Github. He gets a 3-day tutorial of the tool (a detailed manual), where MatSim is explained in more detail. incl. description of functions but not essentially scripts.  He creates a pull request to be analysed by the board of directors (BD). If he passes he can become part of user level 2. 

——**User level 2 is a contributor whose pull request has been accepted**. As well as any other researcher, Postdoc, PhD that has been pointed directly by the BD to contribute. This user can have access to a folder called “Sandbox” where he can play around with code. When his code is bullet-proofed, he puts the code in a folder called “Contributions”. The BD will look at the code, and if it is good for Matsim it will be implemented into its core. 

——**User level 1 is a senior developer/reseracher **who is in most cases part of the BD. He approves the code and can directly modify the core of MatSim. The board can object however and take it down. I suggest me and @daren-thomas to start here too.

1. Manuals and tutorials:

There will be two main documents of the CEA tool: Example:http://matsim.org/docs

--- The Developers Manual: first version could be in charge of @daren-thomas and me. This is targeted to Users 1, 2 and 3. Here Gitbook can work.

--- The User Manual: first version could be in charge of me and @amraladdin. this is targeted to User 4. Here we have to think on something else. it needs a nice and easy to read format. highly graphic and intuitive. 

 
@daren-thomas and @amraladdin  based on the matsim case study and your experience let's define levels of users, sandbox folders and levels of credentials. Here is the example of Matsim:

1. Users and credentials:

- MatSim counts with 4 types of users and a board of directors, each one belonging to one level of rights. This allows to have certain selection at the moment of expanding the tool. Also acknowledging that not everyone should be allowed to directly contribute to its core.
---- **Board of directors (BD).** This board are responsible of  merging to master and accepting new users. As the tool is quite young I will suggest @daren-thomas and myself are the board for now. and it

----**User level 4 is the common public**, who downloads the tool from the MatSim website and uses it for their studies, he has access to a manual and a small tutorial which explains which files to get, where to get them from, how to run it, etc. I see this user as an engineer generally, our students or a company who would like to use it for their own applications. the group of Matsim might or might not know who uses it. There must be **a disclaimer**. we do not accept any responsibility. 

——**User level 3 is a wanna to be contributor**, he is typically a researcher who gets interested and gets access to the source code through Github. He gets a 3-day tutorial of the tool (a detailed manual), where MatSim is explained in more detail. incl. description of functions but not essentially scripts.  He creates a pull request to be analysed by the board of directors (BD). If he passes he can become part of user level 2. 

——**User level 2 is a contributor whose pull request has been accepted**. As well as any other researcher, Postdoc, PhD that has been pointed directly by the BD to contribute. This user can have access to a folder called “Sandbox” where he can play around with code. When his code is bullet-proofed, he puts the code in a folder called “Contributions”. The BD will look at the code, and if it is good for Matsim it will be implemented into its core. 

——**User level 1 is a senior developer/reseracher **who is in most cases part of the BD. He approves the code and can directly modify the core of MatSim. The board can object however and take it down. I suggest me and @daren-thomas to start here too.

1. Manuals and tutorials:

There will be two main documents of the CEA tool: Example:http://matsim.org/docs

--- The Developers Manual: first version could be in charge of @daren-thomas and me. This is targeted to Users 1, 2 and 3. Here Gitbook can work.

--- The User Manual: first version could be in charge of me and @amraladdin. this is targeted to User 4. Here we have to think on something else. it needs a nice and easy to read format. highly graphic and intuitive.

**Comment by JIMENOFONSECA** [comment]
let me know you opinion and we start distributing issues in relation

**Comment by amraladdin** [comment]
Sounds good for me! So does this mean I'm a level 2 contributor? :+1: 
Why did you write everything twice?

**Comment by daren-thomas** [comment]
So, the "Sandbox" and "Contributions" folder is not necessary: Basically,
this is solved by the GitHub fork/branch and pull request workflow.

I like the idea of adding structure.

I'm not so sure what you meen by "highly graphic and intuitive" for the
user manual...

**Comment by JIMENOFONSECA** [comment]
I see the sandbox as a collection of scripts anyone can see and play with. For instance i create a new radiation model and start working with it there. Somebody online sees it and wants to give me a hand or use parts of the code. I can decide weather create a pull request or not.

**Comment by JIMENOFONSECA** [comment]
The nice thing about a contribution folder is that we can organize people who contribute and their contributions before integrating into the Core. It will be easier to check and control later on than digging in each single branch done in let's say next 20 years of the tool?.

**Comment by JIMENOFONSECA** [comment]
"highly graphic and intuitive": with graphs. a good and clear design that can be digested easily and makes anyone wants to read it. We need to provide a good image speially to the general public if we want the tool becomes widespread.

**Comment by JIMENOFONSECA** [comment]
Yes @amraladdin your will be level 2. Sorry github wrote it twice

**Comment by daren-thomas** [comment]
OK. I think I don't really understand what you mean. Jimeno, do you mind creating a chapter in the Dev documentation describing the above in more detail? Then maybe I can understand how what you are proposing is different/better to the pull/merge workflow.

As to the credits: Anyone who works on a branch and commits will automatically become part of the changelog. We should apply credits at pull/merge time. Then we forget the single branch forever!

As to your example: We need a checklist of stuff to do *before* sending pull request. This should include:
- update headers/credits of files you have changed
- update documentation (user/dev) of functionality that has changed
- test that the merged version will still work (test in ArcGIS, test the test-scripts)
- list issues by number that are fixed/affected by the pull request

How is a branch different to a sandbox? How is a fork different to a contribution folder?

**Comment by JIMENOFONSECA** [comment]
Perfect i will create ground rules. and include it in the documentation. after finished would you @daren-thomas create the folder structure and change the credentials of any participant?

The ground rules will include the way we will assign issues to people. i think we need some clarity on that too. I suggest we first mention the issue, describe it thoroughly and then propose somebody to solve it. this also helps that people commit acknowledging their overhead. This is to avoid practices such as issues #123 and #124

**Comment by JIMENOFONSECA** [comment]
done in the documentation, please check.
