### ISSUE TITLE
Error generating PROPERTIES - new CEA version

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#122]
There seems to be a problem when I try to run the PROPERTIES on the CEA.
I get the following error:
------------------------------------------------------------------------------------------------

Executing: PropertiesTool C:\Users\aelesawy\Documents\GitHub\CEAforArcGIS\test\reference-case\feature-classes\building_age.shp C:\Users\aelesawy\Documents\GitHub\CEAforArcGIS\test\reference-case\feature-classes\building_occupancy.shp true true true C:\Users\aelesawy\Documents\GitHub\CEAforArcGIS\test\Results
Start Time: Mon Apr 04 16:24:30 2016
Running script PropertiesTool...

Traceback (most recent call last):
  File "C:\Users\aelesawy\Documents\GitHub\CEAforArcGIS\cea\toolbox.py", line 79, in execute
    prop_HVAC_flag=prop_HVAC_flag.value, gv=gv)
TypeError: properties() got an unexpected keyword argument 'path_age'

Failed to execute (PropertiesTool).
Failed at Mon Apr 04 16:24:31 2016 (Elapsed Time: 0.06 seconds)

**Comment by daren-thomas** [comment]
bug went away magically after reinstalling. must have been a configuration issue.
