### ISSUE TITLE
Take down sensible data

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#128]
About the documentation and reference case study currently available online in Github or Gitbook:
- the test/reference-case should be taken down now. The case study could have data (terrain and geometry) that cannot be published by any means. There is no way to make an artificial dataset at this moment. I will suggest to Create a dropbox or another repository (private) where we share the reference case study.
- The documentation/ installation guidelines etc should be taken down. Nobody should be able to download and intend to use the tool at this stage (except us). For that no installation guide nor manual to use the tool should be available online. I propose we make it available after the planned release of the fist milestone (13.06.16). We might lose credibility later on if we keep something online unfinished and not tested. (edited)

[11:21] 
@daren-thomas Please suggest the means to share these data. It can be either dropbox, polybox or our server in Singapore/ another private repository in Github etc..

**Comment by JIMENOFONSECA** [comment]
This will take effect on the 08.04.16 if not any other comment @amraladdin @gabriel-happle @shanshanhsieh

**Comment by JIMENOFONSECA** [comment]
Done, we will share it. Please copy the reference-case to your C:\ when using it in that sense I can make sure that everytime you open ArcGIS the maps and layers correspond to the folder structure in C:\

**Comment by daren-thomas** [comment]
where is the reference-case?
