### ISSUE TITLE
Translate referencecase/infrastructure.xls to English

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#134]
It is currently in german.

Also, check that the code doesn't depend on the german labels.

**Comment by JIMENOFONSECA** [comment]
done, where should I put it?

**Comment by daren-thomas** [comment]
huh... i guess it is time to get #119 up and running, right?

where do you currently keep the reference case? put it there. I'll contact you when I have the reference-case repo up and running...

**Comment by JIMENOFONSECA** [comment]
up in the repo
