### ISSUE TITLE
Do we need multiple radiation files per scenario?

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#136]
This has to do with the reference-case folder structure: I'm working on an `InputLocator` class that can do stuff like:

```python
locator = InputLocator(PATH_TO_SCENARIO)
locator.get_building_thermal()  # --> path to building_thermal.shp
```

This breaks down because we have multiple radiation files... which file to return for `locator.get_radiation()`?

Now... before I come up with something clever... does a scenario have to have more than one radiation file? is a scenario bound to a specific point in time (then we only need one such file!!!) or can a scenario be looked at at different times (then having multiple makes sense and we need to answer this question intelligently)

@JIMENOFONSECA, can you help with this?

**Comment by JIMENOFONSECA** [comment]
Good point. There should be only one radiation file per scenario. An scenario should be one point in time with certain boundary conditions under it. The radiation file is an output of an script. I am gonna upload the radiation script we have now in a new issue. we probably will needed for the next milestone

**Comment by daren-thomas** [comment]
OK. Let us call it `radiation.csv`.

**Comment by daren-thomas** [comment]
also, the same goes for the weather files. can we call the (single) weather file:

- `weather_hourly.csv`
- `weather_daily.csv`

**Comment by JIMENOFONSECA** [comment]
yes let's do that. could you create the private repository for the case studies? I will make a baseline scenario and a baseline scenario+2030 weather data making the above mentioned conventions

**Comment by daren-thomas** [comment]
I will do this today!
Creating the repo is easy. I will order the GitHub LFS thing. You will need to install an extension on your computer to use it. This will allow you to push large files to github and download them as well. I'll contact you as soon as this is done!
