### ISSUE TITLE
Create radiation script 

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#137]
From the old work on the CEA, we will create a script to calculate vertical isolation in building surfaces using ArcGIS. this script will be replaced by the work of Neitel paul in late september. By the time being we need it now. i will create the script @daren-thomas could you create the ArcGIS interface?

**Comment by daren-thomas** [comment]
sure, can! Assign the task to me as soon as the script is done...

**Comment by JIMENOFONSECA** [comment]
done :-)

**Comment by daren-thomas** [comment]
The radiation script is very unstable. I often get `MemoryError` on the `pandas.merge` operations. I suspect it might have to do with

- the size of the dataframes in question
- specifically the shape (most tools are optimized for tall tables as opposed to wide tables)

Maybe we can change the shape of the radiation dataframe to fit tidy data standards?

- one observation per line!

We currently have $HOURS_IN_YEAR observations per line...

**Comment by daren-thomas** [comment]
just pushed latest fix for the radiation tool: It now uses the weather file list similar to the demand script.
