### ISSUE TITLE
Standard to create documentation and comment every script

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#138]
I was wonder if we could elaborate a good example of how to comment a script and elaborate documentation for it. @shanshanhsieh maybe you can give it a try to create a template. @daren-thomas could we also look for automated ways to do it?. I head from Sergio that java has something called java docs. it basically reads the code and extracts all the comments into an organized and structured way.

@shanshanhsieh for the time being we might start with a description of what the script does, what it is based on/a reference at the beginning, and include comments in the code.

**Comment by shanshanhsieh** [comment]
got it, I will make documentation in my current contribution (i056), and derived a template from it.

**Comment by daren-thomas** [comment]
Here is a link to the documentation guide for python: https://docs.python.org/devguide/documenting.html

This is for the core python and standard libraries. Following these rules will make it easy to use Sphynx (like javadoc) to generate documentation automatically.

Also check the PyCharm Documenting Source Code page: https://www.jetbrains.com/help/pycharm/2016.1/documenting-source-code-in-pycharm.html

Since we are using PyCharm, it makes sense to use some of it's cool stuff. Adding type information to the doc string of methods for instance let's PyCharm assist in code-completion/IntelliSense and makes life easier for everyone.

A very, **very** important step to documenting code that is often overlooked is *naming*. You need to name your variables, functions, classes etc. properly. This will make the code much clearer than documenting messy code. This is also very important as the code tends to change faster than the documentation and keeping those two in sync has a long history of not happening...

**Comment by shanshanhsieh** [comment]
hey @daren-thomas, maybe you could give me a hand on this issue.
as I understand, currently, we are sort of using ReStructured Text format in our codes, which has the possibility to generate documentation in HTML/PDF via Sphinx tool integrated in Pycharm. 

This leads me to two questions:
1. Do we want replace gitbook with documentation generated from this workflow (via Sphinx tool)? Seems like there is no direct way to read markdown docstring in Pycharm like Sphinx, tell me if I am wrong.
2. I couldn't quite get the "Running Sphinx Task" step to generate documentation. If you know how it works, could you please take storagetank_mixed.py as an example and show us how the documentation will look like?
https://www.jetbrains.com/help/pycharm/2016.1/run-debug-configuration-sphinx-task.html

Thanks!

**Comment by daren-thomas** [comment]
hey @shanshanhsieh, to answer your questions:

1. No. This should not replace the documentation, but rather augment it: The generated documentation is more of an API documentation. We can maybe add it as a chapter to the gitbook documentation. On gitbook, we are also documenting team stuff and other things that don't fit into file headers / function docstrings.

2. I will look into the "Running Sphinx Task" as soon as I can.

**Comment by JIMENOFONSECA** [comment]
any update?

**Comment by shanshanhsieh** [comment]
@daren-thomas just checking out the issues we need to finish before M1. i don't think we are going to use the documentation for the SBE workshop, shall we move this to M2?

**Comment by daren-thomas** [comment]
I think we need to document the code as much as possible for M1. No need to generate the sphynx api docs, but the code should be in the best shape we can get it by then as it goes public on M1.

**Comment by shanshanhsieh** [comment]
As discussed, here is a general in-function documentation format we could adapt. 
@JIMENOFONSECA @daren-thomas @gabriel-happle @martin-mosteiro @amraladdin Please feel free to comment on what else we could include, I will make a standard format and write it in the Gitbook.  

```
"""    
    Description
    ---------------
This algorithm calculates the heat flows within a fully mixed water storage tank.
Heat flows include sensible heat loss to the environment (ql), heat charged into the tank (qc), and heat discharged from the tank (qd).
    
    Assumptions
    -----------------

    Parameters
    ---------------
    :param Tww_st_0: Initial tank temperature in C
    :param Utank: dhw tank insulation heat transfer coefficient in W/m2-K, value taken from [1]
    :param AR: # tank height aspect ratio, H=(4*V*AR^2/pi)^(1/3), value taken from commercial tank geometry[2]. global variable.

    Returns
    ----------
    :return ql: storage sensible heat loss in W.
    :return qd: heat discharged from the tank in W.
    :return qc: heat charged into the tank in W.

    References
    ---------------
    [1] SIA 385
    [2] Jenni.ch
"""
```

This is the link to the source code of sandia pv library, more examples could be found there:
http://pvlib-python.readthedocs.io/en/latest/_modules/pvlib/pvsystem.html#LocalizedPVSystem

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh was this added to the gitbook? could be close this issue?

**Comment by shanshanhsieh** [comment]
The documentation comment template is added to gitbook in the "Style" section. This issue can be closed now.
