### ISSUE TITLE
Tidy up `CalcThermalLoads`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#141]
The function `CalcThermalLoads` has some code smells... These are some things that should be fixed:
- the name should comply to PEP8 (suggestion: `calc_thermal_loads`)
- the parameter list needs to be shortend -strategies from Martin Fowlers _Refactoring_: 
  - _Replace Parameter with Method_ (like the `InputLocator`)
  - _Introduce Parameter Object_ (create a class to encapsulate the data needed)
- keep names for parameters the same throughout the project (why do we call the `RadiationLoad` `Solar`, `Radiation_Shading2` etc.??)
- move to the `demand.py` script

**Comment by daren-thomas** [comment]
Progress has been made here on multiple fronts with multiple issues. I think the M1.8 Milestone is appropriate for having this done and over with. The `tds` variable implements the _Introduce Parameter Object_ refactoring - as does the `bpr` instance of `BuildingPropertiesRow`. `gv` should be expanded on and renamed to `context` but that will be a separate issue.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas  is this still an active issue?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA technically it is not finished yet, but I do not want to make changes to demand calculation because @gabriel-happle is making changes. We need to get @gabriel-happle 's changes into master ASAP I think. I have moved this to the next milestone for now.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still an active issue?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA no. it has been resolved with gabriel's branch.
