### ISSUE TITLE
Fix paths to reference case location to test run demand.py

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CEAforArcGIS#142]
in order to test_demand

**Comment by daren-thomas** [comment]
what is `location_demand.py`? What is the new reference case?

I don't understand what this issue is about. Also, "Fixed" in past tense suggests it has already happened, but I think you want to fix it?

**Comment by shanshanhsieh** [comment]
the paths in text_demand() is not pointing to the folder where we are storing the current reference case now, so i would like to modify it.
