### ISSUE TITLE
Write a function to automatically place windows on building envelope

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#146]
Windows are automatically placed on the building envelope according to window-wall-ratio and number of floors above ground.
Properties of the windows include:
- Orientation of window (deg)
- Height of window above ground (m) or above floor height
- Area of window (m2)

This issue is linked to #16 and #30 and prerequisite for the new ventilation model according to EN 16798

**Comment by daren-thomas** [comment]
don't forget to document how the orientation works. i have seen different schemes (based of true north, based of project north, based of east (?) etc.) - at some point some poor guy is going to have to take such a building description and create an EnergyPlus model from it programatically (happens all the time, I swear!) and will then need this information...

**Comment by gabriel-happle** [comment]
I'm going to close this issue. We can open a new one, when we decide how to proceed exactly with building geometries, 3D formats, etc.
