### ISSUE TITLE
Refactor embodied.py `for archetype in list_of_archetypes`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#147]
This is ugly: sure, a for-loop is cool, but then using a counter to figure out what archetype we are calculating reverses the benefit.

Suggestion: _extract-method_

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still the case? would you take care of it?

**Comment by daren-thomas** [comment]
Sure. I'm doing a lot of refactoring anyway and adding issues as I'm going through the code so I don't forget them.
