### ISSUE TITLE
Create Archetypes Values for Controller types

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#159]
@shanshanhsieh i will create the Input excel datafile and shapefile to refer to. It includes temperatures of operation of emission systems. Then i will pass it to you.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh the work is in branch i159

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA there should actually be two control types, ex. e_ctr_c and e_ctr_h, for heating and cooling respectively, instead of one control type for both heating and cooling emission systems.
could you please add another control field? thanks

**Comment by shanshanhsieh** [comment]
We will leave this issue on whether implementing separate control systems for cooling and heating emission systems in buildings until more research is done. @martin-mosteiro , would this be something you want to find out as well?

**Comment by martin-mosteiro** [comment]
@shanshanhsieh absolutely!

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @martin-mosteiro is anybody working on this? is the level of priority adequate?

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro could you add the estimate, thanks?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @martin-mosteiro is thi sstill an issue? please close if not...
