### ISSUE TITLE
Air infiltration model

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#16]
This concerns an outdoor dependent model for simualting air infiltration in buildings due to occupancy and building tightness. Until now this is generalized independently of the type of occupancy or building with the next variables in GlovalVariables.py

-	self.NACH_inf_non_occ = 0.2  num air exchanges due to infiltration when no occupied. SIA
-	self.NACH_inf_occ = 0.5  num air exchanges due to infiltration when occupied. SIA

**Comment by shanshanhsieh** [comment]
Instead of using fixed value as it is currently.
Possible ideas: stochastic/ agent based modelling

**Comment by gabriel-happle** [comment]
Ideas:
(1) Infiltration (and summer comfort) according to EN 15242:2007
(2) Infiltration analog to DOMVENT3D (http://bse.sagepub.com/content/35/4/408.full.pdf+html)

**Comment by 3for2** [comment]
Highly advocate a detailed study / model development on this - and with a focus on handling this parameter probabilistically... Some examples: the 3for2 area infiltration is about 0.03 ACH overnight, and negative (e.g., we exfiltrate) during operational hours. Exfiltration is attributed to the creation of positive indoor pressure, which central air handling systems with fresh-air provision strive for. You can even assume that, as a norm, central air-con systems in commercial buildings have negligible infiltration during occupied hours with the exception of the ground entrance/exit floor. The 3for2 area's overnight ACH is attributed both to its tight facade and generally low wind pressures in Singapore. Residential HDBs (or even modern condos) may be significantly more leaky (as they are at my place, which is a brand new condo). However, I have found no easy rule of thumb to go by to estimate infiltration in these cases... Without better knowledge about the specific building, or some probabilistic handling, the deterministic selection of 0.05, 0.1, 0.5, 0.7 ACH for infiltration all seems arbitrary to me.....

**Comment by gabriel-happle** [comment]
This is probably continuous development. But with smaller, specific issues. I'm therefore closing this now.
