### ISSUE TITLE
Refactor `Calc_Rf_sh` to use a dictionary

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#161]
Seriously? We create a `DataFrame` and then loop through it to find the row matching `ShadingType` and then return the value?

Code should be this:

``` python
def Calc_Rf_sh(ShadingType):
   coefficients = {'T0': 1.0, 'T1': 0.08, 'T2': 0.08, 'T3': 0.15, 'T4': 0.57, 'T5': 0.1}
   return coefficients[ShadingType]
```

And then refactor function name to `calc_Rf_sh` (maybe) and `ShadingType` to `shading_type`

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still the case? would you take care of it?

**Comment by daren-thomas** [comment]
I can take care of it.

**Comment by daren-thomas** [comment]
I can't find this in our code anymore. Closing.
