### ISSUE TITLE
Architecture for CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#164]
The CEA is missing a clear structure to allocate functions, classes and create a controller to put everything together. This needs some research but needs to be implemented asap so the DEV team can more easily contribute

Hi @daren-thomas i believe we can discuss this here. Could you take care of this issue?

**Comment by daren-thomas** [comment]
Yes. I agree. This is a good place to do the discussion. I am thinking along the lines of having an object called `ModelRepository` that gets passed to the scripts that contains implementations of the models. To do this, we would have to refactor the scripts. Start with `demand.py`: extract the separate models from the "driver" script and describe the inputs and outputs. Add these to a default `ModelRepository` implementation. Later, users can then swap in the `mr.ventilation_model` with an implementation of their own.

This could get tricky, as models start to interact...

**Comment by daren-thomas** [comment]
A first "poor-mans-registry" has been implemented (i.e. "sneaked into core") in the pull request #171 - this adds a `gv.models` dictionary of functions that can be overridden before starting a simulation. The demand script uses `gv.models['calc-thermal-loads']` as the function for (you guesst it!) calculating thermal loads. This is set to be `functions.CalcThermalLoads` in the core, but can be overridden to use another method - see @gabriel-happle 's sandbox.

**Comment by daren-thomas** [comment]
(I'm just a little worried that this could become difficult to debug?)
basically, the pattern is called *dependency injection*.
