### ISSUE TITLE
Sandbox and Contributions "bleeding" into pull requests

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#165]

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still the case? would you take care of it?

**Comment by daren-thomas** [comment]
Yes, this is still the case. We still need to think about this a bit more.

**Comment by daren-thomas** [comment]
We now have a sandbox branch and that seems to be working. It is probably better to develop changes on a dedicated branch, but the sandbox can serve for personal scripts / playing around.

I'm not sure what the contributions branch is good for.
