### ISSUE TITLE
# fix interface for new heatmaps module

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#166]
This is the result from solving issue #163
After merging the pull request #167  @daren-thomas would you add it to your list? merci

# COMMENTS FOR THE INTERFACE
## USER SIDE:
-  the user should select a scenario
- then select from a `fixed_list` a file he would like to map.  
  - `fixed_list` = `list(get_total_demand(self), all files in results/emissions)`

## PYTHON SIDE
- return the pointer to the scenario
- return the selected element form the list as `selection'
- when the element is selected from the list: if the file is from the emissions folder. return the `path_results = get_heatmaps_emission_folder()`
- but if the element selected in from the demand folder, return `path_results = get_heatmaps_demand_folder()`.
- do the same to select the `path_variables`

## USER SIDE
- see the analysis field variables from the `selection` file
- select one or several

**Comment by daren-thomas** [comment]
I've cleaned up the issue a bit. It is not really described clearly so I am going to have to guess what you mean. Also, for user interface, we should in the future specify what text to show. Again, I'm going to have to guess some stuff.

**Comment by daren-thomas** [comment]
Interpreting "all files in results/emissions" as `scenario/2-results/3-emissions/1-timeseries/*.csv`.
the folder can be found in `inputlocator`: `get_lca_emissions_results_folder()`.

**Comment by daren-thomas** [comment]
Problems with emissions-files as inputs: field names longer than 10...

**Comment by daren-thomas** [comment]
see pull request #170 for implementation of this feature

**Comment by JIMENOFONSECA** [comment]
Correct!

Sent on the road

**Comment by daren-thomas** [comment]
fixed and merged :)
