### ISSUE TITLE
Style section of dev guide missing reference

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#177]
When we copied the style section of the dev guide (I guess from the `code-conventions.md` file?) the reference to the original document got lost.

This is not something we wrote, so we should mention our source!

**Comment by JIMENOFONSECA** [comment]
Avoid assigning, rather mention. Check team conventions. 

The reference you are looking at is at the bottom of the article.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas can we close this?

**Comment by daren-thomas** [comment]
yes we can!
