### ISSUE TITLE
Last fixes to contributors manual

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#180]
@daren-thomas i worked intensively in the contributors manual and would need your help to finish the next sections for the milestone. would you mind taking care of them? 
- Quick start Team convention / Communication / Github 
- Architecture
- Architecture / Code structure 
- Architecture / Workflow

**Comment by JIMENOFONSECA** [comment]
@daren-thomas would this be ok?

**Comment by daren-thomas** [comment]
Sure. I'll work on it.

**Comment by daren-thomas** [comment]
Moving this to the next milestone because I don't think I'll get it done in this one in time.

**Comment by daren-thomas** [comment]
Architecture / Workflow: how do the modules interconnect with each other?
