### ISSUE TITLE
Create plots of the 2000 Watt society benchmark

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#182]
@martin-mosteiro  i believe this could be a good way to get you started. 

The idea will be to create automated graphs comparing the CO2 emissions Vs. Primary energy per building and per scenario.

Matplotlib in python can help to do the work. Refer to graphs.py for an example of how to use the library

![img_4276](https://cloud.githubusercontent.com/assets/8973186/15109790/d362fa26-160f-11e6-9c83-4812077f656f.JPG)

**Comment by JIMENOFONSECA** [comment]
This diagram can be done with the output of the Total_LCA_emissions file

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro maybe we could enable the selection of a list of scenarios from Arcgis? this is done with the heatmaps.py script. coudl we then enable the script to receive a list with the location of different scenatios (it could be also one). listscenarios = [locatorA, locatorB etc..) and make the graphs?

**Comment by martin-mosteiro** [comment]
Certainly. I do think choosing only two scenarios is quite restrictive and I think your proposal is a good way to expand the possibilities. Should I take care of that?


________________________________________
Von: JIMENOFONSECA [notifications@github.com]
Gesendet: Montag, 23. Mai 2016 11:53
An: architecture-building-systems/CEAforArcGIS
Cc: Mosteiro Romero  Martin; Mention
Betreff: Re: [architecture-building-systems/CEAforArcGIS] Create plots of the 2000 Watt society benchmark (#182)

@martin-mosteiro<https://github.com/martin-mosteiro> maybe we could enable the selection of a list of scenarios from Arcgis? this is done with the heatmaps.py script. coudl we then enable the script to receive a list with the location of different scenatios (it could be also one). listscenarios = [locatorA, locatorB etc..) and make the graphs?

�

**Comment by JIMENOFONSECA** [comment]
yep :-). @daren-thomas coudl do the magic with the interface to let the user select from one to n scenarios.

**Comment by JIMENOFONSECA** [comment]
<img width="585" alt="screen shot 2016-05-24 at 6 01 12 pm" src="https://cloud.githubusercontent.com/assets/8973186/15500150/0ccbbc32-21da-11e6-8c1b-b63e7b052c25.png">

**Comment by JIMENOFONSECA** [comment]
This is basically what we are pointing out to have. If we can not achieve it with matplotlib, we might do the next:
1. Create a template of the graph in an excel worksheet A and put it in our DB.
2. Make A dependent on a worksheet B with all the data points.
3. Make a script in python that puts the data we need to plot into B.
4. Make a script in python that prints out A once the data is in B.

Excel has the possibility that if the spaces are null it will remove the Datapoints and the legend automatically.
The user must have ms excel installed (which almost any computer has nowadays). Not sure if we should worry about it.

**Comment by JIMENOFONSECA** [comment]
Maybe we can look up nicer graphs in python?

**Comment by martin-mosteiro** [comment]
I think making graphs like these with Python wouldn’t be a problem at all - we can then see if it looks okay or if it’s not aesthetically pleasing enough :)

One caveat, though: SIA 2040 provides 2000 W society target values for the following building types: Residential, Office, and Schools (i.e., no general values for all building types). What we did during the test run was to generate graphs for each of these building types, but that ignores any other building type.

I see these graphs have different “Target 2050” values than the ones on SIA 2040, though, so maybe I’m missing something?





On 24 May 2016, at 12:05, JIMENOFONSECA <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2016-05-24 at 6 01 12 pm]<https://cloud.githubusercontent.com/assets/8973186/15500150/0ccbbc32-21da-11e6-8c1b-b63e7b052c25.png>

**Comment by JIMENOFONSECA** [comment]
So i talked to clayton and we see there are three options to improve the graphics and analytics of the CEA tool considerably:

1. there is the plotly library in python https://plot.ly/~cparmer2/489/state-2-vs-state-1/
2. there is the seabborn library in python https://web.stanford.edu/~mwaskom/software/seaborn/
3. there is D3 in Jva script. https://github.com/d3/d3/wiki/Gallery

Plotly is free as long as all content is open. It offers dynamic visualization (i believe a must in the CEA for the future).
Seaborn is free and basically improves the visualization of matplotlib. The downside, it is static, flat.
3D is the rollsroyce of open source visualization for now. It is in Java script, but calling it from python might be an option. The good thing is that @daren-thomas worked with it for the DPV tool. @martin-mosteiro  you might want to talk to him about its feasibility.

Other than this, clayton created a series of ipython notebooks describing a series of novel visualization methods of simulated data. we might want to implement some of this in the CEA tool.

http://nbviewer.jupyter.org/github/cmiller8/PythonforBuildingAnalysts/blob/master/2_AnalyzingEnergyPlusOutputFile/EnergyPlusOutFileAnalysis.ipynb

http://www.datadrivenbuilding.org/EnergyPlus-Output-Processing

**Comment by martin-mosteiro** [comment]
As promised, here are the benchmark graphs at the moment. 
[Benchmark_plot_20160601_170203.pdf](https://github.com/architecture-building-systems/CEAforArcGIS/files/295357/Benchmark_plot_20160601_170203.pdf)
- 2000 W target calculated based on SIA standard 2040, but not every building is included (2000 W targets are not defined by all building classes).
- Current situation based on Inducity paper *for now*. This is certainly not an ideal solution, but good enough for now, I'd say.
- Mobility based on SIA 2039, also doesn't include all classes. The standard provides MJ and kg CO2/m2, for each occupancy type - since in all buildings in the reference case have only one occupancy type, all buildings with the same occupancy appear as a single point on the plot - again, not ideal, but it's a direct consequence of the case at hand.
- SIA 2040 benchmark is calculated for whatever scenario is selected first. This could be defined differently in the future.
- These graphs will be made prettier and interactive based on Jimeno's suggestions above after the workshop.
