### ISSUE TITLE
Cover Art for dev-docs is ungrammatical

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#183]
"A Manual for Developer of CEA" is not English. Maybe "A Manual for Developer*s* of CEA"?

**Comment by shizhongming** [comment]
Yea, I knew it is not grammatically correct. It is not necessarily a sentence. Just to emphasise the three key word "Manual", "Developer", "CEA". Anyway, I am willing to change that.

**Comment by JIMENOFONSECA** [comment]
@shizhongming Please refer to Contributor instead of Developer for the future

**Comment by shizhongming** [comment]
@JIMENOFONSECA  ok~
