### ISSUE TITLE
Add "About" script to toolbox

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#185]
Include information like numpy/pandas/scipy versions, version of toolbox (?), Credits / License

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still the case? would you take care of it?

**Comment by daren-thomas** [comment]
Sure. I'll take care of it.

**Comment by daren-thomas** [comment]
I've had a thorough look at how the tools work in ArcGIS and it doesn't really work. There is no elegant way to do this. There is, however, the possibility to add waaay more documentation to the tool, and I will add that as a separate issue instead.
