### ISSUE TITLE
Rename `__init__.py` in reference-case to `README.md`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#186]
Or something similar (`DOC.md` or `INFO.md` or `FILES.md`) and include a description of the contents of the folder. `__init__.py` is reserved for python packages and the reference-case does not contain python code! But I love Jimeno's idea of having marker files to force the folder structure in github and this is an excellent opportunity to make the reference-case self-describing.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still the case? would you take care of it?

**Comment by daren-thomas** [comment]
yes, it is still the case. I will take care of it.

**Comment by JIMENOFONSECA** [comment]
This is a year old issue. @daren-thomas is this still the case?.

**Comment by daren-thomas** [comment]
Yes. But I think we can take the easy route of just removing all the `__init__.py` files. The `InputLocator` should be able to handle folders that do not exist yet. Check out PR https://github.com/architecture-building-systems/cea-reference-case/pull/9

**Comment by JIMENOFONSECA** [comment]
That will be great!

Best, Jimeno

On 20 Mar 2017, at 21:43, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes. But I think we can take the easy route of just removing all the __init__.py files. The InputLocator should be able to handle folders that do not exist yet. Check out PR architecture-building-systems/cea-reference-case#9<https://github.com/architecture-building-systems/cea-reference-case/pull/9>

**Comment by daren-thomas** [comment]
waiting for reference-case folder to stabilize with the new .dbf files. also, @JIMENOFONSECA consider merging the PR in the reference case repository.

**Comment by JIMENOFONSECA** [comment]
done!
________________________________
