### ISSUE TITLE
Subclass `InputLocator` for documenting interface

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#189]
Create a `LoggingInputLocator` subclass / decorator of `InputLocator` that tracks all calls to `InputLocator` and use this to gather info about what scripts use what input data. Use this class for the test methods in the scripts.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still the case? would you take care of it?

**Comment by daren-thomas** [comment]
Closed. See my sandbox for the implementation.
