### ISSUE TITLE
Properties File Fix

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#19]
-	Change name of dataframe `q`
-	q1.E4 will probably have to be changed - it is an equipment type in industrial processes!

**Comment by daren-thomas** [comment]
**Note:** these are two separate issues! Take care not to close this without resolving both (especially the "q1.E4" point will probably live longer than the "dataframe q" point, which is really only a very simple refactoring.

**Comment by JIMENOFONSECA** [comment]
it addresses issue #99 and it is solved with the pull request of #103
