### ISSUE TITLE
A function that creates full reports including intermediate results for testing new code

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#192]
A function that writes all hourly intermediate results to *.csv if a flag for "testing" is active.

**Comment by daren-thomas** [comment]
@gabriel-happle, this is a good idea - you should expand on this as it is currently not possible to implement (it is still a little vague)

- which hourly intermediate results do you want to write out? (I believe the demand script actually already does do that?)
- what functions do you want to check with this?
- how would you compare results with previous versions of the software?

**Comment by gabriel-happle** [comment]
@daren-thomas
 I just did this and moved it to the contributions. I will make a pull request for my branch now. I plan to use it for now for manual comparison. A date and time tag is included in the file name, so that files are never over written

**Comment by gabriel-happle** [comment]
@daren-thomas I think this could be closed.
