### ISSUE TITLE
Fixing calculations for area of study

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#201]
When calculating the demand, we focus on the study area (containing 274 buildings). This also applies when calculating the operational energy.
However, when calculating the embodied energy, the analysis is conducted on the whole modeled area (containing 1482 buildings). Would it be possible to make the embodied energy calculations on the study area only as well?

**Comment by amraladdin** [comment]
@JIMENOFONSECA and this one? :+1:

**Comment by JIMENOFONSECA** [comment]
I will probably split the input files to a shapefile with data about the surroundings and another file with the buildings in the area of interest. Would this make sense?. or should we keep the data for all 1440 buildings?

**Comment by JIMENOFONSECA** [comment]
But, this might constrain the study of opportunities in the surroundings too.

**Comment by martin-mosteiro** [comment]
Indeed, this would restrict the opportunities for studying the surroundings. However, at the moment, when analyzing the PEN and GHG (say, for example, in the 2000 W society graphs) we get about 1400 data points for embodied energy and emissions and only 274 for the area of study, such that it's a bit of an "apples and pears" comparison (or rather "apples and a lot more apples"). Maybe we could just calculate the results for the zone of study and those outside of it but keep them separate? Or I could just adjust the script for the graphs to only plot the buildings within the zone of study :)


________________________________________
Von: JIMENOFONSECA [notifications@github.com]
Gesendet: Montag, 23. Mai 2016 11:30
An: architecture-building-systems/CEAforArcGIS
Betreff: Re: [architecture-building-systems/CEAforArcGIS] Fixing calculations for area of study (#201)

But, this might constrain the study of opportunities in the surroundings too.

�

**Comment by JIMENOFONSECA** [comment]
True...in order to avoid other issues, I will just fix it :-)

**Comment by amraladdin** [comment]
Great!

**Comment by JIMENOFONSECA** [comment]
done! now this should be working. We use only the buildings in the zone of interest
