### ISSUE TITLE
Create reference-case with smaller zone of study

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#204]
For testing purposes this would be great: Have our reference-case, but only look at, oh, 10 buildings. That would make running the calculations a lot faster and we would test our code more often!

**Comment by daren-thomas** [comment]
Make sure the reference-case contains special buildings! (e.g. no conditioned floor area)

- this should be a mix of any edge cases the software has!

**Comment by JIMENOFONSECA** [comment]
#113 replaces this
