### ISSUE TITLE
Implement economizer for HVAC cooled buildings

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#206]
Free mechanical cooling at night at certain indoor and outdoor temperature conditions.

**Comment by gabriel-happle** [comment]
possible duplicate of #256 (Free cooling)

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle if it is a duplicate, can this be closed?

**Comment by gabriel-happle** [comment]
Actually Economizer is totally different from free cooling. I didn't know at the time. I learned that in Singapore context the conditions are never favorable to use an Economizer. In Switzerland however, this is different. Maybe @martin-mosteiro has to decide?

**Comment by martin-mosteiro** [comment]
Are we talking about night time flushing to cool the building? Probably good to have in Switzerland, no?
