### ISSUE TITLE
Update `gv.report_variables` for `schedule_maker`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#207]
Changes introduced by the schedule maker branch (and solar to radiation) have made the current version of `report_variables` obsolete: not all variables exist!

The current list of missing variables is: 
- `q_int` 
- `Qcdataf`
- `Qcrefrif`

**Comment by daren-thomas** [comment]
@gabriel-happle do you want to take a look at this?

**Comment by gabriel-happle** [comment]
Yes.
