### ISSUE TITLE
Tree organizational script structure for CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#214]
![capture](https://cloud.githubusercontent.com/assets/8973186/15529287/dfea069c-227e-11e6-959a-3a08ead544a1.PNG)

**Comment by JIMENOFONSECA** [comment]
One thing we discussed sometime ago is the idea of making a folder structure for the current and future scripts of the CEA tool. We should definitely do this for the next release (even if we do not have the supply and optimization side ready) as it will help to show users to keep track of future releases.

I included an example of how other toolboxes are organized in ArcGis.

**Comment by JIMENOFONSECA** [comment]
This is how i can see the tree taking place for the cea tool: @architecture-building-systems/cea  Please feel free to comment and change until next friday 27.05.2016.

**Comment by JIMENOFONSECA** [comment]
1 - CEA
1.1. DEMAND MODEL
1.1.1. SIMPLE DYNAMIC
1.2. RESOURCE POTENTIAL
1.2.1 SOLAR 
1.2.3 AMBIENT HEAT
1.2.4 WIND
1.2.5 WASTE
1.3. OPTIMIZATION
1.3.1 CONVERSION SYSTEM
1.3.1.1 NGSA-II + MILP
1.3.1.2 OPS + MILP
1.3.1 NETWORK
1.3.1.1 NGSA-II + MILP
1.3.1.2 OPS + MILP
1.4. ANALYSIS
1.4.1. SENSITIVITY ANALYSIS
1.4.2. LIFE CYCLE ANALYSIS
1.4.3. BENCH MARKING
1.5 PLOTS
1.4.4.1 HEAT-MAPS
1.4.4.2 TIME-SERIES
1.4.4.3 TOTALS
1.6 WORKFLOW (predefined either keppler or model builder workflow connecting all scripts)
1.6.1 LOW RESOLUTION SIMULATION
1.6.2 HIGH RESOLUTION SIMULATION

**Comment by shanshanhsieh** [comment]
I edited the part 1.2 and added part 1.3 TECHNOLOGIES. It has became quite a long list now, maybe we could keep it part 1.3 like this now until we have other new technology models.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas @martin-mosteiro  @gabriel-happle @amraladdin @shizhongming please comment in the folder structure of the CEA folder. today i expect to start implementing

**Comment by gabriel-happle** [comment]
I think the demand model should also have sub folders.
E.g.
- Ventilation Model
- Occupancy Model
- Building Equipment
-- HVAC Model (could also be a sub folder of Ventilation Model?)
etc.

**Comment by daren-thomas** [comment]
Please make sure folder names have no spaces in them. Especially source code folders. While often spaces and non-ascii characters will work, it does tend to make everything more tedious. We could save ourselves some headaches.
- ventilation-model
- occupancy-model
- hvac-model

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this will change the folder structure of the repository as discussed, i wonder if this is part of the "Architecture" you are investigating.  The next step will be to accommodate the scripts we have in such structure. it could become messy so better we agree on one
