### ISSUE TITLE
Facilitate migration from shapefiles with .DBF

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#217]
So in order to facilitate the migration of shape-files but still maintain functionality, we might consider using only .dbf files instead of .shp files. (excl. buildings geometry, terrain and zone of study).

It will be faster to read by other formats such as CityGML in the future. It will avoid using geopandas potentially. Which is kind of hard to get running.

**Comment by daren-thomas** [comment]
why?

**Comment by daren-thomas** [comment]
also, .dbf cannot be directly read from pandas as far as i could find out...

**Comment by JIMENOFONSECA** [comment]
well....i already did it. it is faster by 0.25 sec than reading a shapefile

**Comment by daren-thomas** [comment]
but... why?

**Comment by JIMENOFONSECA** [comment]
can you specify?

**Comment by daren-thomas** [comment]
seriously, jimeno, i must have missed the issue with shapefiles. what was the problem again? (since we still need them for the building geometry as mentioned above...) what is the natural format for arcgis? it's not dbf right?

**Comment by daren-thomas** [comment]
why not sqlite for that matter? or any other format?

**Comment by JIMENOFONSECA** [comment]
so...we need just one shapefile not eight to store geometry. 
dbf can be read in arcgis too and work with other shafiles. dbf can be open from excel too.

**Comment by JIMENOFONSECA** [comment]
does sqlite offers those options? if so, i believe it will be a better option than dbf

**Comment by daren-thomas** [comment]
good. thank you for explaining 😊 (i just needed a motivation for the change because i didn't understand) still... i would like this kind of change (that requires changing the whole documentation and the test cases etc. to have more discussion before we do them - we still need to fix up the code base to be more readible etc...)

**Comment by JIMENOFONSECA** [comment]
totally agree. I also do not know if in terms of interoperability it is better to keep the shapefiles, so it easier for the user to map directly all data. However i found that the way we are doing the shapefiles might be mixing the data in properties.py :-(

**Comment by JIMENOFONSECA** [comment]
right at the time of creating a shapefile and saving it. (this was code that i made up) @daren-thomas coudl you take a look if this is the right way?. then we can leave this issue open for another time

**Comment by JIMENOFONSECA** [comment]
@daren-thomas from the workshop, i see this change does not make sense anymore. if we exchange the shapefiles for .dbs, the users will not be able to select polygons and change the databases in arcgis. it will drastically reduce user experience. i close the issue.
