### ISSUE TITLE
Update dev process for sandbox and contributions

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#224]
Can we move sandbox and contributions development to two respective branches 'sandbox' and 'contributions'?

We can then merge back to master when a contribution or sandbox item needs to be accessible to other people / is finished. This would stop some of the "bleeding" (i.e. *noise*) of sandbox development into the `github_core` channel.

**Comment by JIMENOFONSECA** [comment]
Yes i am doing this
