### ISSUE TITLE
Weather files don't create different results

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#234]
When we made simulations using Zurich and Singapore weather files, the results came back identical. Any idea what's the reason behind that?
@JIMENOFONSECA  @daren-thomas

**Comment by daren-thomas** [comment]
I'll look into that right now! Good catch...

**Comment by daren-thomas** [comment]
@amraladdin: can you try it out again on the master branch? I think I found the bug and fixed it.

**Comment by amraladdin** [comment]
@daren-thomas @JIMENOFONSECA 
In order for the weather file to work, I have to run the radiation file per weather, is that correct?

**Comment by JIMENOFONSECA** [comment]
Yes

Best, Jimeno

On 14 Jul 2016, at 18:50, Amr Elesawy <notifications@github.com<mailto:notifications@github.com>> wrote:


@daren-thomas<https://github.com/daren-thomas> @JIMENOFONSECA<https://github.com/JIMENOFONSECA>
In order for the weather file to work, I have to run the radiation file per weather, is that correct?

**Comment by amraladdin** [comment]
@JIMENOFONSECA Yes, I'll check them as soon as I finish installing the latest ArcGIS 10.4 and CEA

**Comment by JIMENOFONSECA** [comment]
@amraladdin could you add the estimate, thanks?

**Comment by amraladdin** [comment]
This issue is cause I didn't run the radiation at the time.

**Comment by amraladdin** [comment]
So I think we can close this issue now. @JIMENOFONSECA agree?
