### ISSUE TITLE
Move weather files to separate directory

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#235]
Currently, they are part of the country-specific db stuff (cea/db/CH/...)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA : Do you have input on this?

**Comment by JIMENOFONSECA** [comment]
yes, we can do that. please feel free to move it to a separate directory in the databases.

**Comment by daren-thomas** [comment]
on branch `235-move-weather-files-to-separate-directory` but I need to wait for PR #423 to be merged first. @JIMENOFONSECA can you look into that?

**Comment by JIMENOFONSECA** [comment]
done!
________________________________

**Comment by daren-thomas** [comment]
fixed in PR #433
