### ISSUE TITLE
Plots - Benchmark & Demand Graphs 

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#240]
When comparing more than 2 plots, the legend starts to disappear because the text goes out of the page border. Same happens when simulating hotter climates, but for the values as well.

**Comment by amraladdin** [comment]
@martin-mosteiro Should I assign this task to you?

@JIMENOFONSECA any idea who was responsile for the Demand graph plots to fix this point?

**Comment by martin-mosteiro** [comment]
Sure, I'll take care of it.


________________________________
Von: Amr Elesawy [notifications@github.com]
Gesendet: Donnerstag, 14. Juli 2016 12:47
An: architecture-building-systems/CEAforArcGIS
Cc: Mosteiro Romero Martin; Mention
Betreff: Re: [architecture-building-systems/CEAforArcGIS] Plots - Benchmark & Demand Graphs (#240)


@martin-mosteiro<https://github.com/martin-mosteiro> Should I assign this task to you?

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> any idea who was responsile for the Demand graph plots to fix this point?
