### ISSUE TITLE
fix create_windows

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#248]
There are a lot of (important) FIXME's in the create_windows function. Also, we could
- rename the inputs, suggestion: surface_properties, architecture (same as get_prop_RC_model)
- rename the columns in the output
- suggestion: angle, are, height_above_ground, height_in_zone, name, orientation
- especially Name: that seems to be the standard in all the other dataframes (and yes, i think we should move it to lower-case and id would also be a good alternative)

**Comment by daren-thomas** [comment]
@gabriel-happle, do you want to work with me on this?

**Comment by gabriel-happle** [comment]
@daren-thomas Sorry, didn't see this notification. The output of this function is actually not used at the moment. It would be for more sophisticated infiltration/ventilation calculation. Also this issue has to be properly addressed as soon as we select our geometry data type of the future. Maybe we can just deactivate it for now?

**Comment by daren-thomas** [comment]
I suggest removing the whole function, if it is not being used. We can still find it in the revision history if we ever need it again, but having "dead" code in the codebase is a bad idea: It makes it harder to understand what is going on and code tends to "rot" over time.

Could you remove it and we revisit this function when we are ready for a more sophisticated infiltration/ventilation calculation?

**Comment by gabriel-happle** [comment]
Actually I'm working on exactly that.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle what is the status of this? is it still an issue?

**Comment by gabriel-happle** [comment]
Whole function will be obsolete with higher LOD inputs. Probably no action needed.

**Comment by JIMENOFONSECA** [comment]
Closing as the function is not used anymore, The geometry generator of the radiation_daysim does this work already
