### ISSUE TITLE
CEA in Arcgis not working

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#261]
After refactoring the tool used to work form arcgis. However it just executed the scripts and then it finished without producing any output. We noticed this issue later after merging the refactoring of functions.py

the error is relatively simple to solve without needed to reverse any previous merge.  I might need a hand. @daren-thomas can we talk about this when you are back?

the main issue is happening in cea/GUI/toolbox.py

Other than that, the tool works perfectly form the source.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas could you take a look at this? I tried it to fix it without success

**Comment by daren-thomas** [comment]
@JIMENOFONSECA i am currently looking into this!

**Comment by daren-thomas** [comment]
hey... for a bug report: which script executed without results? what results were expected?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: assigning back to you to close. I have checked on the master branch. It seems to be working fine! (i did merge some fixes though, so maybe that helped?)

Also, it is really hard to fix a bug as described above. What is the issue? What were the error messages? Where there any? Which tool did you run? (we have ten of them!) Where did you look for the missing data?

**Comment by JIMENOFONSECA** [comment]
I get the next message while running the demand tool, any advice?
![capture](https://cloud.githubusercontent.com/assets/8973186/17539726/0f75d3c8-5ee3-11e6-8f82-e1257ffa4bfd.PNG)

**Comment by daren-thomas** [comment]
yes, I might have an idea. I fixed a similar issue with the port to 10.4.
what branch is this on?

**Comment by daren-thomas** [comment]
I have synced a fix to master that should fix this. Please verify.
