### ISSUE TITLE
Incomplete parts in the technologies

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CEAforArcGIS#272]
- Make sure all technology scripts all contain three parts of functions: technical conversion, cost calculation and test functions. An complete example is the `photovoltaic.py` script.
- Add borehole technology for geothermal energy utilization.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this part of this milestone? could we add an estimate too?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh what is the status and plan to integrate this? is it still an issue? i suggest to put only technologies we need to incorporate soon.. the issue is 8 months old.

**Comment by shanshanhsieh** [comment]
Yes, we can close this issue for now since these aspects will be updated when we add new technologies.
