### ISSUE TITLE
Distinguish the area used for PV and SC

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CEAforArcGIS#273]
The optimization script currently determine the percentage used from PV and SC respectively with the maximum available install area. PV and SC might occupy the same area following this calculation.
A re-iteration step should be implemented to ensure no overlapping installation of PV and SC panels.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @BhargavaKrishnaSreepathi is this still necessary?

**Comment by shanshanhsieh** [comment]
I believe yes, otherwise the solar potentials will be over-estimated.
This issue falls in category 1 - stuff we are definitely going to do

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @BhargavaKrishnaSreepathi could you coordinate this inside the optimization?

**Comment by BhargavaKrishnaSreepathi** [comment]
@shanshanhsieh : Can we meet regarding this? I would like to know what we want to do

**Comment by BhargavaKrishnaSreepathi** [comment]
The total potential of PV, PVT, SC of a neighborhood is calculated apriori and this value is used to calculate the individual portion for different configurations. So the estimation of all the technologies is consistent. That is to say either the overestimation or underestimation is consistent. We feel that going in to further granularity is not necessary and is painstaking. Thus closing the issue.
