### ISSUE TITLE
Investigate numba AOT to spead up calc_tm

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#279]
Numba might be able to speed up calc_tm - using either JIT or AOT. Investigate this in a branch and merge if successful.

This is an (imprecise) measurement of running the code before optimization:

![image](https://cloud.githubusercontent.com/assets/2969564/17665517/d02479f0-62fb-11e6-9bec-3713bf5a18e4.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: I'm about to close the issue. I was just wondering if you did any speed tests? I did some on my computer, that uses 8 CPUs - when single processing, the speedup is really big, but when multiprocessing, the overhead of multiprocessing eats up some of the gains (still faster, just not by such a large percent) - so I was wondering if on your machine (4 CPU's? the demand script tells you how many it is using) it was faster?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I am using an 8 core CPU in windows for this week. I did not do any speed test though.
