### ISSUE TITLE
Reducing calculation time for Demand Graphs

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#286]
Daren did his magic on the Demand analysis calculation. Now it runs on an 8 processor PC in 1 minute 53 seconds.
However, the Demand Graphs calculation still takes around 10 minutes to calculate. Can we also reduce this analysis calculation time?

**Comment by JIMENOFONSECA** [comment]
Yeah i was wondering about the same. would it be feasible to implement it?

**Comment by daren-thomas** [comment]
it looks like this can be closed with the merge of #313
