### ISSUE TITLE
Issue with the Demand Graphs Plots

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#287]
After creating the Demand Graphs Analysis, I found 2 points when opening one of the building results:
- It seems there's an overlapping between the title of the horizontal axis (DATE) with the graph afterwards, or with the legend at the end of the first page.
- The second page contains a graph that has no value or title (the graph on the left), what is this graph supposed to show?

@JIMENOFONSECA @daren-thomas Who should I assign this issue to?

Here attached a screen shot of one of the demand graphs PDFs

![issue_demand graphs](https://cloud.githubusercontent.com/assets/16256867/17775213/8269bef6-6557-11e6-85a0-f3453b826e18.jpg)

**Comment by JIMENOFONSECA** [comment]
I will fix it..

Best, Jimeno

On 18 Aug 2016, at 21:22, Amr Elesawy <notifications@github.com<mailto:notifications@github.com>> wrote:


After creating the Demand Graphs Analysis, I found 2 points when opening one of the building results:

  *   It seems there's an overlapping between the title of the horizontal axis (DATE) with the graph afterwards, or with the legend at the end of the first page.
  *   The second page contains a graph that has no value or title (the graph on the left), what is this graph supposed to show?

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> @daren-thomas<https://github.com/daren-thomas> Who should I assign this issue to?

Here attached a screen shot of one of the demand graphs PDFs

[issue_demand graphs]<https://cloud.githubusercontent.com/assets/16256867/17775213/8269bef6-6557-11e6-85a0-f3453b826e18.jpg>

**Comment by daren-thomas** [comment]
Reopened as merge has not happened yet.
