### ISSUE TITLE
Update documentation to include installing numba

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#288]
The latest version of CEA uses numba, which needs to be installed. On the Anaconda prompt:

`$ conda install numba`

**Comment by daren-thomas** [comment]
I will probably refactor the code to remove the numba requirement instead: Compiling the *.pyd file can be done from my sandbox and we only need to ship the new files.

**Comment by daren-thomas** [comment]
see #321 for another way to do this: The compilation step is removed from the scripts to a cea/utilities/compile_pyd_files.py script. Therefore, numba is not required to run the CEA. The compilation requires a whole development environment to run anyway, which is waaaay to much for casual users to install!

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: Please test the corresponding pull request #321 and merge if satisfied.
