### ISSUE TITLE
Reference case Hochschulquartier data

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#289]
@daren-thomas: Could you look up who was the contact person for the measured data from the Hönggerberg campus? (UMEN -?- project)

They could provide us with information for the Hochschulquartier as well.

**Comment by daren-thomas** [comment]
Here are my notes (edited to remove sensitive information) from the meeting way back when:

Datum: 31. Juli 2013, 09:00

Beteiligte:

	* Markus Zubler, Ferg und Rainer Schwab (ETH Bauten)

	* 
		* Schwab Rainer (BA), Fergg Ueli (IS), Zubler Markus (PFM)

	* Daren Thomas, Christian Hersberger (SuAT)


Generell

	* HIT + HPL + HPZ gekühlt
	* Gebäude besichtigen (Reinräume / Speziallabore)


Pläne / Flächennutzungen

	* Geschosspläne mit Flächennutzungen für alle Gebäude 
	* => PDF => www.plan.ethz.ch
	* DWG auch vorhanden, auf Anfrage
	* => Meldeportal Immobilien (Stichwort Plan => Bestellung Pläne & Raumdatenlisten)


3D-Modell

	* von Modell im HIL (David Müller, Stab VS)



Energieverbräuche pro Gebäude: 

	* www.betrieb.ethz.ch => Energiedaten 
	* SILOVEDA=> Benutzername + pwd beantragen, Rechte analog Rainer Schwab (Frau Marta Bless)

	* Wegleitung lesen
	* thh = Gesamt-Campus Hönggerberg

**Comment by martin-mosteiro** [comment]
Thanks! I'll take it from here then.

**Comment by daren-thomas** [comment]
Maybe you want to talk to Zubler Markus (PFM stands for Port Folio Management, if I recall correctly). You can mention contact with me and Christian Hersberger and the date if you like. We have access to the SILOVEDA platform, but I would suggest we regain access for the CEA project as access was originally granted for the UMEM project and that is now closed.
