### ISSUE TITLE
Full reports not working with "tsd" as dict

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#293]
The option for full reporting does not work any more for `tsd` variable as `dict`.

**Comment by gabriel-happle** [comment]
@daren-thomas is it OK that I just assigned you?

**Comment by daren-thomas** [comment]
@gabriel-happle yes. It seems this is blocking a few things right now so I will handle it first thing.

**Comment by daren-thomas** [comment]
Fixed with PR #302...
