### ISSUE TITLE
Organize case studies in private repo

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#295]
Get the private repo in order and document this. Discuss it with the group.

**Comment by daren-thomas** [comment]
wishlist:
- rename "reference-case (HQ)" to "reference-case-hq"
- make sure radiation data is present in each reference case
- delete old reference cases: 
  - reference-case dbf
  - reference-case old
  - reference-case
  - NOTE: they will still sit in GitHub forever, but you can add a tag to the current version before deleting if you want quick access (hint: we probably don't)
- move the measurements folder to reference-case-zug/baseline/measurements

**Comment by daren-thomas** [comment]
Also, we can update `.gitignore` to ignore the `.csv` files in `outputs/data/...`

**Comment by JIMENOFONSECA** [comment]
I think it is good to organize it. Would you go ahead with the changes?

On 29 Sep 2016, at 22:23, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


wishlist:

  *   rename "reference-case (HQ)" to "reference-case-hq"
  *   make sure radiation data is present in each reference case
  *   delete old reference cases:
     *   reference-case dbf
     *   reference-case old
     *   reference-case
     *   NOTE: they will still sit in GitHub forever, but you can add a tag to the current version before deleting if you want quick access (hint: we probably don't)
  *   move the measurements folder to reference-case-zug/baseline/measurements

**Comment by daren-thomas** [comment]
Sure. You OK with the proposed changes? I suggest also removing the `__init__.py` files from the reference cases...

**Comment by JIMENOFONSECA** [comment]
yes, now we have a way to create the folders automatically right? does this include the folders for optimizaiton?

**Comment by daren-thomas** [comment]
Hm. Not yet. But I have an idea :) I'll create an issue for this.

**Comment by JIMENOFONSECA** [comment]
done!
