### ISSUE TITLE
Discrepancy between Glossary and Output results

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#296]

**Comment by daren-thomas** [comment]
Can you be more specific please? What is the discrepancy?

**Comment by amraladdin** [comment]
Yeah yeah, wait, it was a mistake that it got posted... I didn't put the description yet :)

**Comment by amraladdin** [comment]
While organizing the output values for the Total_Demand.csv, I realized there is a bit of discrepancy between what is in the .CSV file and the Documentation Glossary. Here is what I found so far:

1. Trww0_C exists in the documentation (under Scenario Outputs>Data>Peak Values), but it's not in the output of the Total_Demand.csv .

2. In the same section of the documentation (under Others) the value Vw0_m3 exists as the total fresh water consumption (cold + hot), while in the output I have `Vw_m3yr,Vww0_m3,Vww_m3yr`, so should the output value Vw_m3yr become Vw0_m3yr?

3. The values `Vww0_m3,Vww_m3yr` are not described anywhere in the glossary Data outputs.

4. The following values are in the documentation but not in the Total_Demand.csv file `Eauxf0_kWh,Edataf0_kWh,Epro0_kW,Ef0_kW,Qcdataf0_kW,Qcref0_kW,Qcs0_kW,QCf0_kW,Qhs0_kW,Qww0_kW,QHf0_kW`

5. `Qhprof_MWhyr` is one of the outputs, but it is not in the documentation.

6. `Aroof_m2,GFA_m2,occ_pax` are not mentioned in the Yearly Values, only `occ_pax` is mentioned in the Hourly Values.

That's all I found for now, I believe some of these comments might apply on the demand-per-building outputs as well... So I'll check that and report here.

**Comment by amraladdin** [comment]
In terms of the Demand Outputs per building, here are my notes:

7. Why aren’t the floor area part of the outputs?

8. Final electricity in industrial processes is abbreviated in the Hourly Values as `Epro_kWh`, while the same definition in the Yearly Values is written as `Eprof_MWhyr`, so shouldn’t we fix it to either `Epro` or `Eprof`?

9. `Qhprof_kWh,Qww_tankloss_kWh,Ecaf_kWh,Tww_tank_C,Tsref_C,Trref_C,Tsdata_C,Trdata_C,mcpref_kWC,mcpdata_kWC` are outputs in the .csv file but not in the documentation under (Hourly Values).

**Comment by amraladdin** [comment]
For the Embodied Energy and Operational Energy, I strongly suggest the following:

1. To change in the documentation the title `Primary energy demand and emissions` to `Operational energy demand and emissions`.

2. Differentiate between the names of the output results to the following:

    * For Embodied Energy `E_ghg_ton,E_ghg_kgm2,E_pen_GJ,E_pen_MJm2`

    * For Operational Energy `O_ghg_ton,O_ghg_kgm2,O_pen_GJ,O_pen_MJm2`

**Comment by amraladdin** [comment]
@daren-thomas @JIMENOFONSECA Who can be assigned this task?

**Comment by JIMENOFONSECA** [comment]
@amraladdin i think you have identified different issues here and they are worth spliting in three:
1. discrepancies documentation and total_demand.csv
2. eprof and epro related comment
3. embodied energy and emissions folder.

would you mind creating a separate issue for each?
As for the first. I believe we maintain the documentation according to the tool outputs. So you can update this.
As for the second i can help.
As for the thrid, would you mind @martin-mosteiro making the changes?. It is an easy fix but you might want to cross check that these changes does not brake the benchmark graphs...

**Comment by martin-mosteiro** [comment]
Sure, that's an easy fix. @amraladdin please assign the issue to me once you've created it.

**Comment by amraladdin** [comment]
Done :) Thanks!

**Comment by amraladdin** [comment]
Oh, sorry, I didn't read Jimeno's comment... Ok, I'll set the issues and assign @martin-mosteiro

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: Good call. Maybe we can add this to the contributors manual? An issue should be focused on one thing only?

**Comment by amraladdin** [comment]
Ok, I'm on it.

**Comment by JIMENOFONSECA** [comment]
i agree
