### ISSUE TITLE
Over heating in buildings should be acknowledged 

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CEAforArcGIS#30]
also, the infiltration rate should be adjust accordingly

**Comment by JIMENOFONSECA** [comment]
#16 I belive this should be solve there.

**Comment by gabriel-happle** [comment]
Idea:
(1) According to DIN EN ISO 13792

**Comment by gabriel-happle** [comment]
This issue will also be attacked in #16

**Comment by gabriel-happle** [comment]
Closed for now. Continuing work in #256 and others.
