### ISSUE TITLE
clean up `thermal_loads.results_to_csv()` and move to `utilities.reporting`

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#300]
reduce number of input parameters to `results_to_csv()` and move script to reporting.

**Comment by gabriel-happle** [comment]
@daren-thomas could you take a look at this?

**Comment by daren-thomas** [comment]
@gabriel-happle: sure, will do.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA worked on this with the calibrator branch and I introduced the `DemandWriter` classes. I think this issue can be closed.
