### ISSUE TITLE
Embodied and Operational Energy

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#301]
For the Embodied Energy and Operational Energy, I strongly suggest the following:

1. To change in the documentation the title `Primary energy demand and emissions` to `Operational energy demand and emissions`.

2. Differentiate between the names of the output results to the following:

    * For Embodied Energy `E_ghg_ton,E_ghg_kgm2,E_pen_GJ,E_pen_MJm2`

    * For Operational Energy `O_ghg_ton,O_ghg_kgm2,O_pen_GJ,O_pen_MJm2`

    * For Mobility `M_ghg_ton,M_ghg_kgm2,M_pen_GJ,M_pen_MJm2`

**Comment by martin-mosteiro** [comment]
Separate (but related) note: if the "emissions" script calculates not only the operational greenhouse gas emissions but also the operational primary energy demand... Shouldn't it rather be called "operation"?

Even the output files are called "*_LCA_operation.csv"

**Comment by amraladdin** [comment]
Is this question directed to me or Jimeno?
