### ISSUE TITLE
Warning on embodied energy script

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#303]
The following warning message appears when running the `embodied.py` script:

`C:\Users\User\Anaconda2\envs\esri104\python.exe C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/analysis/embodied.py`
`C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/analysis/embodied.py:95: SettingWithCopyWarning:`
`A value is trying to be set on a copy of a slice from a DataFrame.`
`Try using .loc[row_indexer,col_indexer] = value instead`

`See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy`
  `occupancy_df['mainuse'] = calc_mainuse(occupancy_df, list_uses)`
`done!`
`test_lca_embodied() succeeded`

`Process finished with exit code 0`

The script otherwise runs fine. @daren-thomas: is this a problem?

**Comment by daren-thomas** [comment]
It would become a problem with future versions of pandas. I will look into it.

I am moving this to MS 1.8 as it does not present the error in ArcGIS 10.4 (which has a slightly older version of pandas)

![image](https://cloud.githubusercontent.com/assets/2969564/17884634/a52b822e-6919-11e6-858f-4d1d310e6463.png)
