### ISSUE TITLE
Running Emissions operation error

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#305]
This might not be a huge problem, however, there's a bug.

When running the emissions operation from the CEA Toolbox, if all the following check boxes are ticked (as seen in the photo), then the tool runs smoothly:

![emissions_error00](https://cloud.githubusercontent.com/assets/16256867/17863516/32698af8-689a-11e6-98e6-4e9226cab292.jpg)

HOWEVER, if I untick any of the check-boxes, it gives me the following error:

![emissions_error03](https://cloud.githubusercontent.com/assets/16256867/17863580/726e3130-689a-11e6-8bd0-13678c1b58d8.jpg)

Strangely, the only case where it runs (other than having all the check-boxes marked) is in the following case:

![emissions_error02](https://cloud.githubusercontent.com/assets/16256867/17863595/7d6a544c-689a-11e6-9a6e-755fe339d64d.jpg)

So, who should I assign this issue to? @JIMENOFONSECA @daren-thomas

**Comment by daren-thomas** [comment]
I'm on it.

**Comment by daren-thomas** [comment]
Reproduced error on my machine. I'm looking into it right now.

**Comment by daren-thomas** [comment]
@amraladdin: could you please check out this branch and see if it now works for you?
@JIMENOFONSECA: could you please merge this after testing?

**Comment by amraladdin** [comment]
Hey guys,
I'm sorry but I'm moving out of the office today, so I can't do testing till mid September.
@JIMENOFONSECA or @martin-mosteiro could you test this case instead?

Thanks!
