### ISSUE TITLE
Remove `ExtendInputLocator` by merging with `InputLocator`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#308]
The mobility analysis script uses `ExtendInputLocator` but I think the functionality should be folded into the regular `InputLocator`.

@martin-mosteiro: Could you tackle this? It does not have to be done for MS 1.5 I think...

**Comment by martin-mosteiro** [comment]
Yeah, this was done in order to avoid last-minute modifications of the main code for milestone 1. I'll incorporate these into the main code.
