### ISSUE TITLE
Rename non-renewable primary energy demand in output files

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#312]
To be consistent with #301 and #306, the embodied, operational and mobility non-renewable primary energy demand in the corresponding csv output files need to be renamed as E_nre_pen, O_nre_pen and M_nre_pen, respectively.

**Comment by daren-thomas** [comment]
https://github.com/architecture-building-systems/CEAforArcGIS/pull/317/files
In this pull request, the file `operation.py` is not changed. I think we didn't check the files after the merge and forgot to check in a file...

I am re-opening the issue.

**Comment by martin-mosteiro** [comment]
Fixed this on pull request #328 . As soon as that goes through I'll close this issue.

**Comment by daren-thomas** [comment]
please make sure the scenario plots also work with your changes.

**Comment by daren-thomas** [comment]
is this issue done? #328 was merged. Can you check all the changes are now in master and the plots work? Then we can close this task!

**Comment by martin-mosteiro** [comment]
Everything works fine. Closing the issue now.
