### ISSUE TITLE
Radiation script not working in master

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#320]
Running the radiation script on the **baseline** scenario of the HQ reference case takes only about 3 minutes and generates a file radiation.csv that includes all the buildings in the **masterplan** (not baseline) scenario.

This happens when running both on ArcScene and on the command line. Running it on the command line produces the following errors:

```
C:\Users\User\Anaconda2\envs\esri104\python.exe C:/CEAtoTEST/cea/resources/radiation.py
PyTables is not installed. No support for HDF output.
SQLalchemy is not installed. No support for SQL output.
complete calculating sunrise
complete raw radiation files
complete transformation radiation files
C:\Users\User\Anaconda2\envs\esri104\lib\site-packages\pandas\core\frame.py:2642: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)
done

Process finished with exit code 0
```

**Comment by martin-mosteiro** [comment]
Okay, this is a real issue. I am running the HQ scenario. I ran the radiation script on the baseline case, then on the masterplan case. Then I ran the data helper on the baseline case, then on the masterplan case. Then I ran the demand script on the baseline case and got the following error message:

Executing: DemandTool "C:\reference-case (HQ)\baseline" Zurich
Start Time: Thu Aug 25 16:50:59 2016
Running script DemandTool...
Using python: C:\Python27\ArcGIS10.4\python.exe
Path to demand script: C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py
Adding path to PYTHONPATH: C:\Users\User\Documents\GitHub\CEAforArcGIS
Running demand calculation for scenario C:\reference-case (HQ)\baseline
Running demand calculation with weather file C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\databases\CH\Weather\Zurich.epw
reading input files
done
calculating thermal properties
done
creating windows
Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 185, in <module>
    run_as_script(scenario_path=args.scenario, weather_path=args.weather)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 176, in run_as_script
    demand_calculation(locator=locator, weather_path=weather_path, gv=gv)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 92, in demand_calculation
    building_properties = BuildingProperties(locator, gv)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\thermal_loads.py", line 881, in __init__
    df_windows = geometry_reader.create_windows(surface_properties, prop_architecture)
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\geometry\geometry_reader.py", line 125, in create_windows
    win_wall_ratio = gdf_building_architecture.ix[name[i]]['win_wall']
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\core\indexing.py", line 73, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\core\indexing.py", line 920, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\core\indexing.py", line 89, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\core\generic.py", line 1472, in xs
    loc = self.index.get_loc(key)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\core\index.py", line 1578, in get_loc
    return self._engine.get_loc(_values_from_object(key))
  File "pandas\index.pyx", line 134, in pandas.index.IndexEngine.get_loc (pandas\index.c:3811)
  File "pandas\index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas\index.c:3691)
  File "pandas\hashtable.pyx", line 697, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12336)
  File "pandas\hashtable.pyx", line 705, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12287)
KeyError: 'MP13'

Completed script DemandTool...
Succeeded at Thu Aug 25 16:51:09 2016 (Elapsed Time: 9.58 seconds)

MP13 is one of the buildings on the masterplan scenario, but there is no reason for it to raise an issue on the baseline scenario...

**Comment by martin-mosteiro** [comment]
After copying the reference case from the server again and following the same procedure for the baseline case only, I got the same error message. @daren-thomas could you quickly check if you have the same problem on your computer?

**Comment by martin-mosteiro** [comment]
Same issue when running the Hochschulquartier baseline reference case from the command line...

**Comment by daren-thomas** [comment]
There are a couple of things going on here:

1. Running the script from the command line uses the default weather which is set to Zug 2010 (this might create different weather for you)
2. The radiation script does not work at all on my machine:

```
C:\Users\darthoma\Anaconda2\envs\esri104\python.exe C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py
PyTables is not installed. No support for HDF output.
complete calculating sunrise
Traceback (most recent call last):
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py", line 503, in <module>
    test_solar_radiation()
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py", line 500, in test_solar_radiation
    weather_path=weather_path)
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py", line 137, in solar_radiation_vertical
complete raw radiation files
    radiations.append(calc_radiation_day(day, sunrise, locator.get_temporary_folder()))
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py", line 224, in calc_radiation_day
    radiation_sunnyhours = np.round(Dbf5(route + '\\' + 'Day_' + str(day) + '.dbf').to_dataframe(),2)
  File "C:\Users\darthoma\Anaconda2\envs\esri104\lib\site-packages\simpledbf\simpledbf.py", line 539, in __init__
    self.f = open(dbf, 'rb')
IOError: [Errno 2] No such file or directory: 'c:\\users\\darthoma\\appdata\\local\\temp\\Day_1.dbf'

Process finished with exit code 1
```

@JIMENOFONSECA: Why are the `%TEMP%\Day_N.dbf` files not produced anymore? I suggest you assign this issue to yourself since according to the git history, you made the last changes to the radiation script (cb968f6)

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro @daren-thomas , there were some parts of the code that were commented, so they were not run. My bad sorry. please try again,

**Comment by daren-thomas** [comment]
I have created a task for milestone 2.0 to implement a continuous integration server that will hopefully make it easier for us to avoid introducing breaking changes. I have a computer set aside that can be used for this. It will take time, but is probably worth it in the long run!

**Comment by daren-thomas** [comment]
The radiation script seems to be working now, thanks @JIMENOFONSECA!

@martin-mosteiro: can you please check for valid data?

**Comment by martin-mosteiro** [comment]
The script runs, but it does still create some warnings:

```
C:\Users\User\Anaconda2\envs\esri104\python.exe C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py
PyTables is not installed. No support for HDF output.
SQLalchemy is not installed. No support for SQL output.
complete calculating sunrise
complete burning buildings into raster
**C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py:446: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  DataCentroids['FactorShade'] = 1
C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py:447: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  DataCentroids['Freeheight'] = DataCentroids.height_ag**
complete calculating boundaries
**C:\Users\User\Anaconda2\envs\esri104\lib\site-packages\pandas\util\decorators.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return func(*args, **kwargs)**
complete calculating observers
complete calculating radiation of day No. 1
```
(...)
```
complete calculating radiation of day No. 365
complete raw radiation files
complete transformation radiation files
**C:\Users\User\Anaconda2\envs\esri104\lib\site-packages\pandas\core\frame.py:2642: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)**
done

Process finished with exit code 0
```

**Comment by martin-mosteiro** [comment]
The results are very different to the ones in the HQ reference case on GitHub, but the total yearly radiation for each building is within 6% of the reference case's.

**Comment by martin-mosteiro** [comment]
The results now are quite different to the radiation data on the server but the total yearly results for each building are within 1%

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro would we close the issue?

**Comment by daren-thomas** [comment]
is there a way to verify the results? if not, we should close the issue. 

The warnings mentioned above are just that: Warnings. And while I would like to remove all warnings from the software, the radiation script might be replaced by the next version, so I don't think we need to fix the warnings.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA: I can't really say if the current results are _better_ or _worse_ than before, just different. One key difference is that for about 10 hours in the year, the sun appears to come up one hour earlier in the new calculation.

But I'd say the results in general look feasible, so I think we can close this.
