### ISSUE TITLE
Rename plots/graphs.py to plots/graphs_demand.py

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#322]
For consistency with the other plots/graphs and also to communicate what is being plotted.

**Comment by daren-thomas** [comment]
@amraladdin: This might be a good task for you to get into the code workflow... just assign it to yourself if you feel up to it.

**Comment by amraladdin** [comment]
@daren-thomas yeah that sounds great! I'll start with it after coming back, does that sound ok?

**Comment by daren-thomas** [comment]
resolved in PR #382
