### ISSUE TITLE
Weird Output of coling demand in HVAc buildings

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#329]
There is a strange behavior in the hourly calculation of the cooling demand in buildings with HVAC. There are some peaks 5 times the average demand that have no relation to changes to outdoor temperature. The problem might be in the HVAC calculation model. It is difficult to jump to conclusions, but there might be something strange about it.

@gabriel-happle would you take a look at this?

![image](https://cloud.githubusercontent.com/assets/8973186/18190857/2c66f42c-70f8-11e6-8529-467618c6fa6f.png)

![image](https://cloud.githubusercontent.com/assets/8973186/18190927/aff1e4b4-70f8-11e6-9296-963d8974d546.png)

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I will try to fix this asap. The problem is related to the latent load. Probably something related to internal humidity gains. I don't know who changed it and what exactly was changed. But I suspect something went wrong during the testing. I encourage everyone to make use of the "full reports" option to look at the detailed hourly results and check whether they make sense.

**Comment by daren-thomas** [comment]
@gabriel-happle : is there a way to formalize "check whether they make sense"? Then we could create a unit test for this...

Also, you can do a binary search on the commit history to find the commit that introduced the bug: Choose a time in the past where you know it still worked and then keep checking out the midpoint between that time and now until it stops working. Then check out the midpoint between then and the previous point... that way you can find the "bad" commit in O(log(n)).

**Comment by gabriel-happle** [comment]
@daren-thomas: apparently the problem is from a different origin. We have planned a discussion for tomorrow to decide what to do.
I will keep the search on the commit history in mind. Thanks for the tip.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, @gabriel-happle: I need to get a version of the CEA fixed as soon as possible for installation for the students. The IT guy who needs to publish the tool to the computerroom is under a lot of pressure now that the semester is starting again and we shouldn't bug him too often with updates.

What is your opinion on when we can rely on the results of the master branch?
