### ISSUE TITLE
Radiation script not working on the masterplan scenario

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#337]
I'm running the radiation script on the masterplan scenario on ArcScene and it seems to be getting stuck after the "calculating observers" part:

> Executing: RadiationTool "C:\cea-reference-case\reference-case (HQ)\masterplan" Zurich 2014
> Start Time: Wed Sep 07 15:31:36 2016
> Running script RadiationTool...
> longitude: 7.43958333333
> latitude: 46.9524055556
> complete calculating sunrise
> complete burning buildings into raster
> complete calculating boundaries
> complete calculating observers
> Completed script RadiationTool...
> Cancelled function
> (RadiationTool) aborted by User.
> Failed at Thu Sep 08 08:18:53 2016 (Elapsed Time: 16 hours 47 minutes 19 seconds)

I ran it again now and it's still not done after 5+ hours

**Comment by martin-mosteiro** [comment]
The script works fine on the command line, so it must be a problem with the implementation on ArcScene

`
C:\Users\User\Anaconda2\envs\esri104\python.exe C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py
PyTables is not installed. No support for HDF output.
SQLalchemy is not installed. No support for SQL output.
complete calculating sunrise
complete burning buildings into raster
C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py:446: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  DataCentroids['FactorShade'] = 1
C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/resources/radiation.py:447: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  DataCentroids['Freeheight'] = DataCentroids.height_ag
complete calculating boundaries
C:\Users\User\Anaconda2\envs\esri104\lib\site-packages\pandas\util\decorators.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return func(*args, **kwargs)
complete calculating observers
complete calculating radiation of day No. 1
[...]
complete calculating radiation of day No. 365
complete raw radiation files
complete transformation radiation files
C:\Users\User\Anaconda2\envs\esri104\lib\site-packages\pandas\core\frame.py:2642: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)
done

Process finished with exit code 0
`

Took less than three hours in total.

**Comment by daren-thomas** [comment]
I just started it on the baseline zug scenario and it is running:

![image](https://cloud.githubusercontent.com/assets/2969564/18466448/0ae7f5f6-799c-11e6-9f94-d0144a448ac7.png)

I will check next with another weather file (zurich) and then move on to the masterplan scenario.

**Comment by daren-thomas** [comment]
Test with baseline zug and zurich weather file works.

**Comment by martin-mosteiro** [comment]
Baseline HQ with Zurich weather worked for me too. The problem was always with the Masterplan case, and only when running on ArcScene... weird.

**Comment by daren-thomas** [comment]
Working on HQ masterplan with Zurich weather file:

![image](https://cloud.githubusercontent.com/assets/2969564/18466683/f4fb3950-799c-11e6-9192-19a77256a051.png)

**Comment by daren-thomas** [comment]
Closed after confirmed it works on @martin-mosteiro 's computer too...
