### ISSUE TITLE
Baseline and Masterplan results are inconsistent

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#338]
The results for the same buildings change widely between the baseline and masterplan scenarios.

**Baseline:**
![screen shot 2016-09-12 at 11 11 30 copy](https://cloud.githubusercontent.com/assets/18548065/18430745/13f4da46-78da-11e6-9133-abce6ccdb967.png)
Note: during the CEA workshop, we noticed that some buildings (E.G. the ETH Hauptgebäude) had extremely high heating demands caused by the fact that the space was defined as 100% office space. This is no longer the case here, even though the building is still defined as 100% offices.

**Masterplan:**
![screen shot 2016-09-12 at 11 12 08 copy](https://cloud.githubusercontent.com/assets/18548065/18430744/13f4a9f4-78da-11e6-9b24-cafa3e367dc9.png)
The demand for various buildings here (including the aforementioned ETH HG) are very different, even though none of their characteristics are changed.

A few caveats:
* I ran the radiation script for both cases with Zurich weather in the command line because of the problems described in #337 
* Other than the buildings that are demolished and the new buildings in the masterplan scenario, every building's characteristics (geometry, occupancy, age, supply systems) are constant for both scenarios **EXCEPT** for:
* Some very small buildings' occupancies were changed in the baseline scenario (from office occupancy to parking) by @JIMENOFONSECA and @amraladdin but not in the masterplan scenario. These changes, however, **do not** explain the differences in the energy demand for buildings such as the ETH HG.
* I did try to adjust these occupancies in the masterplan scenario to keep both cases constant, but this caused problems in the demand calculation (after changing these occupancies, not all building's demand was included in the calculation)

Can someone else please test these scenarios to see if they get the same results? @amraladdin @JIMENOFONSECA @daren-thomas

**Comment by daren-thomas** [comment]
I did some tests. See branch [i338-baseline-and-masterplan-results-are-inconsistent](https://github.com/architecture-building-systems/CEAforArcGIS/tree/i338-baseline-and-masterplan-results-are-inconsistent), file `tests/compare_hq_baseline_masterplan.py`.

It reads in the properties for the two scenarios. Then it prints the building names that are in common. Then it compares the architecture shapefiles for differences on the buildings.

Scroll to the bottom of the output. This is why the results are different! The window to wall ratios and the occupancy is different. I didn't check for other property files (yet) as I believe this already explains the differences in the computation:

```
C:\Users\darthoma\Anaconda2\envs\esri104\python.exe C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/tests/compare_hq_baseline_masterplan.py
reading input files
done
calculating thermal properties
done
creating windows
done
reading input files
done
calculating thermal properties
done
creating windows
done
set(['B302007056a', 'B153701', 'B2372562', 'B302021376', 'B302021377', 'B155128', 'B302049558', 'B140583', 'B140582', 'B140581', 'B2372564', 'B302023103', 'B140586', 'B140585', 'B140584', 'B140589', 'B140588', 'B9011127', 'B302023067', 'B153738', 'B153739', 'B153734', 'B153735', 'B153737', 'B153730', 'B153731', 'B153732', 'B153733', 'B302022730', 'B2372478', 'B2372475', 'B302019954', 'B2372472', 'B302006719', 'B302006718', 'B302006713', 'B302049632', 'B302006717', 'B2368514', 'B302006714', 'B140590', 'B140591', 'B153692', 'B155992', 'B302022768', 'B2368593', 'B302040217', 'B302024465', 'B302024464', 'B2367084', 'B302040213', 'B2368599', 'B153700', 'B302020948', 'B302040194', 'B302040218', 'B2367127', 'B302022767', 'B302040197', 'B140580', 'B302049821', 'B155080', 'B302040295', 'B302040296', 'B155083', 'B302040204', 'B302040195', 'B302007878', 'B302019572', 'B302007876', 'B302007873', 'B153716', 'B153717', 'B153715', 'B302008404', 'B302040203', 'B302040207', 'B302040205', 'B153719', 'B302007086', 'B302007087', 'B302040323', 'B302049837', 'B302007089', 'B302019757', 'B153693', 'B302040285', 'B302024358', 'B2372539', 'B302007714', 'B9001534', 'B302006827', 'B302040222', 'B153767', 'B153766', 'B9011701', 'B302007093', 'B302020945', 'B302040272', 'B155082', 'B302040224', 'B302040175', 'B302040176', 'B302040229', 'B2372547', 'B3169932', 'B302061510', 'B2368544', 'B2372522', 'B155061', 'B302006812', 'B3169241', 'B302040269', 'B302040263', 'B302040303', 'B2368214', 'B2368215', 'B9011691', 'B2372281', 'B302040335', 'B302040308', 'B2372467', 'B302022981', 'B155989', 'B302007063', 'B155194', 'B155192', 'B302007068', 'B2372458', 'B153749', 'B2368562', 'B3169989', 'B153745', 'B153744', 'B153747', 'B153746', 'B153741', 'B153740', 'B153743', 'B153742', 'B302040311', 'B302006694', 'B302006695', 'B302040315', 'B155990', 'B155991', 'B302007075', 'B153727', 'B140556', 'B140557', 'B302006890', 'B302022729', 'B302007073', 'B153726', 'B302007387', 'B140564', 'B302049650', 'B140558', 'B140559', 'B153724', 'B2367183', 'B2372508', 'B153759', 'B153752', 'B153753', 'B153750', 'B302020916', 'B302040249', 'B153751', 'B302006683', 'B3169251', 'B155071', 'B155073', 'B155072', 'B302049800', 'B140561', 'B140560', 'B140562', 'B153718', 'B140567', 'B9083954', 'B140568', 'B153691', 'B153690', 'B153697', 'B153696', 'B153695', 'B153694', 'B3169552', 'B302006716', 'B155067', 'B155065', 'B302007199', 'B302049656', 'B302020840', 'B155068', 'B155069', 'B302023054', 'B153729', 'B153728', 'B302007057', 'B302007056', 'B153725', 'B3169408', 'B153723', 'B153722', 'B153721', 'B302007201', 'B3169526', 'B140578', 'B140576', 'B140577', 'B140571', 'B140573', 'B140570', 'B153748'])
architecture difference: B302022730 @ win_wall (baseline=0.1, masterplan=0.4)
architecture difference: B302022730 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302020948 @ win_wall (baseline=0.1, masterplan=0.15)
architecture difference: B302020948 @ Occ_m2p (baseline=0.0, masterplan=8.0)
architecture difference: B302040218 @ f_cros (baseline=0, masterplan=1)
architecture difference: B302040218 @ win_wall (baseline=0.1, masterplan=0.25)
architecture difference: B302040218 @ Occ_m2p (baseline=0.0, masterplan=5.0)
architecture difference: B302040195 @ win_wall (baseline=0.1, masterplan=0.31)
architecture difference: B302040195 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302019572 @ win_wall (baseline=0.1, masterplan=0.4)
architecture difference: B302019572 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302007087 @ win_wall (baseline=0.1, masterplan=0.31)
architecture difference: B302007087 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302040323 @ win_wall (baseline=0.1, masterplan=0.31)
architecture difference: B302040323 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302019757 @ win_wall (baseline=0.1, masterplan=0.31)
architecture difference: B302019757 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302024358 @ win_wall (baseline=0.1, masterplan=0.4)
architecture difference: B302024358 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302040176 @ win_wall (baseline=0.1, masterplan=0.4)
architecture difference: B302040176 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302006812 @ win_wall (baseline=0.1, masterplan=0.4)
architecture difference: B302006812 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302022981 @ f_cros (baseline=0, masterplan=1)
architecture difference: B302022981 @ win_op (baseline=0.5, masterplan=0.9)
architecture difference: B302022981 @ win_wall (baseline=0.1, masterplan=0.21)
architecture difference: B302022981 @ Occ_m2p (baseline=0.0, masterplan=40.0)
architecture difference: B155192 @ win_wall (baseline=0.1, masterplan=0.31)
architecture difference: B155192 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302007068 @ win_wall (baseline=0.1, masterplan=0.31)
architecture difference: B302007068 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302022729 @ win_wall (baseline=0.1, masterplan=0.4)
architecture difference: B302022729 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302020840 @ win_wall (baseline=0.1, masterplan=0.31)
architecture difference: B302020840 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302007057 @ win_wall (baseline=0.1, masterplan=0.4)
architecture difference: B302007057 @ Occ_m2p (baseline=0.0, masterplan=14.0)
architecture difference: B302007201 @ type_shade (baseline=T1, masterplan=T0)
architecture difference: B302007201 @ win_wall (baseline=0.1, masterplan=0.27)
architecture difference: B302007201 @ Occ_m2p (baseline=0.0, masterplan=10.0)
```

**Comment by daren-thomas** [comment]
I revised the test code and now it shows differences in the RC models for the mail building:
```
--------------------------------------------------------------------------------
Checking building B9011701
testing architecture
testing building systems
testing hvac
testing age
testing rc_model
rc_model difference: B9011701 @ Htr_w (baseline=1395.81552061, masterplan=22328.2186639)
rc_model difference: B9011701 @ Atot (baseline=42948.8806649, masterplan=79039.230912)
rc_model difference: B9011701 @ Htr_is (baseline=148173.638294, masterplan=272685.346646)
rc_model difference: B9011701 @ Awall_all (baseline=2406.57848381, masterplan=38496.9287309)
rc_model difference: B9011701 @ HD (baseline=5041.63768788, masterplan=39688.3739251)
rc_model difference: B9011701 @ Aw (baseline=481.315696762, masterplan=7699.38574618)
rc_model difference: B9011701 @ Htr_em (baseline=11679.51203, masterplan=49806.8082849)
rc_model difference: B9011701 @ Htr_op (baseline=11464.031658, masterplan=46110.7678952)
testing geometry
QHf: baseline=3386.06, masterp0lan=5547.49
QCf: baseline=1190.98, masterp0lan=1365.72
--------------------------------------------------------------------------------
Checking building B3169989
testing architecture
testing building systems
testing hvac
testing age
testing rc_model
rc_model difference: B3169989 @ Htr_w (baseline=4312.55543644, masterplan=223471.399247)
rc_model difference: B3169989 @ Atot (baseline=181691.565146, masterplan=725510.03614)
rc_model difference: B3169989 @ Htr_is (baseline=626835.899755, masterplan=2503009.62468)
rc_model difference: B3169989 @ Awall_all (baseline=10701.1301152, masterplan=554519.601109)
rc_model difference: B3169989 @ HD (baseline=3917.7986825, masterplan=78964.7476796)
rc_model difference: B3169989 @ Aw (baseline=3317.35033572, masterplan=171901.076344)
rc_model difference: B3169989 @ Htr_em (baseline=8750.72227001, masterplan=86179.643008)
rc_model difference: B3169989 @ Htr_op (baseline=8725.26148384, masterplan=83772.2104809)
testing geometry
QHf: baseline=2346.86, masterp0lan=12866.92
QCf: baseline=1189.57, masterp0lan=8108.91
--------------------------------------------------------------------------------
```

**Comment by martin-mosteiro** [comment]
Solved the occupancy issues, ran the data helper for both the baseline and the masterplan scenarios. Checked every single shapefile for both to make sure all the information contained in them is the same (it is). The results are still different for both cases.

**Comment by martin-mosteiro** [comment]
Of course, the rc_model for each case is different (as posted by Daren above). @JIMENOFONSECA does this make any sense to you?

**Comment by JIMENOFONSECA** [comment]
The results should not change too much as the radiation in the building should be similar.

Just to get it right, for one building at the time, did you checked if all inputs are the same after running the properties.py?

Best, Jimeno

On 14 Sep 2016, at 00:59, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


Of course, the rc_model for each case is different (as posted by Daren above). @JIMENOFONSECA<https://github.com/JIMENOFONSECA> does this make any sense to you?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA I did - for every building in the area, for every shapefile. The data in the attributes table is the same for all buildings that are contained in both files. Yet the RC-models for the buildings aren't the same (as shown by @daren-thomas above)

**Comment by daren-thomas** [comment]
check to make sure ['Shape_Leng', 'Freeheight', 'FactorShade'] in the surface properties are the same. Hint: They're not!

**Comment by daren-thomas** [comment]
`Awall_all` is a sum of `'Shape_Leng' * 'Freeheight' * 'FactorShade'` from `surface_properties` for the building

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro just try to debug it and see where the inputs or outputs change. while the demand script run. could the technique of Daren work in this case? apparently the inputs are different according to daren. 

if you are running it via pycharm, maybe it is taking the wrong default inputs? probably weather data?

**Comment by martin-mosteiro** [comment]
After running the radiation script for both scenarios again, the data in the surface_properties.csv file looks fairly similar for both (which makes sense, since there is very little change to these buildings in the masterplan scenario). This probably means, though, that the radiation files in the baseline case on GitHub, i.e., @amraladdin: you should probably either make the students run the radiation script themselves or run the radiation script again and provide them with this version.

However, given #341 the demand for both scenarios cannot be compared at the moment.

**Comment by martin-mosteiro** [comment]
The results from both scenarios are now a lot more reasonable, see the following examples as above:

**Baseline scenario**
![screen shot 2016-09-20 at 11 54 27 copy](https://cloud.githubusercontent.com/assets/18548065/18665871/73d63f0e-7f29-11e6-93f8-dd3b1226ac33.png)

**Masterplan scenario**
![screen shot 2016-09-20 at 11 53 41 copy](https://cloud.githubusercontent.com/assets/18548065/18665885/892b42f0-7f29-11e6-9bcb-3b72d7248b3a.png)

I will now verify the other results, but this issue seems solved. I will update the radiation data on the `reference-case (HQ)` on Github and close this issue.

**Comment by martin-mosteiro** [comment]
Results look good. Closing now.
