### ISSUE TITLE
Document range of valid input values for `calc_cooling_coil` and `calc_heating_coil` and check them

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#343]
As noted in the issue #341, the functions don't work for all inputs. This issue involves:
- documenting the valid ranges of the inputs as part of the function documentation
- checking those ranges (e.g. with `assert`) at the beginning of the function (see https://wiki.python.org/moin/UsingAssertionsEffectively)
  - NOTE: `assert` statements can be switched off when the script is run for production, so we do not need to worry about performance issues
- writing a set of unit tests to test the boundaries of the inputs to the function.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: Your help with this issue would be greatly appreciated.

**Comment by JIMENOFONSECA** [comment]
I see we have identified one in the newton function. the problem is with infinite values when two temperatures are the same. valid ranges are really difficult to know or describe for any function apriori. so i guess if we want to document this. we need to to run every function with different inputs until they brake...

**Comment by daren-thomas** [comment]
Actually, no. Valid ranges can be known apriori. In these functions it may be a bit difficult because it is more a relationship of value ranges, but we know that `TD1` must never be zero, for instance and that is `tc - (k2 + x)` and that is... well, you get the picture...

Another thing is to specify that the two temperatures (which ones exactly? I'm guessing `Tcs_sup_0` and `Tcs_ret_0`) must never be the same... 

BTW: The supply and return temperatures `Ta_sup_cs` and `Ta_ret_cs` are very often the same in the masterplan scenario for a lot of buildings, but as they never appear in a denominator that is not really a problem. I have not tested the other scenarios...

Also, now is the time to decide what to do if such a boundary case does happen. What should the function output? Or should the whole simulation grind to a halt? What are situations where this could happen and how can we make sure they don't happen.

I'm going to guess this task is quite large... say... 5 story points?
