### ISSUE TITLE
Rading latitude/longitude form raster not always working

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#344]
For some case studies with coordinate systems different to the Swiss, the latitude of the raster is read under a different variable to Latitude. As we can not foresee which case studies and coordinates systems we will gonna be dealing with in the future i suggest to let the user decide the latitude and longitud directly in the GUI of the script radiation.py. 

In the next figure you can notice how the variable Latitude_of_origin =90 for the Brussels_1972 coordinate system gives a different value to the real latitude of the raster (that is: standard_parallel_1 = 49.8333.._) this produces an error as the cea toolbox will read the latitude as 90 instead of 49.8333.

This issue could happen in the future. the best is to just let the user put the real latitude and longitud which is what is normally done in the radiation script of arcgis..

![image](https://cloud.githubusercontent.com/assets/8973186/18696072/d9412290-7fe8-11e6-8aa3-9c91ed9b189b.png)

@daren-thomas could you take a look at this in the toolbox?

**Comment by daren-thomas** [comment]
Sure! I'm on it!

**Comment by JIMENOFONSECA** [comment]
just like #251 the best to do is to ask the user always for the latitude and longitude of the place were he is doing the simulation via the GUI.
