### ISSUE TITLE
Radiation data missing from reference-case-zug

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#346]
Steps to reproduce:
1. Download reference-case-zug from repo
2. run data helper
3. run Demand script with weather=Zug
4. ???
5. Boom!!

```
Executing: DemandTool C:\reference-case-zug\baseline Zug
Start Time: Thu Sep 29 16:28:43 2016
Running script DemandTool...
Using python: C:\Python27\ArcGIS10.4\python.exe
Path to demand script: C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py
Adding path to PYTHONPATH: C:\Users\darthoma\Documents\GitHub\CEAforArcGIS
Running demand calculation for scenario C:\reference-case-zug\baseline
Running demand calculation with weather file C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\databases\CH\Weather\Zug.epw
reading input files
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 187, in <module>
    run_as_script(scenario_path=args.scenario, weather_path=args.weather)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 176, in run_as_script
    demand_calculation(locator=locator, weather_path=weather_path, gv=gv)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py", line 92, in demand_calculation
    building_properties = BuildingProperties(locator, gv)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\demand\thermal_loads.py", line 849, in __init__
    solar = pd.read_csv(locator.get_radiation()).set_index('Name')
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\io\parsers.py", line 474, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\io\parsers.py", line 250, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\io\parsers.py", line 566, in __init__
    self._make_engine(self.engine)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\io\parsers.py", line 705, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\io\parsers.py", line 1072, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas\parser.pyx", line 350, in pandas.parser.TextReader.__cinit__ (pandas\parser.c:3160)
  File "pandas\parser.pyx", line 594, in pandas.parser.TextReader._setup_parser_source (pandas\parser.c:5905)
IOError: File C:\reference-case-zug\baseline\outputs\data\solar-radiation\radiation.csv does not exist

Completed script DemandTool...
Succeeded at Thu Sep 29 16:28:49 2016 (Elapsed Time: 6.03 seconds)
```

**Comment by daren-thomas** [comment]
Currently running radiation script with these parameters: weather=Zug, year=2014

**Comment by martin-mosteiro** [comment]
I followed the above steps 1 through 3, but step 4 never happened:

> Executing: DemandTool C:\cea-reference-case\reference-case-zug\baseline Zug
> Start Time: Thu Sep 29 16:42:08 2016
> Running script DemandTool...
> Using python: C:\Python27\ArcGIS10.4\python.exe
> Path to demand script: C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\demand\demand_main.py
> Adding path to PYTHONPATH: C:\Users\User\Documents\GitHub\CEAforArcGIS
> Running demand calculation for scenario C:\cea-reference-case\reference-case-zug\baseline
> Running demand calculation with weather file C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\databases\CH\Weather\Zug.epw
> reading input files
> done
> calculating thermal properties
> done
> creating windows
> done
> Using 2 CPU's
> Building No. 1 completed out of 24
> Building No. 2 completed out of 24
> Building No. 3 completed out of 24
> Building No. 4 completed out of 24
> Building No. 5 completed out of 24
> Building No. 6 completed out of 24
> Building No. 7 completed out of 24
> Building No. 8 completed out of 24
> Building No. 9 completed out of 24
> Building No. 10 completed out of 24
> Building No. 11 completed out of 24
> Building No. 12 completed out of 24
> Building No. 13 completed out of 24
> Building No. 14 completed out of 24
> Building No. 15 completed out of 24
> Building No. 16 completed out of 24
> Building No. 17 completed out of 24
> Building No. 18 completed out of 24
> Building No. 19 completed out of 24
> Building No. 20 completed out of 24
> Building No. 21 completed out of 24
> Building No. 22 completed out of 24
> Building No. 23 completed out of 24
> Building No. 24 completed out of 24
> done - time elapsed: 31.16 seconds
> Completed script DemandTool...
> Succeeded at Thu Sep 29 16:42:46 2016 (Elapsed Time: 38.06 seconds)
>

**Comment by martin-mosteiro** [comment]
Edit: the version of the reference case Zug that is copied on my hard drive works perfectly. The one on GitHub, however, doesn't. i.e., I reproduced the above error. I'm having a look at it now.

**Comment by daren-thomas** [comment]
I tried running the radiation script as mentioned above, but it fails with the following error:

Executing: RadiationTool C:\reference-case-zug\baseline Zug 2014
Start Time: Thu Sep 29 16:32:49 2016
Running script RadiationTool...
longitude: 7.43958333333
latitude: 46.9524055556
complete calculating sunrise
complete burning buildings into raster
complete calculating boundaries
complete calculating observers
complete calculating radiation of day No. 1
[...]
complete calculating radiation of day No. 365
complete raw radiation files
complete transformation radiation files

Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\GUI\toolbox.py", line 589, in execute
    longitude=longitude, year=year, gv=gv, weather_path=weather_path)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\resources\radiation.py", line 153, in solar_radiation_vertical
    CalcIncidentRadiation(Data_radiation_path, locator.get_radiation(), locator.get_surface_properties(), gv)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\resources\radiation.py", line 160, in CalcIncidentRadiation
    radiation[['Name', 'Freeheight', 'FactorShade', 'height_ag', 'Shape_Leng']].to_csv(surface_properties, index=False)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\core\frame.py", line 1184, in to_csv
    formatter.save()
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\core\format.py", line 1417, in save
    encoding=self.encoding)
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\core\common.py", line 2831, in _get_handle
    f = open(path, mode)
IOError: [Errno 2] No such file or directory: u'C:\\reference-case-zug\\baseline\\outputs\\data\\solar-radiation\\properties_surfaces.csv'

Failed to execute (RadiationTool).
Failed at Thu Sep 29 16:43:14 2016 (Elapsed Time: 10 minutes 24 seconds)

**Comment by martin-mosteiro** [comment]
Well, the first issue is easy to clarify. There is no radiation data on the reference case on Github. So the demand script obviously doesn't work. So the first problem in this issue is not a problem at all.

The issue is rather that the Radiation tool doesn't work...

**Comment by daren-thomas** [comment]
This issue is all about the radiation data being missing. That the radiation tool doesn't work is a separate issue (i guess) which might be solved by solving this issue.

@JIMENOFONSECA, do you have any ideas why we are seeing this? And how to fix it?

**Comment by martin-mosteiro** [comment]
The radiation tool is supposed to create the `surface_properties.csv` file that it later cannot find. i.e., the problem is that the `surface_properties.csv` file is not being created.

**Comment by daren-thomas** [comment]
OK! I figured it out! the script is trying to WRITE the `surface_properties.csv` file, but the folder does not exist. I will fix the `InputLocator` to create this folder.

**Comment by daren-thomas** [comment]
OK. So PR #348 can fix this issue automatically. I have now run the radiation data and am created a PR for the reference-case repo: https://github.com/architecture-building-systems/cea-reference-case/pull/7

@JIMENOFONSECA can you check this and merge?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: Th[e PR on the reference case is still open](https://github.com/architecture-building-systems/cea-reference-case/pull/7). Can you please comment on that?
