### ISSUE TITLE
Preserve order of columns when writing out to Excel

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#35]
Go through the codebase and change any `DataFrame.to_excel(... cols={...})` to `DataFrame.to_excel(... cols=[...])`

**Comment by daren-thomas** [comment]
What is the correct order of the columns to use? For which files? This goes hand-in-hand with the documentation effort next week...

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: Do we have a preferred ordering for the columns? Do we still care about this issue?

The function in question would be `demand_main.write_totals_csv`.
Also `thermal_loads.results_to_csv`.

**Comment by JIMENOFONSECA** [comment]
@amraladdin i remember coming up together with this issue, is this still important?, i do not see it important anymore.

**Comment by daren-thomas** [comment]
the fix is really easy, though. someone just has to define the ideal column order.

**Comment by JIMENOFONSECA** [comment]
@amraladdin any comment?

**Comment by amraladdin** [comment]
@JIMENOFONSECA @daren-thomas 
What I had in mind was to have a main fixed number of columns that represent the repeated values in all the tables (e.g. Date, Hour and Building Name). These values should be added in the first few columns in the same order for all the tables.
As for the rest of the columns:
- In the case of the demand calculation, the next row of columns I would put the totals, and after that the breakdown of these values.
- In the case of the occupancy or age of buildings for example... The organization after the basic columns does not matter.
I'll attach an excel file as a sample (Note: The highlighted part in yellow is only for explanation, not to be included).
[Sample of Column Organization.xlsx](https://github.com/architecture-building-systems/CEAforArcGIS/files/422220/Sample.of.Column.Organization.xlsx)

**Comment by daren-thomas** [comment]
@amraladdin, to keep this task as simple as possible: Since we output CSV files, we can only have one header row with column names. These are the same names as the variables used in the calculation. I think keeping it that way has some advantages, at least for people interested in the calculation procedure: Then, the variables in the output correspond directly to those in the calculation code.

If you would like to have a specific column order, could you please look through the output files and define the order for me?

An example:

- Total_demand.csv: `Af_m2,Aroof_m2,Ealf0_kW,Ealf_MWhyr,Eauxf_MWhyr,Ecaf_MWhyr,Edataf_MWhyr,Ef_MWhyr,Eprof_MWhyr,GFA_m2,Name,QCf_MWhyr,QHf_MWhyr,Qcdataf_MWhyr,Qcref_MWhyr,Qcs_MWhyr,Qcsf0_kW,Qcsf_MWhyr,Qhprof_MWhyr,Qhs_MWhyr,Qhsf0_kW,Qhsf_MWhyr,Qww_MWhyr,Qwwf0_kW,Qwwf_MWhyr,Trcs0_C,Trhs0_C,Tscs0_C,Tshs0_C,Tsww0_C,Vw_m3yr,Vww0_m3,Vww_m3yr,mcpcs0_kWC,mcphs0_kWC,mcpww0_kWC,occ_pax`

This is the current (random) order. If you can send me for each of these output files the preferred order, I can make sure they get written that way.

**Comment by amraladdin** [comment]
OK, I discovered a discrepancy between the results in the file and the glossary, so I'll create an issue with that first, once it's solved, we can continue with the organization. Does that sound good for you? @daren-thomas

**Comment by amraladdin** [comment]
So, order of the columns should be as follows:

- Total demand (for the whole study zone):
`Name,Af_m2,Aroof_m2,GFA_m2,occ_pax,QHf_MWhyr,QCf_MWhyr,Ef_MWhyr,Qhsf0_kW,Qhsf_MWhyr,Qhs_MWhyr,Qwwf0_kW,Qwwf_MWhyr,Qww_MWhyr,Qhprof_MWhyr,Qcsf0_kW,Qcsf_MWhyr,Qcs_MWhyr,Qcref_MWhyr,Qcdataf_MWhyr,Ealf0_kW,Ealf_MWhyr,Eauxf_MWhyr,Ecaf_MWhyr,Edataf_MWhyr,Eprof_MWhyr,Tshs0_C,Trhs0_C,Tscs0_C,Trcs0_C,Tsww0_C,Vw_m3yr,Vww0_m3,Vww_m3yr,mcphs0_kWC,mcpww0_kWC,mcpcs0_kWC`

- Demand (per building):
`DATE,Name,occ_pax,QHf_kWh,QCf_kWh,Ef_kWh,Qhsf_kWh,Qhs_kWh,Qhprof_kWh,Qwwf_kWh,Qww_kWh,Qww_tankloss_kWh,Qcsf_kWh,Qcs_kWh,Qcref_kWh,Qcdataf_kWh,Ealf_kWh,Eauxf_kWh,Ecaf_kWh,Edataf_kWh,Epro_kWh,Tshs_C,Trhs_C,Tscs_C,Trcs_C,Tsww_C,Trww_C,Tww_tank_C,Tsref_C,Trref_C,Tsdata_C,Trdata_C,Vw_m3,mcphs_kWC,mcpww_kWC,mcpcs_kWC,mcpref_kWC,mcpdata_kWC`

Regarding the organization of the Total LCA_Embodied, Operational and Mobility, @martin-mosteiro already fixed them.

**Comment by daren-thomas** [comment]
Pull request sent #325.
