### ISSUE TITLE
Integration of Generative Design in CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#354]
potential to use CityGML + rhino.

**Comment by JIMENOFONSECA** [comment]
@shizhongming could you elaborate about the status in here?, thanks

**Comment by shizhongming** [comment]
@JIMENOFONSECA The CityGML LOD2.5 is finalizing. I am working on wrapping my things up to be readable by CEA. And Darren is working on the connection of CEA and Grasshopper as we discussed during his visit here last week.

**Comment by JIMENOFONSECA** [comment]
it is duplicate of #665
