### ISSUE TITLE
Integrate PV sensor selection into daysim radiation script

### ISSUE THREAD

**Issue by paulneitzel** [architecture-building-systems/CEAforArcGIS#356]
up to now files with all sensor points have to be saved and loaded. a pre selection of only the relevant sensors for pv calculation would save simulation time

**Comment by JIMENOFONSECA** [comment]
waiting for #424 to be merged. It depends on #9 to be developed.

**Comment by JIMENOFONSECA** [comment]
Waiting for #9 to be delivered. @chenkianwee is working in it now. moving to the next milestone

**Comment by shanshanhsieh** [comment]
As the results of the radiation calculation are also used for demand calculation, it is not necessary to implement the pre-selection of sensors for PV installation in the radiation script. The process of sensor selection will be kept in the technology script of PV generation. This issue can be closed.
