### ISSUE TITLE
Replace `calc_t_em_ls` with a table-based method

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#358]
`calc_t_em_ls`  is just one of many methods that might be improved by using a more data-driven approach. This is a possible rewrite of the function, *except* edge cases behave slightly different.

This issue is about verifying that the edge cases in the original implementation are, in fact, correct and if not, maybe we can adopt the following version:

```
def calc_t_em_ls(heating_system, cooling_system, control_system):
    control_delta_heating = {'T1': 2.5, 'T2': 1.2, 'T3': 0.9, 'T4': 1.8}
    control_delta_cooling = {'T1': -2.5, 'T2': -1.2, 'T3': -0.9, 'T4': -1.8}
    temperature_correction_heating = {'T1': 0.15, 'T2': -0.1, 'T3': -1.1, 'T4': -0.9}
    temperature_correction_cooling = {'T1': 0.5, 'T2': 0.7, 'T3': 0.5}

    try:
        result_heating = control_delta_heating[control_system] + temperature_correction_heating[heating_system]
    except KeyError:
        result_heating = 0.0

    try:
        result_cooling = control_delta_cooling[control_system] + temperature_correction_cooling[cooling_system]
    except KeyError:
        result_cooling = 0.0

    return result_heating, result_cooling
```

**Comment by shanshanhsieh** [comment]
hey @daren-thomas , could you please give me an example on the "edge cases"?

**Comment by daren-thomas** [comment]
hey @shanshanhsieh, OK, so I wrote a commentary on this bug in my sandbox folder https://github.com/architecture-building-systems/CEAforArcGIS/blob/sandbox/sandbox/dthomas/i358.py

Edge cases could mean a lot in testing. In this example I just tested all combinations and included versions where a bad input ("XYZ") and no input (`None`) get passed in and we get some differences:

```
difference found for inputs: T1 T1 XYZ (0.15, 0.5) (0.0, 0.0)
difference found for inputs: T1 T1 None (0.15, 0.5) (0.0, 0.0)
difference found for inputs: T1 T2 XYZ (0.15, 0.7) (0.0, 0.0)
difference found for inputs: T1 T2 None (0.15, 0.7) (0.0, 0.0)
difference found for inputs: T1 T3 XYZ (0.15, 0.5) (0.0, 0.0)
difference found for inputs: T1 T3 None (0.15, 0.5) (0.0, 0.0)
difference found for inputs: T1 T4 XYZ (0.15, 0) (0.0, 0.0)
difference found for inputs: T1 T4 None (0.15, 0) (0.0, 0.0)
difference found for inputs: T1 XYZ XYZ (0.15, 0) (0.0, 0.0)
difference found for inputs: T1 XYZ None (0.15, 0) (0.0, 0.0)
difference found for inputs: T1 None XYZ (0.15, 0) (0.0, 0.0)
difference found for inputs: T1 None None (0.15, 0) (0.0, 0.0)
difference found for inputs: T2 T1 XYZ (-0.1, 0.5) (0.0, 0.0)
difference found for inputs: T2 T1 None (-0.1, 0.5) (0.0, 0.0)
difference found for inputs: T2 T2 XYZ (-0.1, 0.7) (0.0, 0.0)
difference found for inputs: T2 T2 None (-0.1, 0.7) (0.0, 0.0)
difference found for inputs: T2 T3 XYZ (-0.1, 0.5) (0.0, 0.0)
difference found for inputs: T2 T3 None (-0.1, 0.5) (0.0, 0.0)
difference found for inputs: T2 T4 XYZ (-0.1, 0) (0.0, 0.0)
difference found for inputs: T2 T4 None (-0.1, 0) (0.0, 0.0)
difference found for inputs: T2 XYZ XYZ (-0.1, 0) (0.0, 0.0)
difference found for inputs: T2 XYZ None (-0.1, 0) (0.0, 0.0)
difference found for inputs: T2 None XYZ (-0.1, 0) (0.0, 0.0)
difference found for inputs: T2 None None (-0.1, 0) (0.0, 0.0)
difference found for inputs: T3 T1 XYZ (-1.1, 0.5) (0.0, 0.0)
difference found for inputs: T3 T1 None (-1.1, 0.5) (0.0, 0.0)
difference found for inputs: T3 T2 XYZ (-1.1, 0.7) (0.0, 0.0)
difference found for inputs: T3 T2 None (-1.1, 0.7) (0.0, 0.0)
difference found for inputs: T3 T3 XYZ (-1.1, 0.5) (0.0, 0.0)
difference found for inputs: T3 T3 None (-1.1, 0.5) (0.0, 0.0)
difference found for inputs: T3 T4 XYZ (-1.1, 0) (0.0, 0.0)
difference found for inputs: T3 T4 None (-1.1, 0) (0.0, 0.0)
difference found for inputs: T3 XYZ XYZ (-1.1, 0) (0.0, 0.0)
difference found for inputs: T3 XYZ None (-1.1, 0) (0.0, 0.0)
difference found for inputs: T3 None XYZ (-1.1, 0) (0.0, 0.0)
difference found for inputs: T3 None None (-1.1, 0) (0.0, 0.0)
difference found for inputs: T4 T1 XYZ (-0.9, 0.5) (0.0, 0.0)
difference found for inputs: T4 T1 None (-0.9, 0.5) (0.0, 0.0)
difference found for inputs: T4 T2 XYZ (-0.9, 0.7) (0.0, 0.0)
difference found for inputs: T4 T2 None (-0.9, 0.7) (0.0, 0.0)
difference found for inputs: T4 T3 XYZ (-0.9, 0.5) (0.0, 0.0)
difference found for inputs: T4 T3 None (-0.9, 0.5) (0.0, 0.0)
difference found for inputs: T4 T4 XYZ (-0.9, 0) (0.0, 0.0)
difference found for inputs: T4 T4 None (-0.9, 0) (0.0, 0.0)
difference found for inputs: T4 XYZ XYZ (-0.9, 0) (0.0, 0.0)
difference found for inputs: T4 XYZ None (-0.9, 0) (0.0, 0.0)
difference found for inputs: T4 None XYZ (-0.9, 0) (0.0, 0.0)
difference found for inputs: T4 None None (-0.9, 0) (0.0, 0.0)
difference found for inputs: XYZ T1 XYZ (0, 0.5) (0.0, 0.0)
difference found for inputs: XYZ T1 None (0, 0.5) (0.0, 0.0)
difference found for inputs: XYZ T2 XYZ (0, 0.7) (0.0, 0.0)
difference found for inputs: XYZ T2 None (0, 0.7) (0.0, 0.0)
difference found for inputs: XYZ T3 XYZ (0, 0.5) (0.0, 0.0)
difference found for inputs: XYZ T3 None (0, 0.5) (0.0, 0.0)
difference found for inputs: None T1 XYZ (0, 0.5) (0.0, 0.0)
difference found for inputs: None T1 None (0, 0.5) (0.0, 0.0)
difference found for inputs: None T2 XYZ (0, 0.7) (0.0, 0.0)
difference found for inputs: None T2 None (0, 0.7) (0.0, 0.0)
difference found for inputs: None T3 XYZ (0, 0.5) (0.0, 0.0)
difference found for inputs: None T3 None (0, 0.5) (0.0, 0.0)
```
The format of the output is: inputs, (outputs of original function), (outputs of refactored function) and the program only reports results that differ between the original and refactored function.

Going through the results, it looks like they only differ when bad input is given ("XYZ" or `None`), so, for "good" input, we can say they compute the same results. Still, edge cases are not really specified here: What *should* the output be, if a system is specified that the program does not yet know about? I think an error could be raised instead...

**Comment by daren-thomas** [comment]
So, once you and I agree on what *should* happen when bad data gets put in to the function, we can adopt the newer version of the function...

**Comment by daren-thomas** [comment]
I have also done a speed test to see if there is a difference, but there is no noticeable difference in speed so I suggest we go with the version that is easier to understand and maintain. What do you think, @shanshanhsieh?

**Comment by daren-thomas** [comment]
Huh... by moving the dictionaries to the module (so they only get created at module import time) the newer version is twice as fast...

**Comment by daren-thomas** [comment]
See PR #371

**Comment by shanshanhsieh** [comment]
Hi @daren-thomas , thank you for the explanation!
to my opinion, at the edge cases, when the control systems and emission systems are not specified in the database, an error should be raised. Or at least zero temperature adjustment should be returned (result_heating, result_cooling). Therefore, we should switch to your table-based method.

**Comment by daren-thomas** [comment]
OK. It turns out that the reference cases include 'T0' as cooling system. What is the setpoint correction for that supposed to be? I'm setting it to `0.0`, @shanshanhsieh can you please check to see if that is correct?

**Comment by daren-thomas** [comment]
@shanshanhsieh: Can you check the branch of the PR #371 for an example of unit testing the `calc_t_em_ls` function? What are examples of correct behavior (input / output)? I think it would be good to test some. Also, please check that the `T0` definitions are correct. I'm not sure about them.

**Comment by shanshanhsieh** [comment]
You are right @daren-thomas , there is a problem when no heating or cooling system is assigned (`T0`).
`T0` means there's no heating/cooling systems installed, therefore, also no control systems for heating/cooling. 
In short, when the input system is `T0`, the output set point correction should be `0.0`.
So if there is no cooling systems, the `calc_t_em_ls` function input: (T1, T0, T1) (type_hs, type_cs, type_ctrl), return should be (2.65, 0.0), the control system is only specified for the heating system.
In another case with no heating systems: input: (T0, T3, T1) return: (0.0, -2.0), the control system is only specified for the heating system.

**Comment by daren-thomas** [comment]
I have updated the code to reflect this for heating systems and cooling systems in 522e066.  I have also added your last comment to the documentation of the function. Also, check out the unit tests that make sure this is correct. I think we should do a lot more of these at the module/function level as they "document" the assumptions built into the code.

Can you come up with other tests for correct behavior? What happens if the control system is `T0`?

Can we come up with a better name than `calc_t_em_ls`? What does that even mean? Could we call it `correction_factor_for_heating_and_cooling_setpoints`? or `correction_factor_for_setpoints`? Did you derive the name from a section in the standard? (where? paragraph?) - that would be an indication to leave the name as is...

**Comment by shanshanhsieh** [comment]
I adopted the function name from before, a better name could be `temperature_setpoint_correction_for_space_emission_systems` or just `setpoint_correction_for_space_emission_systems`.
`T0` is not a valid input for control system, if the control system is not specified, an error should be raised, and I think that's what the current function is doing. I modified it in [099bee3](https://github.com/architecture-building-systems/CEAforArcGIS/commit/099bee327d2db01edfc86f57aad1640e218d98d8).

**Comment by daren-thomas** [comment]
thank you! I will update the function name, I like your suggestions!

BTW: I took the `T0` for control systems from the documentation as mentioned in the docstring of the function. Would you mind checking the relevant page and updating it in the documentation please?

**Comment by shanshanhsieh** [comment]
Will do!
