### ISSUE TITLE
I don't understand the share parameter in calc_Edataf

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#362]
The function `calc_Edataf` has a `share` parameter that get's passed the occupancy share for usage type "SERVERROOM". The thing is, we already created the schedule as that same fraction of the electrical loads, so I think we're doing this twice:

`calc_Edataf = schedule * Ed_Wm2 * Aef * share`

with 
- `schedule = schedules[list_uses[num][1] *  building_uses[list_uses[num]]`,
- `Ed_Wm2 = bpr.internal_loads['Ed_Wm2']`
- `Aef = bpr.rc_model['Aef']`
- `share = bpr.occupancy['SERVERROOM']`

So, essentially, the `schedule` is already multiplied by the `bpr.occupancy['SERVERROOM']` and we multiply again...

I think this might be a bug. @JIMENOFONSECA can you please check that this is really what should be happening? If not, then the same probably goes for the COOLROOM and INDUSTRY uses...

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, I would like you to assign this task to yourself or talk to me about it.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas yes you are right. check PR #421

**Comment by daren-thomas** [comment]
fixed with PR #421
