### ISSUE TITLE
Create a "renovation archetype" script

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#369]
Data on building renovation is basically impossible to obtain (feedback from the city of Zurich) unless you ask each building owner for the information. The next best solution is to assess the building stock visually, which might be impractical and would still be a guess.

One solution could be to create a model based on the Gebäudeparkmodell which predicts the probability of a building component being renovated on a given year based on Swiss statistics. For a given building year and occupancy type, the model would give the cumulative probability that each component has been renovated after X years.

I believe I have discussed this with @JIMENOFONSECA and @amraladdin before as a possible solution to the uncertainty in the renovation years in the Hochschulquartier. The results could then be compared to the estimates provided by the MIBS students.

**Comment by JIMENOFONSECA** [comment]
Interesting, I am working on the Calibrator issue and this might be inline with some statistical work to predict demand. I am looking now at bayesian statistics to calibrate building models. I imagine using a similar approach to the renovation paradigm. It sounds to me like a nice topic for a publication. Basically we will use bayesian statistics to calibrate the building model based on the year of renovation. We will need measured data of all buildings and the probability density functions of all the renovation periods.


On 15 Oct 2016, at 7:27 pm, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


Data on building renovation is basically impossible to obtain (feedback from the city of Zurich) unless you ask each building owner for the information. The next best solution is to assess the building stock visually, which might be impractical and would still be a guess.

One solution could be to create a model based on the Gebäudeparkmodell which predicts the probability of a building component being renovated on a given year based on Swiss statistics. For a given building year and occupancy type, the model would give the cumulative probability that each component has been renovated after X years.

I believe I have discussed this with @JIMENOFONSECA<https://github.com/JIMENOFONSECA> and @amraladdin<https://github.com/amraladdin> before as a possible solution to the uncertainty in the renovation years in the Hochschulquartier. The results could then be compared to the estimates provided by the MIBS students.
