### ISSUE TITLE
Extract PropertiesTool (etc.) to a separate file

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#37]
Extract the `PropertiesTool` class from the `properties.py` script (and the same for the other scripts) to a separate file (`properties_tool.py`?)

**Comment by daren-thomas** [comment]
working on this in the i37 branch...

**Comment by daren-thomas** [comment]
oh dear... the tools are broken since #99!

**Comment by JIMENOFONSECA** [comment]
This issue was addressed in issue #102  after properties tool was modified in issue #99

**Comment by daren-thomas** [comment]
Right. I found the issue and assigned it to myself.

**Philosophy discussion:**

I think this should have been part of #99, as otherwise #99 breaks the
tool, right? so each time an issue is resolved, the whole project must be
left in a state where it still works.

**Comment by daren-thomas** [comment]
ok. extracted to `toolbox.py`.
