### ISSUE TITLE
Heating coil breaks due to data generated by HVAC model

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#373]
The heating coil does not converge due to a case where both temperatures of air before and after the coil are identical even in periods of heating demand. The temperatures are about 39 degrees which seems unrealistic if there is a heating load. This is stopping work on the issue i351.

To discover this, I run 300 simulations of a set of 9 buildings in zug with different HVAC systems. The problem happens in buildings with AC both for heating and cooling under certain configurations:

{u'Th_mass': 'T3', u'Hs': 0.5, u'U_wall': 3.7000000000000002, u'U_roof': 0.39333333333333331, u'U_win': 4.2999999999999998, u'U_base': 0.14999999999999999, u'Es': 0.92000000000000004}

I uploaded the reference-case in the folder reference-case-zug/sensitivity_demand_model in the folder of references cases in github.

@gabriel-happle  could you take a look at this? as these configurations were done automatically we will have to change the value of each variable manually in arcgis to check the cases.

**Comment by gabriel-happle** [comment]
On it

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I can not see the mentioned reference case. Can you send me the link please?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I can not reproduce this error with the given inputs! The demand calculation in the master branch runs through. However, I made some observations:
- The inputs for the U-values are impossible in practice, as ArcGIS does not allow for more then 15 digits after the comma in attribute tables
- The radiation file is not consistent with the weather file (e.g. different hours of sun shine)

I suspect that there might be other inputs that cause this error. Maybe you can give me an exact copy of the input files you are using.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle great i will come back to you with some other cases next week.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle it is working, i think the inputs with many digits was the problem. i was able to run it without concern now
