### ISSUE TITLE
Need for different types of outputs of the demand model

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#377]
In the sensitivity analysis, as well as in testing, not all the outputs of the demand model will be needed. Sometimes the file total data is not necessary, sometimes hourly data is not necessary, but monthly and vice versa etc..

I think we could create some standard output configurations. This will be especially effective when generating big chunks of data. like results of 200k simulations..

It would be good to create a class of outputs.

This issue will be solved together with #351

**Comment by daren-thomas** [comment]
One way to do this is to refactor the methods for writing out the result files to a class, say `BuildingResultWriter` and `TotalsResultWriter`. Have the `demand_main` script use a default value for these - one that writes out the results just like the current version does. Then, you can create alternative subclasses of these writers: a `MonthlyBuildingResultsWriter` would just write out the monthly results, a `DisableTotalsResultWriter` would just discard any results, i.e. do nothing (`pass`).

This is one of the places where following OO principles makes sense. Of course, this could also more elegantly be implemented with functions - `write_building_results` etc. and store those in a variable. It doesn't really matter which way we choose.

**Comment by daren-thomas** [comment]
Note, if we are doing the calibration calculations on Euler, we don't really need to do this: We can implement a post-processing step that converts the hourly results into monthly results.

When running on Euler, you have two types of storage: A per-user storage (your `$HOME` folder) that is persisted between sessions and a per-node storage (a "scratch" folder) that is deleted after a job has been completed.

I envision running each demand calculation in a separate job, that starts with copying a template reference-case from the home folder to the scratch folder, applying the changes, running the demand and then post-processing and collecting the results. The last step would copy the output back to the home folder. Once all the demand simulations have been done, a final step would run the sensitivity analysis and produce the final output.

**Comment by JIMENOFONSECA** [comment]
I created a solution to this with some flags in global variables.
It works nicely in my pc. after merged maybe we can thing on transforming the remake of results_to_cv function of the thermal loads.py to a class as you say? I agree with you that could be the way to go. .


On 21 Oct 2016, at 5:48 pm, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


One way to do this is to refactor the methods for writing out the result files to a class, say BuildingResultWriter and TotalsResultWriter. Have the demand_main script use a default value for these - one that writes out the results just like the current version does. Then, you can create alternative subclasses of these writers: a MonthlyBuildingResultsWriter would just write out the monthly results, a DisableTotalsResultWriter would just discard any results, i.e. do nothing (pass).

This is one of the places where following OO principles makes sense. Of course, this could also more elegantly be implemented with functions - write_building_results etc. and store those in a variable. It doesn't really matter which way we choose.
