### ISSUE TITLE
Update the documentation for `type_ctrl`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#378]
In the [current documentation](https://architecture-building-systems.gitbooks.io/cea-toolbox-for-arcgis-manual/content/building_properties.html#mechanical-systems) the list of values for `type_ctrl` does not reflect the values as described in the `calc_t_em_ls` (or, as of #371 / #358) `setpoint_correction_for_space_emission_systems`). Especially `T0` should not be described as a valid value. But we also need to check the remaining descriptions for `T1` through `T3`.

**Comment by daren-thomas** [comment]
@shanshanhsieh can you do this please?

**Comment by shanshanhsieh** [comment]
The documentation of [Building Properties in the Archetype section ](https://architecture-building-systems.gitbooks.io/cea-toolbox-for-arcgis-manual/content/building_properties.html) is updated according to the current "Archetypes_properties.xlsx" spreadsheets now.
Except there are three properties that is described in the documentation but not in the Architecture spreadsheets.
They are : `type_roof/type_wall/type_win`. Are these properties currently in use, @JIMENOFONSECA ?

**Comment by shanshanhsieh** [comment]
The  `type_roof/type_wall/type_win` are implemented for issue #375 . 
The [building properties section documentation](https://architecture-building-systems.gitbooks.io/cea-toolbox-for-arcgis-manual/content/building_properties.html#mechanical-systems) is up to date.

**Comment by JIMENOFONSECA** [comment]
yes, they will be used in once #381 be merged.


On 21 Oct 2016, at 5:49 pm, shanshanhsieh <notifications@github.com<mailto:notifications@github.com>> wrote:


The documentation of Building Properties in the Archetype section <https://architecture-building-systems.gitbooks.io/cea-toolbox-for-arcgis-manual/content/building_properties.html> is updated according to the current "Archetypes_properties.xlsx" spreadsheets now.
Except there are three properties that is described in the documentation but not in the Architecture spreadsheets.
They are : type_roof/type_wall/type_win. Are these properties currently in use, @JIMENOFONSECA<https://github.com/JIMENOFONSECA> ?
