### ISSUE TITLE
Update full report function

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#379]
A lot of variable can currently not be reported any more in the `utilities.reporting` function, as names of variables have changed.
Names of variables to report are in `globalvar`

`cannot report following variables: q_int, Eal_nove, Edata, vww, vw, Qcdata, Qcrefri, Hve, Htr_is, Htr_ms, Htr_w, Htr_em, Htr_1, Htr_2, Htr_3, QHC_sen, t5, tHset_corr, tCset_corr, Waterconsumption`

`cannot report following variables: Name, Af, Aef, sys_e_heating, sys_e_cooling, Am, Atot, Awall_all, Cm, Ll, Lw, Retrofit, Sh_typ, Year, footprint, nf_ag, nfp, Lcww_dis, Lsww_dis, Lv, Lvww_dis, Tcs_re_0, Tcs_sup_0, Ths_re_0, Ths_sup_0, Tww_re_0, Tww_sup_0, Y, fforma`

**Comment by daren-thomas** [comment]
good point! A lot of these might have been moved to the `tsd` variable...
