### ISSUE TITLE
Create a "readthedocs" style API documentation for the CEA

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#386]
Using techniques as described in [this blog post](https://medium.com/@tryexceptpass/python-introspection-with-the-inspect-module-2c85d5aa5a48#.9sl0rz2m4) and [MkDocs](http://www.mkdocs.org/) or something similar we could create an up-to-date API documentation to the CEA. Some additional ideas:
- host this in GitHub pages / readthedocs.io
- automatically build when merging to master
- will inspire our researchers to maintain source documentation while coding

**Comment by JIMENOFONSECA** [comment]
totally down for it. Would this replace the git book? i hope so. it is difficult to get things well organized there (the menu bar does not work properly).

**Comment by JIMENOFONSECA** [comment]
are we talking about somthing like this:

http://pymc-devs.github.io/pymc3/notebooks/getting_started.html

**Comment by daren-thomas** [comment]
actually, I was thinking more of an API reference, that is, a compilation of module, class and function docstrings (the stuff with the `"""all my documenation in tripple-quotes"""`).

The git book documentation could of course also be moved to another system if you like: we have saved all the files in markdown in a github repository in our organization, so we can easily move them to another system.

Please elaborate on how the menu bar does not work properly: This is the first I've heard of this. Maybe a simple fix can get us back on track?

**Comment by JIMENOFONSECA** [comment]
maybe we can. the menu on the left is a bit big and it is difficult to minimize or expand a chapter and sub-chapter. 

But if it is for the API reference and the Gitbook i will go for doing one sole thing in something like readocs.io. I have seen many other libraries including using manual and API in the same site. I think having the code and the manual is quite useful. So one can refer to the other if necessary.

**Comment by daren-thomas** [comment]
I have set this task to the M3 milestone. I suggest we continue documenting as before for this milestone and then I will figure out how to migrate it to the new version. That way, we don't have to stop our efforts. I have clicked around on the gitbook page a bit and have experienced a weird behavior that I can't really reproduce with level 3 subtitles appearing and disappearing in the TOC without me understanding why. Is that what you mean?

To me this means:
- we have cosmetic problems with the presentation of the documentation that need to be resolved - possibly by migrating to a different platform
- we have structural problems with the documentation in that we want to merge api, user and dev documentation into one site
- we should abandon PDF etc. as output formats because the web has so happened and I'm an idiot for still believing it cutting trees down to print out my documentation on. Sorry for that, I'm a dinosaur and need to evolve...
- we should think about whether keeping user/dev documentation and code separate is still a good idea: if we move to another system, we might just ad a /docs folder to the source for the user/dev documenation and create a `pydoit` script for building the documentation from that. Look into how Sphynx and MkDocs can help us with that etc. Milestone M3 seems perfect for me to do this.

**Comment by JIMENOFONSECA** [comment]
good for me, let's move it to M3
________________________________

**Comment by daren-thomas** [comment]
Woohoo! First, incomplete, buggy version can be marveled here: http://city-energy-analyst.readthedocs.io/en/386-create-readthedocs-style-api-documentation/index.html

We still have a lot of build fails, because not all imports work yet. How to implement these things:

- `arcpy` (no clue, but hey, I'll give it a try)
- `deep` (should be easy, just add it to the requirements)
- `SALib` (see `deep`)
- `arcpyscripting` (what is broccoli anyway?)
- `ephem` (I'm on it!)
- `numba.pycc` (this could be made optional...)
