### ISSUE TITLE
DHC network for the cea

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#393]
- Develop a hydraulic thermal model of DHC networks.

- Develop a new method to optimize the network with 2-objective optimisation (investment and operation costs). Optimize layout and size of the network.

- implement either a minimum spanning tree or ring topology. the last could become the dominating network layout.

- Allow adjusting mass flow rate in networks for heating and cooling instead of temperature adjustment to compensate high network losses during times with low demand (e.g. only domestic hot water supply in summer).

**Comment by JIMENOFONSECA** [comment]
I consider inputs shoudl be:
1. one excel file with the costs of different types of pipes and the properties of the materials. his should be stored in the database of the cea. Check publication in energy and buildings for these parameters as a starting point.
2. a grid of potential paths where buildings can be connected. This include streets, pedestrian pathways, additional that the designer considers could be interesting.

**Comment by JIMENOFONSECA** [comment]
For the thermal losses you might want to check:
summarize_network_main.py/calc_piping_thermal_loss. But i suggest to do some research about this

For the hydraulic model:
One option is to check florian's documentation and try to do it.
Another one is to connect to EPANET. Energyplus is to buildings like epanet is to hydraulic networks.
Another option is to extract and code the hydraulic model from EPANET documentation. 

For the Network:

**Comment by shanshanhsieh** [comment]
4 small issues are decomposed from this issue, and will be finished for Milestone 2.
The 4 issues are: #407, #408, #409, #412 
The rest will be tackled in Milestone 3.

**Comment by martin-mosteiro** [comment]
This issue has been replaced by #407, #408, #409 and #412, so it should be closed.
