### ISSUE TITLE
2000 Watt society target values

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#397]
The target values in the 2000 Watt society graphs are taken from SIA 2040 and the Leitfaden Arealentwicklung für die 2000-Watt-Gesellschaft. This means that not every building occupancy type from the CEA is included (e.g., Industry and Hospitals are not included). In the current CEA calculation, the target for these uses is set to zero!

- **Short term solution for the MIBS:** use the values for industry from InduCity and set the values for all other occupancy types to the target for "other services" from InduCity.

- **Long term solution:** need to calculate the targets for each use type following the methodology from Lenzlinger (2010) “SIA Effizienzpfad: Bestimmung der Ziel- und Richtwerte mit dem Top-Down Approach,” as done for InduCity. As described in [this report from Jimeno](https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&ved=0ahUKEwirkN_Xrp7QAhUKwBQKHW0XAO8QFgg1MAM&url=http%3A%2F%2Fwww.futurecities.ethz.ch%2Fwp-content%2Fplugins%2Fzotpress%2Flib%2Frequest%2Frequest.dl.php%3Fapi_user_id%3D151611%26key%3DUHCZNT9S%26content_type%3Dapplication%2Fpdf&usg=AFQjCNHHCPVv0HVW8afrI4ybhvF_wUd05A&sig2=qahV3AnpecftVfo20DEdsw):
> The estimation of goals is based on the Swiss prospects of energy reference area by Haag, 2004 [7], the grey emissions of the Swiss building stock by Lenzlinger, 2009 [8] and the Swiss energy consumption statistics of Switzerland 2000-2011 by Kemmler et al., 2012 [9]. The result is a set of goals for reduction of CO2 emissions and primary energy consumption of the average Swiss building stock. These values are compared to those of the buildings in the area of study, obtaining goals for each category of use in the area on the time line of the suggested transformation (Table 1).

**Comment by martin-mosteiro** [comment]
@amraladdin This is the issue I was referencing the other day when we talked about setting the 2000W targets. For the MIBS course we already used the values we assigned ourselves with Stefan. Longer term we should really calculate the targets as done in the literature.

**Comment by amraladdin** [comment]
@martin-mosteiro 
Yeah, true. So now we have the new values, however, we also made a number of assumptions and we need to verify them. I don't think we can do this before this milestone. We will need to postpone the deadline of this issue. What do you think?

**Comment by martin-mosteiro** [comment]
This issue was resolved along with #464 . The missing values were completed based on the standard calculation procedure when possible and based on simple assumptions otherwise. These assumptions were double checked and considered reasonable by @amraladdin . The missing values are completed as follows:

**(1) 'INDUSTRY':** operation and embodied energy and emissions calculated based on the bottom-up approach from SIA 2040; due to lack of data on mobility, the same values as for 'OFFICE' were assumed, as the demand consists mainly of workers' daily commutes
**(2) 'HOSPITAL':** operation and embodied energy and emissions estimated based on the bottom-up approach from SIA 2040 coupled with energy demand statistics per sector from the Bundesamt für Energie; due to lack of data on mobility, the same values as for 'HOTEL' were assumed (some people going to work, mainly people going for non-daily travel purposes)
**(3,4) 'GYM', 'SWIMMING':** operational energy calculated from SIA 2024, then the corresponding primary energy and CO2 emissions were estimated as an average of the values for all other uses; due to lack of information, embodied energy and mobility were assumed to be the same as for 'RETAIL' (mainly people attended leisure activities); targets were then set based on these values through the same approach as SIA 2040
**(5) 'SERVERROOM':** calculated the operational energy the same way as (3,4); due to lack of information embodied energy was assumed to be the same as 'OFFICE' (highly technical office space); mobility was assumed to be negligible; the targets were then set the same way as (3,4) 
**(6) 'COOLROOM':** calculated the operational energy the same way as (3,4); due to lack of information embodied energy was assumed to be the same as 'HOSPITAL' (building with lots of technical installations); mobility was assumed to be negligible; the targets were then set the same way as (3,4)

While these assumptions are fairly rough (especially for 3 - 6), since these occupancy types are relatively rare in urban areas the impact of the uncertainty created is expected to be rather small.

The issue will be closed as soon as Pull request #464 is accepted.
