### ISSUE TITLE
Weatherfile should be part of scenario

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#398]
After some consideration I have come to the conclusion that the weather file should be part of the scenario  or at least the path to the weather file should be part of the scenario configuration file (to be developed).

We should also have a script / method to set the weather file for a scenario, like the data helper. In fact, the data helper could be used for that purpose, but a separate step would be preferable.

That way, all the information required to run a scenario (and reproduce it's output!) would be contained inside the scenario folder. Also, it makes sense to define the scenario's weather as part of the scenario definition and not have it as an ephemeral property.

In the same way, the scenario should also define the location, (CH vs. SIN for now), that is, which database to use for archetypes etc.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas i will go for being part of the config file. the user can use a weather file per scenario or use those existing in the database

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this is somehow priority 2 right?

**Comment by daren-thomas** [comment]
duplicate of #646
