### ISSUE TITLE
newest version of wheels for geopandas installation did not work BUT conda has a geopandas installer

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#411]
@daren-thomas my attempt of installing geopandas with the newest versions of shapely, etc was not successful (maybe my fault, I only tried once).
The previously downloaded wheels worked.

During debugging of some code I got the strange message, that I need `rtree`. By researching a bit on how to install I found this:
https://anaconda.org/ioos/geopandas

It seems that there are easy packaged installers for geopandas out there!

**Comment by daren-thomas** [comment]
cool! I'll give it a check: this could make installation of the cea sooo much easier!

**Comment by daren-thomas** [comment]
I have tried and tried... I keep getting the following error:

```
(esri104) C:\Windows\system32>conda install -c ioos geopandas==0.2.1
Fetching package metadata ...........
Solving package specifications: ....
UnsatisfiableError: The following specifications were found to be in conflict:
  - geopandas ==0.2.1
  - numpy ==1.9.2
Use "conda info <package>" to see the dependencies for each package.
```

We will have to dig a lot deeper to get this working... But I haven't given up yet...

**Comment by daren-thomas** [comment]
I have saved a copy of the versions mentioned in the installation docs here: https://www.dropbox.com/s/axy30q24by2qw1z/cea-dependencies-wheels.zip?dl=0

**Comment by daren-thomas** [comment]
I have updated the installation guide to point to the dependencies. We will have to figure out a way to make the installation easier. I would *love* to be able to do `conda install cea` and everything else just gets installed...

**Comment by gabriel-happle** [comment]
@daren-thomas this can be closed I think.

**Comment by daren-thomas** [comment]
check out PR #554
