### ISSUE TITLE
Expand sensitivity analysis

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#416]
Now that the sensitivity analysis runs in Euler we can proceed to expand the analysis to include much more input and output variables.

- We will start with expanding it to get monthly simulation results

**Comment by JIMENOFONSECA** [comment]
@daren-thomas  i am receiving this error, do you know what can be the cause? i think i am not able to pass the list of groups correctly to linux. 
![image](https://cloud.githubusercontent.com/assets/8973186/20700962/63c0f3a8-b64b-11e6-9e68-f3ed76a82c15.png)

**Comment by daren-thomas** [comment]
I noticed your branch `i416-expand-sensitivity` adds `problem.pickle` and `samples.npy` to the folder `cea/analysis/sensitivity`... may I ask why? These files are not code, but output of the script and should be in the samples folder... can I delete them from source please?

**Comment by JIMENOFONSECA** [comment]
Yes, delete them.
When i run it from pycharm locally it stores automatically those files there. Btw, running the sensitivity analysis locally seems to not be working. Does it work for you?

Best, Jimeno

On 29 Nov 2016, at 16:30, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


I noticed your branch i416-expand-sensitivity adds problem.pickle and samples.npy to the folder cea/analysis/sensitivity... may I ask why? These files are not code, but output of the script and should be in the samples folder... can I delete them from source please?

**Comment by daren-thomas** [comment]
how are you running it? you need to specify the command line arguments - if you run it in `cmd.exe` you can specify those there, *or* you can configure PyCharm to set them...

**Comment by JIMENOFONSECA** [comment]
i am just running it as script in pycharm and run defaults

**Comment by daren-thomas** [comment]
we can maybe set up some defaults for running it like that...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas so im facing the same problem. too many outputs and i seem to run out of space in the scratch folder. 

![image](https://cloud.githubusercontent.com/assets/8973186/20956589/d36d27a4-bc85-11e6-8416-2a83c468f4bd.png)


After listing the files i can successfully see that there is some output created. it is supposed to be around 56000*9 = 504.000 files. however i get only 468.000. so i guess we run out of storage. Any clue of what we can do?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, your screenshot doesn't really represent the error you mention.

one thing i noticed on your screenshot, though, is that you are using `scp` from within `euler`. Basically, you are asking the euler node to copy a file to itself. The `scp` command you used was supposed to be called from your local computer.

How are you listing the files? I'm particularly interested in the output of the command `ls | wc`. This would list the files and pipe it to `wc`, which stands for word count... the three numbers output would then be, uh, lines, words and characters of it's input...

FileZilla may not fetch all the files, so I'm not convinced (yet) that they aren't there. BUT: if we can confirm a file count problem / space problem. According to the wiki, you should have "a disk quota of 2.5 TB and a maximum of 1'000'000 files and directories (inodes)" in the scratch folder. So... you should be good if you delete old attempts?

**Comment by JIMENOFONSECA** [comment]
Yep.  Apparently the files are there but i am not able to retrieve the results. Would you suggest a away to transfer the files out of euler? Filezilla did not work..

Best, Jimeno

On 7 Dec 2016, at 17:04, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA>, your screenshot doesn't really represent the error you mention.

one thing i noticed on your screenshot, though, is that you are using scp from within euler. Basically, you are asking the euler node to copy a file to itself. The scp command you used was supposed to be called from your local computer.

How are you listing the files? I'm particularly interested in the output of the command ls | wc. This would list the files and pipe it to wc, which stands for word count... the three numbers output would then be, uh, lines, words and characters of it's input...

FileZilla may not fetch all the files, so I'm not convinced (yet) that they aren't there. BUT: if we can confirm a file count problem / space problem. According to the wiki, you should have "a disk quota of 2.5 TB and a maximum of 1'000'000 files and directories (inodes)" in the scratch folder. So... you should be good if you delete old attempts?

**Comment by daren-thomas** [comment]
you could zip it all up in a single file and download that? do you need all the files or just the analysis excel files?

**Comment by daren-thomas** [comment]
Try this page for some ideas on how to zip the samples folder: http://unix.stackexchange.com/questions/57013/zip-all-files-in-directory

**Comment by JIMENOFONSECA** [comment]
I just need the analysis files. I checked in brutus wiki and it says that you can use scp to extract also files from the cluster into a local workstation. I did not have success.

Best, Jimeno

On 7 Dec 2016, at 18:58, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Try this page for some ideas on how to zip the samples folder: http://unix.stackexchange.com/questions/57013/zip-all-files-in-directory

**Comment by daren-thomas** [comment]
After our skype meeting today, I understand it is working for you now?

**Comment by JIMENOFONSECA** [comment]
Yep, i have to do a couple of checks more though...

Best, Jimeno

On 8 Dec 2016, at 18:05, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


After our skype meeting today, I understand it is working for you now?

**Comment by JIMENOFONSECA** [comment]
waiting for  #434 to be merged
