### ISSUE TITLE
Document credits convention

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#417]
We use the following convention for documenting the credits and other information in the python scripts:

```
__author__ = "Jimeno A. Fonseca; Daren Thomas"
__copyright__ = "Copyright 2016, Architecture and Building Systems - ETH Zurich"
__credits__ = ["Jimeno A. Fonseca", "Daren Thomas"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "Daren Thomas"
__email__ = "thomas@arch.ethz.ch"
__status__ = "Production"
```

This needs to be added to the contributor's manual.

**Comment by daren-thomas** [comment]
@martin-mosteiro do you want to take care of this? And assign the issue to yourself? I think this would also go with your changes for the PR #414.

**Comment by martin-mosteiro** [comment]
@daren-thomas Done.
