### ISSUE TITLE
Make sure column names in schedules match ISO standard

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#43]
Use the ISO standards (**FIXME:** which ones?) as the basis for naming the schedules. Check each column name to see if it is the correct name.

These column names must be updated in the documentation (`demand.md` and possibly the appendix)

**Comment by shanshanhsieh** [comment]
A quite diverse notation of variable names was found in 30% of the data. It still works like this, but it would be great to have a standad notation
