### ISSUE TITLE
Update documentation to explain the tool for interested parties

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#439]
- what does the tool do?
- what modules are included?
- what is the method used by these modules?
- related papers / research / standards / *equations*
- diagram of how different parts connect to each other (workflow flowchart)
- Teaching material should be included in the documentation
- Video tutorials
- talking about which technologies (systems) are included and how they are modeled

problem we're trying to solve: make it really easy for researchers to discover our tool and decide whether it will help them.

An inline example showing the workflow, equations, input / output files. WALKTHROUGH. 
salib is an model example of how we want to document our stuff. pymc3.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA is looking for some extra help in the documentation efforts.

Most of this information needs to be done by end of January.

**Comment by JIMENOFONSECA** [comment]
this is part of the issue #480
