### ISSUE TITLE
Rewrite the "Getting started" chapter

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#442]
- it should reflect how to get started with the tool
- the sandbox is not present anymore
- we should not start the document with a big list of rules and regulations
  - that does not create trust in our product
  - that creates distrust in our procedures (this is subtle, but think about it: do you want to start using a tool for your research, where the main focus of the documentation, the "getting started" bit, is not on how to integrate it into your research, but instead on what the various "circles of trust" are?)

The idea is to put all this at the end of the documentation. Or put it at the developers. Put it under a section of how to contribute.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA do you want to take over this issue? I'm starting by adding an overview workflow description...

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you take a look at this?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this is part of the #386 . could these tasks be moved there?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I'd prefer not to. Here's why: This task is about writing. It is about re-formulating our message. In my mind, #386 is more about the plumbing: How to publish our documentation on RTD, including an automatic API documentation. Keeping these tasks apart will make it easier to complete them as they retain focus.

What do you think?

**Comment by JIMENOFONSECA** [comment]
I got you, let's do that. Btw is it possible to move the .md files to the read the doc page you are creating? Is there a guide? I can do plumbing and writing simultaneously :-)

Best, Jimeno

On 8 Feb 2017, at 16:32, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I'd prefer not to. Here's why: This task is about writing. It is about re-formulating our message. In my mind, #386<https://github.com/architecture-building-systems/CEAforArcGIS/issues/386> is more about the plumbing: How to publish our documentation on RTD, including an automatic API documentation. Keeping these tasks apart will make it easier to complete them as they retain focus.

What do you think?

**Comment by daren-thomas** [comment]
I'm on it. I will explain tomorrow: We will need to reformat the .md files to .rst files. But since we don't have that much documentation, it should be a piece of cake! (also, maybe I can use pandoc to do an automatic translation?)

**Comment by JIMENOFONSECA** [comment]
Great stuff in the read the docs, should we close this issue @daren-thomas

**Comment by daren-thomas** [comment]
not yet: we haven't addressed the getting started stuff quite yet. I'm sorry. The milestone is slipping.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can we close this?

**Comment by JIMENOFONSECA** [comment]
waiting to merge PR #545 to close it
