### ISSUE TITLE
Infiltration as a function of Archetype and building/renovation year

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#449]
Is this currently the case? The infiltration rate could be guessed as a function of archetype and building/renovation year.

**Comment by daren-thomas** [comment]
@gabriel-happle maybe you know about this?

**Comment by gabriel-happle** [comment]
@daren-thomas Currently air tightness of the envelope is related to the U-Values of the windows (which are basically a function of building/renovation year).
Source is the DistrictECA DB http://www.district-eca.de/index.php?lang=en

**Comment by daren-thomas** [comment]
@gabriel-happle, thank you. What do you suggest we do with the issue? Is this something we want to add? Also, we need to document the information you just provided.

**Comment by gabriel-happle** [comment]
https://gabriel-happle.gitbooks.io/cea-thermal-loads-ventilation/content/ventilation_properties_of_buildings.html

@daren-thomas can you open this link? some of the documentation is basically ready for some time but has never been integrated in the public gitbook

**Comment by daren-thomas** [comment]
@gabriel-happle this is really great stuff! Can you take responsibility of ensuring this shows up in the documentation at some point?
