### ISSUE TITLE
Split demand script output `Eauxf` into auxillary and ventilation

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#45]
`Eauxf` is the final auxillary electricity in [kWh] for fans and pumps. Split it into a fans portion and a pumps portion.

**Comment by shanshanhsieh** [comment]
Split demand script output `Ealf` according to more detail usages
ex. separate lighting demand from others

**Comment by gabriel-happle** [comment]
@daren-thomas the splitting of Eauxf seems to be a simple reporting issue. These values can be reported individually.

```
        # Calc total auxiliary loads
        Eauxf = (Eaux_ww + Eaux_fw + Eaux_hs + Eaux_cs + Ehs_lat_aux + Eaux_ve)
```
@shanshanhsieh this is also easy and can be done in `get_internal_loads()`

I think it will be easier, after my pull request #226  with the second `calc_thermal_loads()` is merged.
