### ISSUE TITLE
Radiation tool fails on ninecubes scenario

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#452]
The scenario we ship as an example does not work with the radiation tool. We found this out while installing the CEA on johannes' computer.  It might also fail for other scenarios:

```
Executing: RadiationTool C:\Users\johhofer\Documents\CEA\ninecubes\baseline Zurich 2014 46.9524055555556 7.43958333333333
Start Time: Mon Jan 09 15:17:57 2017
Running script RadiationTool...
longitude: 7.43958333333
latitude: 46.9524055556
complete calculating sunrise
complete burning buildings into raster
complete calculating boundaries

Traceback (most recent call last):
  File "C:\Users\johhofer\Documents\GitHub\CEAforArcGIS\cea\GUI\radiation_tool.py", line 130, in execute
    longitude=longitude, year=year, gv=gv, weather_path=weather_path)
  File "C:\Users\johhofer\Documents\GitHub\CEAforArcGIS\cea\resources\radiation.py", line 119, in solar_radiation_vertical
    CalcObservers(Simple_CQ, observers, DataFactorsBoundaries, path_arcgis_db, gv)
  File "C:\Users\johhofer\Documents\GitHub\CEAforArcGIS\cea\resources\radiation.py", line 373, in CalcObservers
    arcpy.ErasePoint_edit(Observers0, NonoverlappingBuildings, "INSIDE")
  File "c:\program files (x86)\arcgis\desktop10.4\arcpy\arcpy\edit.py", line 90, in ErasePoint
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Remove Features: Dataset C:\Users\johhofer\Documents\ArcGIS\Default.gdb\Non_overlap does not exist or is not supported
Failed to execute (ErasePoint).


Failed to execute (RadiationTool).
Failed at Mon Jan 09 15:18:31 2017 (Elapsed Time: 33.34 seconds)
```

We tried the *reference-case-open* and we have tried both weather files: Zurich and Zug.

@JIMENOFONSECA can you take a look at this and assign it to yourself?

**Comment by JIMENOFONSECA** [comment]
who is johnhofer? somebody messed up the code and commited to the master withotu permission. is  thi issue still open?

**Comment by JIMENOFONSECA** [comment]
Tested. It works in my pc with the latest version of CEA , no changes made. pleas let me know if this is still the case

**Comment by JIMENOFONSECA** [comment]
@daren-thomas it works in mine, maybe gabriel's work fixed this issue. is it working in yours?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA what happened to the zip file? I think that breaks some of my code (not in a bad way, just, will need to fix)

**Comment by JIMENOFONSECA** [comment]
So it should be there in master. But in the other pull requests it will change to an unzipped folder structure of an scenario so it can be read and read from pycharm. Would you agree with it? We can also put it as a zip file which could also work and everytime it changes we zip it again. Maybe this keeps some kind of data integrity?

Best, Jimeno

On 21 Mar 2017, at 17:13, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> what happened to the zip file? I think that breaks some of my code (not in a bad way, just, will need to fix)

**Comment by JIMENOFONSECA** [comment]
I just zipped it.
