### ISSUE TITLE
Refactoring opportunities for demand calculation

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#454]
Based on some function tracing I've been doing for pr #448 (as requested by #441, Create call graph for the various scripts) I have created the following representation of which modules call which other modules as part of the demand calculation:

![image](https://cloud.githubusercontent.com/assets/2969564/21975178/7a62f00c-dbcb-11e6-9ea8-a7f32595ac90.png)

Viewing this graph, you can see some interesting arrows. I have highlighted the ones that I think point to code "smells":

- does `demand_main` need to access the occupancy model? Could be, but we do have an issue open for the next milestone to refactor some of that...
- I think we can separate `cea.technologies` into a controllers part and a emission systems part and a storage systems part
- the `geometry_reader` could also just be part of the ventilation model
- the `physics` module could be part of the `airconditionaling_model` until it is needed somewhere else...

**Comment by daren-thomas** [comment]
@JIMENOFONSECA any comments on this?

**Comment by JIMENOFONSECA** [comment]
For the geometry reader i believe it will be depreciated once citygml is in. Zhongming and kianwee are working in this.

The intention of Physics is to use them in other algorithms so i will keep it outside for the moment.

The cea technologies can be divided as you said. I will however add a subfolder called 'generation' on top.

In regard to the demand_main there is not too much to do at the moment

**Comment by daren-thomas** [comment]
this changes a lot with @gabriel-happle 's branch, so let us wait for that to merge first...
