### ISSUE TITLE
Installation guide-CEA documentation

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#457]
Make a list of the steps involved in installation of CEA along with screenshots or the add the text output provided by the command prompt

**Comment by BhargavaKrishnaSreepathi** [comment]
[Installation Guide.docx](https://github.com/architecture-building-systems/CEAforArcGIS/files/710350/Installation.Guide.docx)

Gave a detailed explanation of steps involved in CEAforArcGIS installation. Do let me know if you have any comments

**Comment by daren-thomas** [comment]
Great work! Can you update the online documentation to reflect this? This will require writing in markdown. Ping me if you need any pointers.
