### ISSUE TITLE
Installation error detected in relation to ArcGIS

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#459]
In my many adventures in installing the CEA tool box, i have encountered one weird interaction between ArcGIS and CEA tool box. I found that in the C:\Python27 folder, there needs to be only folder containing ArcGIS10.4. It should not have any other files which correspond to previous installation of ArcGIS, which can happen if the ArcGIS software is uninstalled and reinstalled, but the user has his preferences saved. The errors in this scenario include but are not limited to "no numpy module detected", "no geopandas detected". One way to surpass this is to uninstall ArcGIS, delete all the files present in C:\Python27 folder and then reinstall ArcGIS.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas what is the best way to remember about this? should we keep it where?

**Comment by daren-thomas** [comment]
This does not happen with the new way of installing the toolbox (`cea install-toolbox`) which doesn't care anymore which python ArcGIS uses, as long as it is a standard python - we run the cea in it's own python now :)

I'm closing this issue as it is not relevant anymore.
