### ISSUE TITLE
Create Indoor Comfort model

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#46]
What norm is this based on? What are the exact criteria used to calculate this field?

**Comment by JIMENOFONSECA** [comment]
no need of a norm, it is calculated as 1 i if the supply system is not able to supply enough energy to heat the space. This can happen especially in buildings with floor heating. this issue will be changed to "create indoor comfort model" as the model should be complemented with humidity.
