### ISSUE TITLE
Create a tutorial about the installation procedure

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#461]
Before we get our .exe or pip installation. we need to fix the procedure of installation.

**Comment by daren-thomas** [comment]
Could this have been fixed with @BhargavaKrishnaSreepathi 's screenshots that he added to the installation procedure?

**Comment by JIMENOFONSECA** [comment]
Yes!

Best, Jimeno

On 18 Jan 2017, at 20:25, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


Could this have been fixed with @BhargavaKrishnaSreepathi<https://github.com/BhargavaKrishnaSreepathi> 's screenshots that he added to the installation procedure?

**Comment by BhargavaKrishnaSreepathi** [comment]
Closing the issue as the installation procedure is updated.
