### ISSUE TITLE
Create CEA's own website

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#462]
This includes but is not restricted to:

Need of a website to show features, updates, team, reach out people and main features.
----Create a list of use cases for the website. @amr priority 1.
----Diagram of CEA tool from the SBE conference.
---- List of standards used in the tool need to be added.
----Show what makes it different to other tools - and compare them.
Exercise to get it to know (http://doc.arcgis.com/en/arcgis-online/get-started/quick-exercise-maps.htm) and run one case study.

**Comment by JIMENOFONSECA** [comment]
@shizhongming please provide graphics for the intro webpage. I created some examples on the website already.

**Comment by JIMENOFONSECA** [comment]
@amraladdin @shizhongming  

For the user manual of the tool. Would you like to have it on the website (e.g.,http://urbanmodellinginterface.ning.com/page/user-guide)

or would you like to be it togetter with the developer's manual?
(e.g., https://pymc-devs.github.io/pymc3/)

@daren-thomas what is your preference too?

**Comment by amraladdin** [comment]
Since we have the manual in text and images at the moment, I believe we can add it to the developers' manual for now, and when we have the videos, we can propose to add them separately, like the UMI tutorials... What do you guys think?

**Comment by daren-thomas** [comment]
I'm not really sure about the difference between your examples? They look structurally more or less the same?

**Comment by JIMENOFONSECA** [comment]
Hi All! so here is the list of things we could do among ourselves for the **NEW** website. I took the liberty to divide the tasks by each one of the sections of the website. Please let me know if there are any doubts. It would be great if we can finish by Thrusday the 26.Feb.

@shizhongming 

…Join / Featured Research Topics
-	add an open-source picture representative of each research topic
…Partners
-	add logos of all partners and cut all of them into a frame of 16:9 ratio with a white background. (CREATE, SEC, FCL, VEOLIA, ECOCAMPUS, A/S, Francois Chair and ETHZ)
…Home/Features at Glance.
-	Create representative Icon of every Feature. As in the example in the website. (a circle inside a square of grey color).

@martin-mosteiro 
..Blog/Workshop Zurich
-	Find Best > 3 Fotos and >3 output diagrams of the SBE workshop. Create a description of about 300 – 500 words of the workshop. 

..Research/Case Studies
-	Zurich – University campus (Hoschulquartier): Describe the project and the role of CEA in it following page’s format. Gather 3 Pictures of the Project.

@gabriel-happle 
..Research/Case Studies
-	Singapore Ecocampus: Describe Ecocampus project and the role of CEA in it following page’s format. Gather 3 Pictures of the Project. send info to Jimeno

@shanshanhsieh 
..Research/publications
-	Gather all the publications that relate to the CEA and get a link to them. (check e-citations of MuSES. Send them to Jimeno. (follow API citation style). 
..People
-	Gather High-res portrait Color photos and e-mail addresses, credentials and websites of everyone at CEA. This included Francois, Arno, and Nicolas from Veolia. Also former contributors. Paul. Send them to Jimeno.

@BhargavaKrishnaSreepathi 
..User/Guide/
-	Upload to the **new** website the user manual (only examples and guides created by Zhongming and Amr). Follow example of the installation. Please ask amr and Zhongming for where to find the manual. I gues it is in Gitbook.

 @Jimeno
..Join / Featured Research Projects
-	Copy from all the projects the three most important

..Join/Finished projects
-      Copy abstract from Paul’s thesis and add a picture.

..Research/Case Studies
-	Zug Industry: Describe project and the role of CEA in it following page’s format. Gather 3 Pictures of the Project.

…Home / intro
-	add open-source photos of good quality (real) of the areas or campuses. Ask Jimeno for that one of Zug, Ask Martin for that one of Zurich, Ask Gabriel for one of NTU.

…Research / Roadmap
-	add information and pictures of RoadMap or About section

…Features/
-	tbd after meeting.

**Comment by JIMENOFONSECA** [comment]
btw,  please Make sure all images have less than 1Mb of wight! use https://tinyjpg.com/ to compress them before uploading)

**Comment by JIMENOFONSECA** [comment]
Sorry guys, i messed up, It would be great if we can finish by **Thrusday the 26. January**

**Comment by JIMENOFONSECA** [comment]
Thanks to everyone for their input. I will close the issue as the website is up and stable. Further modifications will be submitted as individual issues.
