### ISSUE TITLE
Create CEA's documentation website

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#463]
Need of a website to show documentation for developers (read the docs kind). This should contain mainly information about the functions and workflow of the tool.

---- Store it in GitDocs.
---- The formula for showing scripts: (top-down and bottom-up). 2 callgraphs (one coarse, one in detail) followed by the description of every function using SphynX.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA for clarification: what is GitDocs?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA what is the status on this? I think you are creating the website, right? I have a task #386 for the RTD api documentation. See the issue for a preview of what it could end up looking like.

**Comment by JIMENOFONSECA** [comment]
this issue is supposed to be #386. i think this is a duplicate then.... The CEA documentation website is intended to be in RTD or did i get it wrong?

**Comment by JIMENOFONSECA** [comment]
i meant RTD when i said gitdocs, sorry...

**Comment by daren-thomas** [comment]
You are right. Closing this as a duplicate.
