### ISSUE TITLE
Create a list of potential CEA users and their needs

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#468]
In order to understand the needs of each user and how useful the CEA Toolbox is for them.

**Comment by amraladdin** [comment]
List created and awaiting contributions!

**Comment by JIMENOFONSECA** [comment]
@amraladdin is this done?

**Comment by amraladdin** [comment]
Hey @JIMENOFONSECA from my side yes.
I got only one more contribution from Bahrga. I didn't want to close this issue before we discuss about it. I believe this could be important for your workshop next week.
