### ISSUE TITLE
cea.sensitivity.sensitivity_optimization.py doesn't work

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#472]
It can't work. The imports don't work. This never worked

- `import cea.optimization.evolAlgo.evaluateInd as eI` (evolAlgo doesn't exist)
- the variation of globalvars used doesn't work
- the code is a mess

I'm not sure what it is for at all (we have another sensitivity analysis code - which one is this one?)

**Comment by JIMENOFONSECA** [comment]
This is for the optimization part @BhargavaKrishnaSreepathi  could you check if it works? the idea of this code is to take the results of a generation, change the prices of some fuels, re-run and based on certain criteria erase the individuals that are not robust enough

**Comment by BhargavaKrishnaSreepathi** [comment]
Sure, let me take a stab at it

**Comment by BhargavaKrishnaSreepathi** [comment]
Hi @JIMENOFONSECA. I will summarize my understanding of the necessity of the file, please correct me if i am wrong.
1. We take the population of a certain generation
2. we change the unit prices of utilities like electricity, natural gas prices and see the solution which is least sensitive to the variations in these prices.
3. We then proceed to remove the individuals which are very sensitive from the generation and only keep the solutions which are robust

**Comment by JIMENOFONSECA** [comment]
You are right :-)

Best, Jimeno

On 10 Feb 2017, at 12:19, BhargavaKrishnaSreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @JIMENOFONSECA<https://github.com/JIMENOFONSECA>. I will summarize my understanding of the necessity of the file, please correct me if i am wrong.

  1.  We take the population of a certain generation
  2.  we change the unit prices of utilities like electricity, natural gas prices and see the solution which is least sensitive to the variations in these prices.
  3.  We then proceed to remove the individuals which are very sensitive from the generation and only keep the solutions which are robust
