### ISSUE TITLE
Move contributions to own repository, remove sandbox

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#474]
I believe we should move the contributions folder to it's own repository. In fact, I'm still not sure what we use it for. @JIMENOFONSECA could you please explain again?

I think we can remove the sandbox folder and also the sandbox branch. We should probably vote on this or at least discuss some, but I really think it gets in the way and promotes giant merges as opposed to smaller, task-based merges.

**Comment by daren-thomas** [comment]
the folder is not there anymore...

**Comment by JIMENOFONSECA** [comment]
yep it is out, i did not noticed in which merge it went down, but well, we do not need them right?

________________________________
