### ISSUE TITLE
Check benchmarks database and documentation

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#479]
The benchmarks databases could probably be stored in a single excel file. The naming of each tab should be in Capital letters to maintain consistency. Consider changes into the documentation and the references to all the values. @martin-mosteiro could you take care of this part?

**Comment by martin-mosteiro** [comment]
Can

**Comment by martin-mosteiro** [comment]
The benchmark databases have been moved into a single file with the formatting specified in this issue. These changes have been incorporated in Pull request #485 .

The documentation will now be updated accordingly.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro yes there should be a separated version in read the docs. I did it in gitbook let me know if you can see it

**Comment by martin-mosteiro** [comment]
Finished the Gitbook documentation. This issue is now closed.
