### ISSUE TITLE
Equipement use in Properties and Archetypes

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#48]
The use of Equipment has become obsolete for other cases without industrial use. It will be taken away shortly to simplify the problem.

**Comment by daren-thomas** [comment]
so... we are removing industrial use cases from the features?

**Comment by JIMENOFONSECA** [comment]
Not necesarly, maybe we just remove what is not being used. parts of the variables E1, E2, E3
