### ISSUE TITLE
Complement "readthedocs" style API documentation for the CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#480]
The new read the docs documentation needs to migrate work from gitbook + other fixes to be discussed

**Comment by JIMENOFONSECA** [comment]
copied form issue #439 as issues that the documentation should have

what does the tool do?
what modules are included?
what is the method used by these modules?
related papers / research / standards / equations
diagram of how different parts connect to each other (workflow flowchart)
Teaching material should be included in the documentation
Video tutorials
talking about which technologies (systems) are included and how they are modeled
problem we're trying to solve: make it really easy for researchers to discover our tool and decide whether it will help them.

An inline example showing the workflow, equations, input / output files. WALKTHROUGH.
salib is an model example of how we want to document our stuff. pymc3.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA who should be working on this?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA how far is this issue completed? It's not really a S.M.A.R.T. goal and contains a lot of separate tasks... Maybe we can clean this up a bit?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas we can talk about this after group meeting
