### ISSUE TITLE
calc_Y: check with standards for naming / result

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#49]
the function `calc_Y` returns a list of transmittance values for pipes depending on the year of retrofit...

- why is the result called `Y`? this only makes sense if the standards equations use this naming.
- we should rename the function to `calculate_pipe_transmittance_values`
- we should consider moving this to the archetypes instead
- the result should probably be a named tuple (unless the standards use indexes, but even then...)

**Comment by JIMENOFONSECA** [comment]
#24 refers the same issue, I will close #24
