### ISSUE TITLE
Archetype documentation issues

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#495]
@JIMENOFONSECA When trying to create new archetypes for the Hochschulquartier I came through multiple issues in the documentation of the source data for the archetypes. Here are the issues I found:

1. Some values do not match the source (especially SIA 2024):
1.1. Occupancy: e.g.: the probability of people being at home according to SIA 2024 is 0 between 9 and 12 and between 15 and 17 (it never gets to zero on the CEA archetypes); this is one example among many such inconsistencies
1.2. Ve_lps: again, doesn't always match the standard

2. Some values are not even available at the source (SIA 2024):
2.1. Probability of domestic hot water consumption: there is **no such profile in the standard**; some have values such as "0.413793103448276", which makes me think they are probably calculated somehow.
2.2. Setback temperatures: referenced to SIA 2024, but I couldn't find any information on it in the standard (seem to have been simply assumed)
2.3. Internal gains _Ere_, _Ed_: again I couldn't find any information in it on non-HVAC cooling electricity and server electricity

3. Some values are based on a different source:
3.1. **Vw, Vww**: these are referenced to SIA 2024, but the values don't match the standard at all; in fact, I seem to remember @amraladdin changing these because the results were not really plausible - do you remember the source used, @amraladdin ?

The manual should be adapted to account for whatever other sources were used.

**Comment by amraladdin** [comment]
Hey Martin... I honestly don't remember. Can I take a look at it early March? I'm kind of bombarded with work till end of the month :)

**Comment by martin-mosteiro** [comment]
No worries, this is rather low priority stuff I guess. But since we just did this whole documentation run, I thought we might as well get it right ;)

**Comment by amraladdin** [comment]
@martin-mosteiro are you still looking for an answer from my side on the Vw and Vww issue?

**Comment by martin-mosteiro** [comment]
Well, we still don't have a reference. So yes :)

**Comment by martin-mosteiro** [comment]
We checked the oldest version of the Archetypes_properties file on GitHub and the values for Vw and Vww are the same as the current ones. So I seem to have been mistaken on point (3.1) in this issue.

However... the values still don't match SIA 2024 and we still don't have a reference for that. Plus the other two points in this issue still haven't been resolved...

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Since you created these archetypes, I believe only you can clarify this.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro The SIA standard shows schedules per room. (e.g., bathroom, corridor, bedroom, living room, kitchen etc..), In order to create schedules for an use (MULTI-RESIDENTIAL). we used a combination of schedules in several rooms multiplied by a weigth. (Unfortunately I cannot anymore find which weight was assigned). This is why you could find numbers such as 0.44444 etc.. 

Now. for Vww and Vw all schedules are equal to the occupancy EXCEPT for MULTI and SINGLE, for the last, the schedules where taken from a survey in Switzerland of consumption of hot water in the 70's.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro how should we proceed with this issue? would you make it SIA compliant?

**Comment by martin-mosteiro** [comment]
I think this is probably not an issue of content, just of documentation.
- Occupancy schedules: I think the combination you mentioned above makes sense, it's just too bad we don't have a reference to how it was done. But in principle it looks okay.
- Ve_lps doesn't always match the standard: I guess it's also a result of this combining the standard for, say, bedroom+living room+kitchen=MULTI_RES. So I'd say it's okay.
- Probability of domestic hot water consumption, setback temperatures, Ere, Ed: the values could be okay, we just shouldn't reference them to SIA 2024 since they are not actually taken from there
- Vw, Vww: we should probably find the source used for these...

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro I agree, would you mind changing the references to assumptions for now? 

This is the reference to Vw, Vww for MULTI and SINGLE 

Blatter M, Borel M, Simmler H, Paul H. Warmwasserbedarfszahlen und Verbrauchscharakteristik. Bern; 1993.

**Comment by martin-mosteiro** [comment]
![image](https://user-images.githubusercontent.com/18548065/27729243-618c131a-5d85-11e7-9b7d-2cffe70be0d2.png)

**Comment by martin-mosteiro** [comment]
Well, actually... _can't_ do.
The sources I referenced came from the [Building Properties](https://architecture-building-systems.gitbooks.io/cea-toolbox-for-arcgis-manual/content/building_properties.html) subsection of the Archetypes page on Gitbook... which we're not using anymore.
On the readthedocs [Archetypes section](http://city-energy-analyst.readthedocs.io/en/latest/archetypes.html), however, there is no subsection - neither for building properties nor for schedules.
Was this a conscious decision or is this a mistake? If it's the latter, I can always create a new subsection on read the docs and update the references above.

**Comment by JIMENOFONSECA** [comment]
Well we put all that info in the tutorials. So i guess that would be the place to put the references.

However it would be good to link this information in the developers manual too

Best, Jimeno

On 30 Jun 2017, at 23:22, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, actually... can't do.
The sources I referenced came from the Building Properties<https://architecture-building-systems.gitbooks.io/cea-toolbox-for-arcgis-manual/content/building_properties.html> subsection of the Archetypes page on Gitbook... which we're not using anymore.
On the readthedocs Archetypes section<http://city-energy-analyst.readthedocs.io/en/latest/archetypes.html>, however, there is no subsection - neither for building properties nor for schedules.
Was this a conscious decision or is this a mistake? If it's the latter, I can always create a new subsection on read the docs and update the references above.

**Comment by gabriel-happle** [comment]
@martin-mosteiro yes. I created sources files for the Singapore case. This is for partly for my own documentation. So that I remember the different sources for Singapore. But I think it could also be a way for general documentation.
what do you think @JIMENOFONSECA ?

**Comment by JIMENOFONSECA** [comment]
Any way you guys consider the most convenient is fine for me. Please bear in mind the tutorials include tables with all the variables. It could make sense to indicate where the reference can be found.



________________________________

**Comment by martin-mosteiro** [comment]
I'm happy as long as we have a clear reference for ourselves for every value. Option 1 = create an xls file for the Swiss references; Option 2 = create documentation for both case studies. Since Option 1 involves less of an overhaul, I'd go for that.

I'll create an xls file with the Swiss references.

**Comment by martin-mosteiro** [comment]
After discussion with Daren, we decided it was worth keeping the existing documentation on the readthedocs, so I simply copied the existing text to our current documentation instead.
