### ISSUE TITLE
ScenarioPlotsTool throws `NameError:  global name 'arcpy' is not defined`

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#498]
ScenarioPlotsTool not working as 'import arcpy' is not done in the file

**Comment by daren-thomas** [comment]
updated issue title to reflect the actual issue.

**Comment by BhargavaKrishnaSreepathi** [comment]
Issue is fixed and Pull Request has been accepted
