### ISSUE TITLE
NTU EcoCampus: Split building shape file into individual buildings and update names in attribute table

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#506]
Split building shape file into individual buildings and update names in database.
Set up zone / district database.
- floors_bg
- floors_ag
- Bwidth
- Blength
- height_bg
- height_ag

split footprints into individual buildings (with google earth, or similar info)
assuming floor height, extracting no. of storeys from excel sheet (room names)

**Comment by gabriel-happle** [comment]
@shizhongming I will start with #511. I can also check for the number of floors in each building.

**Comment by gabriel-happle** [comment]
@shizhongming building age is in the first tab of the facilities listing Excel file.

**Comment by shizhongming** [comment]
@gabriel-happle Ok! I will start with this one~

**Comment by shizhongming** [comment]
The Shapefile split is done. We use the NTU map as references. Open to changes.

**Comment by gabriel-happle** [comment]
@shizhongming Could you please split S2.1 and S2.2 for me? ;)
Xie Xie
Also we should better remove special characters like '@' and '&', etc. from the names
