### ISSUE TITLE
EcoCampus: Set up building architecture database

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#508]
- Name
- win_wall []
- type_shade
- Occ_m2p
- n50
- win_op
- f_cros
- type_roof
- type_wall
- type_win

roof type; from google earth (flat/pitched), average building height for green roof building.
peak occupancy: from applicable construction code.
air tightness: assumption from age of building, literature review (usual values for simulations in SG).
material properties base plate: from Revit models (assume concrete slab w/o insulation).
material roof: extract from google earth.
shading: survey (street view)

**Comment by gabriel-happle** [comment]
@shizhongming we will do this together

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA What is the actual input data needed to run the CEA? Could you please document this? For me it is not clear which of the shapefiles are produced by the properties script. It seems some are produced, some are modified (i.e. columns added by calculation) and some are actual inputs.
Should we produce the files necessary to run the demand? (but then there are no U-values, thermal mass, etc. ...)
Or should we produce the files necessary to run the properties script? (then we need the archetypes DB for Singapore)?

**Comment by gabriel-happle** [comment]
@shizhongming http://libguides.nus.edu.sg/c.php?g=145647&p=954488 I think we have to get these standards

**Comment by gabriel-happle** [comment]
@shizhongming maybe we can use these categories for green roofs

**Comment by JIMENOFONSECA** [comment]
For this case,

I suggest:

We call the properties file with the archetypes of zurich

Then we modify the input files generated with the data we collected.

With the time we will need to build an archetypes database for singapore. But i see it quite a lot of work now and the clock is ticking to deliver the project results..

Best, Jimeno

On 1 Mar 2017, at 12:17, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> What is the actual input data needed to run the CEA? Could you please document this? For me it is not clear which of the shapefiles are produced by the properties script. It seems some are produced, some are modified (i.e. columns added by calculation) and some are actual inputs.
Should we produce the files necessary to run the demand? (but then there are no U-values, thermal mass, etc. ...)
Or should we produce the files necessary to run the properties script? (then we need the archetypes DB for Singapore)?

**Comment by shizhongming** [comment]
Based on different sources, the number of floors, the window-to-wall ratio and roof type are done. @gabriel-happle for the roof type, most of them are just flat room without green.....
