### ISSUE TITLE
EcoCampus: set up indoor comfort database

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#509]
- Name
- Tcs_set_C
- Ths_set_C
- Tcs_setb_C
- Ths_setb_C
- Ve_lps

temperature set points: ask NTU (ask for meeting with facility manager), especially labs
humidity set points: ask NTU (ask for meeting with facility manager)
ventilation rate: CEA (SIA)

**Comment by gabriel-happle** [comment]
see archetypes SG in google drive

**Comment by JIMENOFONSECA** [comment]
- [ ]
