### ISSUE TITLE
EcoCampus: set up occupancy database

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#511]
- Name
- PFloor
- HOTEL
- COOLROOM
- PARKING
- SCHOOL
- OFFICE
- GYM
- HOSPITAL
- INDUSTRIAL
- RETAIL
- RESTAURANT
- SINGLE_RES
- MULTI_RES
- SERVERROOM
- SWIMMING
- FOODSTORE

Todo:
Add Labs and maybe circulation spaces

functions: 
facilities listing Excel sheet, percentages of functions according to CEA list of functions (office, lab, school mix), HS & ES (assumption, air conditioned space, electrified space = common space is electrified & non-air-conditioned)

**Comment by gabriel-happle** [comment]
Proposed conventions for categorization of functions:
- staff lounge -> OFFICE
- student lounge -> SCHOOL
- research -> OFFICE
- research lab -> LAB
- teaching lab -> SCHOOL

@JIMENOFONSECA any comment? Do we need an additional type for Library? or which one would you suggest.

**Comment by JIMENOFONSECA** [comment]
Tricky one. Does the SIA 2024 offer a library? we might check if it is similar to other uses. if not, we might need to add it...


On 28 Feb 2017, at 9:47 am, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


Proposed conventions for categorization of functions:

  *   staff lounge -> OFFICE
  *   student lounge -> SCHOOL
  *   research -> OFFICE
  *   research lab -> LAB
  *   teaching lab -> SCHOOL

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> any comment? Do we need an additional type for Library? or which one would you suggest.

**Comment by martin-mosteiro** [comment]
It does: 4.3 Bibliothek under the building category "school"

**Comment by gabriel-happle** [comment]
Processing done.
Check Building_Functions_GH_20170227.xlsx in google drive.

Seems we need LAB, LIBRARY and COMMON & CIRCULATION.
You were working on the circulation space @martin-mosteiro ?

**Comment by martin-mosteiro** [comment]
No, not really. I created the LAB archetype, that's it. Library should be pretty easy to define. Common & circulation could be a bit trickier (a lot of the properties would depend on the building's main use, I suppose)

**Comment by gabriel-happle** [comment]
@martin-mosteiro cool. so we have LAB to start from. Is it already merged to the database?
I can also create the Library based on SIA.
Regarding the Common & Circulation - we plan to use it in SG context to determine the fraction of conditioned space vs. non-conditioned space (Hs). We will probably just assume some lighting for those spaces. And no occupancy.

**Comment by martin-mosteiro** [comment]
@gabriel-happle Yep! Pull request #503 . The Library archetype would probably be interesting here too. Do you think your archetype will only be applicable to the SG case or also CH?

**Comment by shanshanhsieh** [comment]
@martin-mosteiro I added the library schedule from SIA2024 to archetype schedule, so it should work for the Swiss case. (see pull request #523 )
As for Singapore, we might have to investigate the monthly variation (because the vacation periods are probably different....)

**Comment by martin-mosteiro** [comment]
@shanshanhsieh Yep, the schedule should obviously be valid for CH. My question was aiming more to the construction archetypes - did you guys also create a construction archetype for libraries and is it also valid for CH?

**Comment by shanshanhsieh** [comment]
@martin-mosteiro we are not creating a construction archetype especially for libraries in SG at the moment. Will keep you posted if we do. But I doubt that could be applied to ZH though...
