### ISSUE TITLE
EcoCampus: set up supply systems database

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#512]
- Name
- type_el
- type_cs
- type_hs
- type_dhw

hvac systems: assumption (ask Jemma), confirm with NTU intern
dhw system: instant electric heaters for residential buildings

**Comment by gabriel-happle** [comment]
Assumptions: 
- VAV AHU for all Non-residential buildings [Eri@n Bharath Paper]
- no space heating systems
- no hot water systems in non-residential buildings [EcoCampus]
- direct electrical heating of hot water in residential buildings, no tank [EcoCampus]
- type_el is only for GHG emissions -> not needed for demand calculation
- cooling systems of residential buildings ???

**Comment by shanshanhsieh** [comment]
DHW temperature: 38 C
https://www.aosbath.com/4-facts-about-hot-water-pressure-in-singapore/
