### ISSUE TITLE
EcoCampus: create terrain file and street network for EcoCampus

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#514]
Terrain file for solar radiation simulation & visualization purposes.
Street network for visualization purposes.

**Comment by shizhongming** [comment]
Working on this now. At first glance, yes the open street map is not matching the locations of buildings we have....

**Comment by gabriel-happle** [comment]
Terrain file is needed to run solar radiation simulation. TIFF-format.

**Comment by shizhongming** [comment]
@gabriel-happle Terrian file has been put into the spatial data folder of Google Drive

**Comment by JIMENOFONSECA** [comment]
WE close this issue because the street network is not necessary anymore for the ecocmapus case study. the terrain is ready
