### ISSUE TITLE
EcoCampus: clean up and prepare cooling consumption data of EcoCampus

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#516]
- Review provided data
- Extract profiles for validation of demand simulation or as input data to bypass demand calculation (building level, if possible)

**Comment by shanshanhsieh** [comment]
@gabriel-happle Why do we want to bypass demand simulation?

**Comment by gabriel-happle** [comment]
@shanshanhsieh In case we have measured data of special processes we are not able to simulate.

**Comment by shanshanhsieh** [comment]
The `Chiller Consumption` folder is reviewed. All the available information is summarized in `_BTU_BuildingSubstation_Summary.xlsx`
