### ISSUE TITLE
EcoCampus: clean up and prepare electricity consumption data of EcoCampus

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#517]
- review provided measured data
- Extract profiles for validation of demand simulation or as input data to bypass demand calculation (building level, if possible)

**Comment by gabriel-happle** [comment]
Method:
- Remove periods of faulty reporting, i.e. zero for a long time and large number at the end (see picture)

![image](https://cloud.githubusercontent.com/assets/17002288/23542272/22f6e1b8-0027-11e7-8c4d-c00d462b9ffc.png)

**Comment by gabriel-happle** [comment]
Tip by Dr. Clayton Miller (Building Data Specialist):
https://bitbucket.org/berkeleylab/eetd-loadshape

I'm trying to get this to work at the moment.

**Comment by JIMENOFONSECA** [comment]
@cmiller8 would you mind shedding some light on how to do it please? thanks!

**Comment by gabriel-happle** [comment]
I think we can close this for now.
