### ISSUE TITLE
EcoCampus: set up database of thermal properties of buildings in Singapore [part of archetypes DB]]

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#518]
- Es
- Hs
- th_mass
- U_wall
- U_roof
- U_base
- U_win

Es, Hs: facilities listing Excel sheet, percentages of functions according to CEA list of functions (office, lab, school mix), HS & ES (assumption, air conditioned space, electrified space = common space is electrified & non-air-conditioned)
thermal mass: calculate from construction (Revit models), get one building, assume same construction for other buildings
Materials: from Revit models (assume concrete slab w/o insulation for base) / survey / cross check with GM website and google street view

Green roof: from google earth

**Comment by shanshanhsieh** [comment]
http://www.sciencedirect.com/science/article/pii/S0378778813003964
27 different envelope combination based on survey of buildings around central business district in Singapore.

**Comment by gabriel-happle** [comment]
http://www.sciencedirect.com/science/article/pii/S0378778817302931

EnergySimulation parameters for Singapore

**Comment by gabriel-happle** [comment]
Thermal properties of green roofs:
http://www.sciencedirect.com/science/article/pii/S0378778802001081

**Comment by gabriel-happle** [comment]
Simulation parameters of residential buildings in SG:
http://www.sciencedirect.com/science/article/pii/S0360544209004733

**Comment by gabriel-happle** [comment]
Generic office building simulation parameters:
http://www.sciencedirect.com/science/article/pii/S0196890410005388

**Comment by gabriel-happle** [comment]
Simulation parameters of office room:
http://www.sciencedirect.com/science/article/pii/S037877880900293X

**Comment by gabriel-happle** [comment]
Fractions of Air-conditioned area for office, industry and residential:
http://www.sciencedirect.com/science/article/pii/S037877881630442X

**Comment by gabriel-happle** [comment]
Common properties of windows and facades in SG:
https://www.bca.gov.sg/greenmark/others/bldgplanningmassing.pdf

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA Yeah!
EcoCampus Block N3.2 Energy Simulation!
http://www.irbnet.de/daten/iconda/CIB_DC26318.pdf

**Comment by gabriel-happle** [comment]
Institutional building properties in SG:
http://www.sciencedirect.com/science/article/pii/S0378778815304552

**Comment by gabriel-happle** [comment]
SinBerBEST Benchmark building SG:
http://escholarship.org/uc/item/7k1796zv
