### ISSUE TITLE
EcoCampus: Create schedules for SG

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#520]
- OFFICE
- RETAIL
- RESTAURANT
- SCHOOL (for lecture hall)
- MULTI_RES (for student hall)
- LAB (new! from HVAC schedules)
- SERVERROOM
- GYM
- PARKING

Todo: check usages first.
Use SG standards or ASHRAE / SIA.
Verify with provided HVAC schedules.

**Comment by gabriel-happle** [comment]
LAB: 24hrs system operation, 7 days per week [EcoCampus Schedules]

**Comment by gabriel-happle** [comment]
NREL schedules:
http://www.nrel.gov/docs/fy11osti/46861.pdf

**Comment by shanshanhsieh** [comment]
Residential cooling load profiles at Emerald Hill, SG: P.186 (including weekdays and weekends)
Restaurant/pub; Office; Store; Yoga/Spa cooling load profiles at Boat Quay, SG: P.129

Bruelisauer, M., & Berthold, S. (2015). Recaiming Backlanes - Design Vision for Increasing Building Performance and Reprogramming Common Spaces. World Sciencitific.

**Comment by gabriel-happle** [comment]
I think we can close this for now with regards to our issue closing policy.
