### ISSUE TITLE
EcoCampus: Expand Occupancy DB to include Library

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#521]
Include Library Occupancy in DB.
Data from SIA2024.

**Comment by shanshanhsieh** [comment]
The library schedule from SIA2024 is added to the archetype schedule.
We might have to investigate the monthly variation (because the vacation periods are probably different....).
Action: check NTU calendar and confirm with ecocampus

**Comment by shanshanhsieh** [comment]
**1. Schedules**: Schedule information was extracted from SIA 2024:2015 4.3 Bibliothek 
Daily hot water use is not actually included in SIA 2024. This profile was assumed to be the same as the occupancy profile.

**2. Architecture properties**: Following the CEA documentation, a variety of sources were used.
2.1. type_shade: assume the same as `SCHOOL` 
2.2. win_wall: assume the same as `SCHOOL` 
2.3. occ_m2p: taken from SIA 2024:2015
2.4. n50: Weber et al. (2014) – same for all uses except homes
2.5. win_op: assumed 0.5 for all uses except homes
2.6. f_cros: European committee of standardization (2014) – used 0 for “all other uses” as defined in the source
2.7. type_roof, type_wall, type_win: assumed for CEA; for the new archetypes, the most common values were used (i.e., same as for schools and many others)

**3. Indoor comfort: ** The CEA database is also based on SIA 2024:2015 4.3 Bibliothek :
3.1. Tcs_set, Ths_set, Ve_lps: taken from SIA 2024 
3.2. Tcs_setback is not actually in SIA 2024. Assumed 28°C for all uses (as done in CEA database)
3.3. Ths_setback is not actually in SIA 2024. Assumed 12°C for all uses (as done for most uses in CEA database)

4. Internal loads: According to the CEA documentation, a variety of sources were used.
4.1. Qs_Wp, X_ghp, Ea_Wm2, El_Wm2: SIA 2024:2015 4.3 Bibliothek 
4.2. Vw, Vww: SIA 2024:2015 4.3 Bibliothek 
4.3. Epro_Wm2, Ere_Wm2, Ed_Wm2: 0

**5. HVAC**: Assume the same systems as in `SCHOOL`

**6. Thermal**: According to the CEA documentation, some values were taken from Girardin (2012), others from a combination of ECA, Gebäudeparkmodell and SIA 380/1 (no precise calculation given). So the following were assumed:
6.1. Es, Hs: 0.9 was used for all uses except homes, parking and server rooms; 0.9 was assumed for the new uses as well
6.2. Thermal mass: the same values were assumed for all buildings, so the same was done for the new uses
6.3. U_wall, U_roof, U_base, U_win: values for construction year >2005 and renovation were the same from all uses (from GPM), thus the same was assumed; for older buildings, the data from `SCHOOL` is used.


**7. Embodied energy and emissions**: According to CEA documentation, these values were taken from Thoma et al. (2014) except for services and excavation, which were taken from SIA 2032.
The same data for `SCHOOL` archetype is used.
