### ISSUE TITLE
Archetype DB for CH and SG: Decouple construction DB from occupancy DB

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#526]
Does it make sense that new occupancy types (i.e. schedules and internal loads) automatically require a new building type?
Maybe we can reduce the types of buildings and increase the types of occupancy at the same time.
E.g. INSTITUTIONAL architecture for MUSEUM, SCHOOL, LIBRARY, LABORATORY, etc. usages
E.g. COMMERCIAL architecture for OFFICE, RETAIL, RESTAURANT, etc.

The database would then just link architecture with occupancy.

see also #380

**Comment by JIMENOFONSECA** [comment]
So in discussion with Gabriel we decided the best way for the time being is to create an archetypes database for SIN similar to that of CH. that entails:

- simplyifying a bit the Achetypes_properties.xls/ARCHITECTURE taking out n50 and put it in in envelope_systems.xls/WINDOW. Taking out occ_m2p and put it in Achetypes_properties.xls/INTERNAL_LOADS

- Then we create the Archetypes_properties.xls for singapore starting with the occupancies available in Ecocampus and the years of construction of ecocampus (>1970s). then we expand this in the future.

- Then we create the Archetypes_schedules.xls with those of Sinberbest and NREL.

**Comment by martin-mosteiro** [comment]
Seems like a reasonable short-term solution to me. Longer term, I agree with @gabriel-happle that a sub-categorization would make more sense - something like what SIA 2024 does, e.g.:
1. Residential: 1.1. Multi-family, 1.2. Single-family
2. Hotel
3. Office
4. School: 4.1. Classroom; 4.3. Library; 4.5. Lab
5. Retail: 5.1. Supermarket; 5.2. General retail
etc.
