### ISSUE TITLE
EcoCampus: Create shapefiles of case study

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#528]
"Empty" shape files needed to run properties/demand script.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle  The best way is to prepare all the databases in excel to make a join with a shapefile with only the names of the buildings. i can do this.

To do this, please prepare 1 shapefile and three excel files:

shapefile 1: Just all the building geometries with only the field 'Name' in it.

excel file 1: Create an excel file with the column names of age.shp (be aware of upper/lower case). Fill it in if you have the data.

excel file 2: Create an excel file with the column names of occupancy.shp (be aware of upper case). Fill it in if you have the data.

excel file 3: Create an excel file with the column names of zone.shp (be aware of upper case). Fill it in if you have the data.

Attention, all excel files should have the same 'Name' column and the same name of buildings.

**Comment by gabriel-happle** [comment]
OK. I'll do that asap.
Do we want to consider "common space" as occupancy?

**Comment by JIMENOFONSECA** [comment]
maybe in architecture.shp? so during the calculation we discount that space from the occupancy...


On 9 Mar 2017, at 2:07 pm, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. I'll do that asap.
Do we want to consider "common space" as occupancy?

**Comment by gabriel-happle** [comment]
OK. So our total of the mixed usage will be smaller than 1?
i.e. OFFICE = GFA_OFFICE / GFA_TOTAL
Or we distribute the common spaces to the other usages and just consider it in Hs and Es?
i.e. OFFICE = GFA_OFFICE / (GFA_TOTAL - GFA_COMMON)

**Comment by JIMENOFONSECA** [comment]
I guess the second… what do you think?

On 9 Mar 2017, at 3:30 pm, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. So our total of the mixed usage will be smaller than 1?
i.e. OFFICE = GFA_OFFICE / GFA_TOTAL
Or we distribute the common spaces to the other usages and just consider it in Hs and Es?
i.e. OFFICE = GFA_OFFICE / (GFA_TOTAL - GFA_COMMON)

**Comment by gabriel-happle** [comment]
Yes. Probably. Otherwise we don't have any electric load in that areas (lighting, etc.)... Or we create the common space later.
I will prepare the files for the second one.
