### ISSUE TITLE
Fix shortcut for `tm_t0` and `tm_t1` in `CalcThermalLoads`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#53]
This is hardcoded for the swiss case study - we could fix this by adding a warm up phase.

**Comment by shanshanhsieh** [comment]
also for 'Tww_re', cold water return temperature of air conditioning system.

**Comment by gabriel-happle** [comment]
I'm going to check if there is something about that issue in ISO 13790 or SIA 2044

**Comment by gabriel-happle** [comment]
I found nothing helpful in the standards. I discussed with @JIMENOFONSECA and we decided to move the value to the globalvars, where we could have different calibrated values for different countries/regions.

**Comment by shanshanhsieh** [comment]
This is how energyplus tests the warmup convergence:
http://bigladdersoftware.com/epx/docs/8-0/engineering-reference/page-006.html

**Comment by gabriel-happle** [comment]
tested in branch #302 
no tm, ta, top jumps at beginning of heating season in all buildings in Zug case study
