### ISSUE TITLE
FAQ for CEA website

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#532]
The goal is to create FAQ for the user manual in the website:

Questions:
- what is 'PFloor'?
- ... add more

**Comment by daren-thomas** [comment]
more questions:
- how to create your own archetype?
- how to specify your own weatherfile?
- how to i create geometry for input?

**Comment by amraladdin** [comment]
Great input! Thanks guys!

**Comment by amraladdin** [comment]
@gabriel-happle @daren-thomas Do you guys agree that I close this issue and add your comments on issue #489 ... It's about the User manual updates...

**Comment by daren-thomas** [comment]
@amraladdin no, I don't agree. Why add the two together to create a mega-task? Instead, we should just complete this task and the other task.

**Comment by amraladdin** [comment]
SUMMARY FOR TOMORROW:
-------------------------------
I made a sample of the FAQ section and one of the questions (the weather file). Regarding the archetypes, I will work on it after the meeting, while point no. 3 (the geomerty) I will finish it with the help of Martin.
@gabriel-happle 's point regarding the definitions, I will work on that after the meeting as well :)

See you guys tomorrow!
