### ISSUE TITLE
Network hydraulic and thermal Losses

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#544]
Generate an interface in ArcGIS which calculates the network hydraulic and thermal losses if the network is provided

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi  it seems like this is a duplicate of #539 , can we close this?

**Comment by BhargavaKrishnaSreepathi** [comment]
sure
