### ISSUE TITLE
No module named shapefile

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#550]
Commit `2557c8e` from #547 includes the following line:
`import shapefile` (line 405 of thermal_loads.py)
This command requires pyshp! So the manual should be updated to include the installation of pyshp as a necessary step to use the CEA.
@JIMENOFONSECA

**Comment by JIMENOFONSECA** [comment]
@daren-thomas could you include this in the pip installation?

**Comment by daren-thomas** [comment]
actually, the pip installation does this. so does running either `python setup.py install` (which is basically what the pip installation does) or `python setup.py develop` (which lets you edit the source without needing to re-install) - they both include pyshp as a dependency.

Closing this as not relevant.
