### ISSUE TITLE
Fix broken build in master

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#556]
The master branch is currently broken wrt the jenkins. Fix this ASAP.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, @gabriel-happle  do you know why this error could be happening:

```
[...]
    outputs = func(*inputs)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\demand\occupancy_model.py", line 74, in calc_average
    return last + current * share_of_use
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

**Comment by JIMENOFONSECA** [comment]
I think, one of the fields in the occupancy.dbf is Null.
so this is what we know. when you create a new field let's call it 'LIBRARY' the content will look like a 0
but in reality is NULL. (a quite stupid thing arches has).

the way to solve it:
when on field 'LIBRARY' is added, you need to fill in the content with 0.
then you will visualise 0
and the content will be 0

Shanshan found this issue. I guess this is the point where we can start creating error messages to the user in CEA. could we add a class that handles some types of errors and get called when this happens?
________________________________

**Comment by daren-thomas** [comment]
It's not actually that easy (refering to "could we add a class that handles some types of errors and get called when this happens) - instead, you are supposed to check input and raise an error with an error message if the program can't recover from this error. I have updated the masterplan reference case (I found the bug yesterday too...) and also added a line 

```prop_occupancy_df.fillna(value=0.0, inplace=True)  # fix badly formatted occupancy file...```

to the code to avoid this specific error in the future. The PR #563 addresses this and also introduces a `cea test` command that will run the same script as the jenkins locally to test for errors before creating a pull request - and can of course also be used to debug a pull request that fails on the jenkins and you want to know why...

**Comment by JIMENOFONSECA** [comment]
I tend to feel this is an user error (he/she/it did not formatted the input file right). We probably should not be handling these type of error internally. I wonder if there could be many of this sort that just need a warning message to pop-up with the description of the error.


________________________________

**Comment by daren-thomas** [comment]
There are many, many, many ways to provide bad input! I think, when we discover these ways, we should through a `ValueError`:

> exception ValueError
> Raised when a built-in operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as IndexError.

In this specific case, though, `fillna` is not so bad, right?

**Comment by JIMENOFONSECA** [comment]
i have the impression that fillna could work in this case, but still we should create some error messages. At least it could give a hint of what is going wrong...
________________________________

**Comment by daren-thomas** [comment]
PR #563 builds!
