### ISSUE TITLE
Refactor / improve output in `demand.py`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#57]
weird copying of data to temporary files each a line and then summed up to the Totals CSV
- might want to refactor that...
- temporary files are written in `functions.py`
- the totals file is written at the end of `demand.py/analytical`

**Comment by JIMENOFONSECA** [comment]
the idea behind was that sometimes the user wants to just run a small selection of all the buildings but still get the Total.csv updated. for this we have to have as input layers instead of shapefiles. this can be done in the type of inputs in ArcGIS. But..! if we do it, we will be integrating the code more to ArcGIS.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, I think the basis for this might have changed? What is the current status on your comment above?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: Do we still want to do this? It might be a good idea to get rid of the temporary files as reading and writing files takes up computation time... The use case you mention at the top: Is that still a valid use case? And does the current code actually address this in a meaningful way?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas yes, let's get rid of them. The functionality was not required in the last experiments so i guess we can discard them and improve performance...

**Comment by daren-thomas** [comment]
I'm pushing this to the next milestone: It doesn't add new features and the temporary files are currently needed - I'd have to restructure some stuff to get rid of them. We don't have time for MS1.5...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still necessay?

**Comment by daren-thomas** [comment]
no. let's not bother.
