### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (8760,) (4984,) (8760,) 

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#570]
Connected to pydev debugger (build 171.3780.115)
PRE-PROCESSING + SINGLE BUILDING OPTIMIZATION
Solar features extraction
Run substation model for each building separately
Run decentralized model for buildings
Create distribution file with all buildings connected
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pydev\pydevd.py", line 1578, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 84, in <module>
    run_as_script(r'C:\reference-case-zug\baseline')
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 79, in run_as_script
    moo_optimization(locator=locator, weather_file= weather_file, gv=gv)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 50, in moo_optimization
    weather_file, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\preprocessing\preprocessing_main.py", line 78, in preproccessing
    summarize_network.network_main(locator, total_demand, building_names, gv, "all") #"_all" key for all buildings
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\master\summarize_network.py", line 81, in network_main
    Electr_netw_total += substations[iteration].Electr_array_all_flat.values
ValueError: operands could not be broadcast together with shapes (8760,) (4984,) (8760,)

**Comment by BhargavaKrishnaSreepathi** [comment]
This is an error I observe once in a while when I run optimization multiple times. This problem is solved when i replace the corresponding reference file in 'C:'. Have you encountered this error @JIMENOFONSECA @daren-thomas

**Comment by JIMENOFONSECA** [comment]
It means that somehow you are reading arrays that have (N = 8760 - 4984) cells with 'NULL' inside, Check the inputs. be sure you have run the demand first. a good way to debug is to know which building the model is checkin and see weather the inputs are the problem...

**Comment by BhargavaKrishnaSreepathi** [comment]
So here is how I get this error. 
1. I run the demand_main file once
2. After this i run the optimization_main file multiple times. It does not show any error 9 out of 10 times. But the 10th time it gives this error. 
3. The surprising part is it running the other times

**Comment by daren-thomas** [comment]
can you create a case? can you figure out the exact scenario being used, the input data as jimeno mentioned? then we figure out how the system got into this state.

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi is it solved?

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA : I have been trying to recreate the error for sometime now, but ironically, I am unable to get the error. I guess something happened which either solved the issue or may be if we face this error in future, I will save the state.

**Comment by JIMENOFONSECA** [comment]
ok, then let's close this issue
________________________________

**Comment by BhargavaKrishnaSreepathi** [comment]
Closing the issue as the error is not replicated

**Comment by BhargavaKrishnaSreepathi** [comment]
I got the same error again, thus reopening the error. I am saving the configuration i.e. the entire reference case folder such that we can reproduce the error

**Comment by BhargavaKrishnaSreepathi** [comment]
`Bau 14_result` present in `optimization -> substations` is changed and has only 4981 rows instead of 8760 rows. The files which come with the reference-case have all the rows. But it has been updated and the remaining rows are deleted. The result doesnt change even after running the `demand_main` file

**Comment by BhargavaKrishnaSreepathi** [comment]
After many runs, I figured out that while the substation results of each buildings are changed in `cea -> technologies -> substation.py`, if the run is abruptly stopped, all the values are not being saved to the corresponding csv file i.e in a run for 'Bau F', of the 8760 values calculated only a part of them are being stored to the csv file. This file when accessed the next time will give the Value Error as the rows are not 8760. 

This is based on the changing error statements I get. It is not always involving the same building, I observed this happening with 'Bau 14', 'Bau F'. Also the number of rows shown in the error `ValueError: operands could not be broadcast together with shapes (8760,) (4984,) (8760,)` also varies. I found values of (4981) and also (7520). My suspicion is on the abrupt stopping in the saving procedure.

@daren-thomas: Do you think that if pycharm is stopped amidst a run, the saving of the results done using `results.to_csv` will be affected? If so, will the file be created with partial values? Because I see the files being created.

**Comment by daren-thomas** [comment]
If you happen to stop exactly in the middle of writing a file, then of course this could end up corrupting data. Good catch! Where to go from here?

- add extra engineering to ensure that the program can pick up from such a hard shutdown
- don't abruptly kill the process? is that an option?
- make sure you don't read&write the same files in the same process (is this an option? it sounds like the same process overwrites files in a loop that are input files to the same process?)
- move the files away from the filesystem (csv) to a rdbms database (e.g. mysql) that supports transactions. that way you can ensure that either the whole file gets written or just a part of the file. this is similar to the first approach mentioned.

**Comment by BhargavaKrishnaSreepathi** [comment]
I am listing my thoughts on the above options:

1. **Don't abruptly kill the process? Is that an option? :** When we are running optimization for higher generations and we find an error in the results, we will kill the process to fix it. But this need not be abrupt, but rather we can kill it after it finishes the saving of the csv. I feel this is very tricky to do.

2. **make sure you don't read and write the same files in the same process :** This is being done currently, and it has its own pros/cons. Pros being that we will not be flooded with many csv files in this process. Cons being we might have a problem when abruptly shutdown

3. M**ove the files away from the filesystem to a rdbms database:** I personally like this idea, where we keep updating the values in a table provided with a timestamp. I am assuming this will be done locally on the computer. One con I see (not sure) is regarding the time involved in the transactions process. Will the computational time be a burden?

**Comment by daren-thomas** [comment]
Regarding 1. you could create a "sentinel" file, say "STOP" and have the software check for this file and shut down if found.

Regarding 2. say you found a csv file with the wrong dimensions (incomplete write at process termination) - is there a way to recover from there? what would recovery look like (ideally)?

Regarding 3. are you running the optimization locally? I thought you'd be using euler for this kind of work. hm. maybe you and i should sit down together sometime and look at the optimization stuff! reading and writing to a database takes time, of course. but maybe it doesn't really matter. especially if it means you can move the computation to a ton of cluster nodes...

**Comment by BhargavaKrishnaSreepathi** [comment]
1. No comments

2. Ideally, it should pick up the result of the previous configuration and proceed. Realistically though, it can recover from the default configuration which is shipped with the reference-case

3. For now, I am running optimization locally. I have not yet given Euler a try, but it is on my list and I will try to do it soon. But on larger picture, for small simulations, done, I think the database also should be present locally which will be continuously updated and it will be neater this way as one can see the mistake if any.

**Comment by BhargavaKrishnaSreepathi** [comment]
Based on a discussion with MUSES members here, it is wise to ship the reference-case folder with no files in the `baseline/outputs` folder. As far as the files regarding the substations (where all the buildings are connected, we are shipping this now in `baseline\outputs\data\optimization\substations`), we can shift this to inputs (as it is one of the input) and just import these files to the outputs folder. In case of data corruption, importing this way will not have any issues with the next run. @daren-thomas : any comments?

**Comment by daren-thomas** [comment]
that is a brilliant solution. so... in code somewhere you'll check the import of the outputs file and if it isn't up to snuff, you'll just failover to the inputs file? but... how are those inputs ever created?

**Comment by BhargavaKrishnaSreepathi** [comment]
I know about few other files present in `outputs` folder, but corresponding to the substations I am not sure. May be @JIMENOFONSECA can shed some light on how the substations files are generated when all are connected.

**Comment by JIMENOFONSECA** [comment]
In essence the optimisation_main.py has a subroutine called preprocessing.

during preprocessing. the solar radiation files, the network files are read. Also the substation routine is run considered that all buildings are connected.

The substation routine calculates the condition of flow from the side of the district heating network.

The substation routine is run overtime the network configuration changes (i.e. when buildings connected change). Why? because the temperature of the grid will depend on the highest temperature need of a customer. This is to account for building heating systems that operate at high temperatures (>80C) with new buildings that operate at 40C. In this way we account for a penalty in the losses of the network when we decide to connect a high temperature customer.


On 2 May 2017, at 9:56 am, BhargavaKrishnaSreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


I know about few other files present in outputs folder, but corresponding to the substations I am not sure. May be @JIMENOFONSECA<https://github.com/JIMENOFONSECA> can shed some light on how the substations files are generated when all are connected.

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA : There are few files which is being shipped along with the reference case present in `reference-case\baseline\outputs\data\optimization\substations`. Can these files instead be generated in CEA files?

**Comment by JIMENOFONSECA** [comment]
Yes!, they should in fact do not be shipped woth the reference case

Best, Jimeno

On 9 May 2017, at 08:49, BhargavaKrishnaSreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> : There are few files which is being shipped along with the reference case present in reference-case\baseline\outputs\data\optimization\substations. Can these files instead be generated in CEA files?

**Comment by BhargavaKrishnaSreepathi** [comment]
Can you tell me which file generates these files?

**Comment by JIMENOFONSECA** [comment]
Under the optimisation folder you will see the preprocessing.py which calls the substation_main.py file. This file gets the substation configuration fro the initial state (all buildings connected and the individual. You can track each one of the routines by doing right click in the function and go to declaration…



On 9 May 2017, at 9:15 am, BhargavaKrishnaSreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you tell me which file generates these files?

**Comment by BhargavaKrishnaSreepathi** [comment]
Aah. That piece of code is commented out. I now included it into the code and it is working now even after removing the files. This way it will work even if we hard shutdown the code and the data is corrupt. As it is recreating the files from scratch

**Comment by BhargavaKrishnaSreepathi** [comment]
solved in PR #631. Hence closing
