### ISSUE TITLE
Document sources for all variables

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CEAforArcGIS#58]
It could either be from standards or other references.

**Comment by daren-thomas** [comment]
so much this!!! :)

I tried to do as much as possible in the developer walkthrough. but of
course this needs to be fed back into the source code, as that will
ultimately be where the buck stops.

**Comment by JIMENOFONSECA** [comment]
Issue #138 is obstructing this @shanshanhsieh @daren-thomas. Equations and systems are likely to change throughout time. A manual way to do this is not durable. A no-standard way to do these things is neither.

**Comment by JIMENOFONSECA** [comment]
so much of this definitely. The information about equations can be found in the references and list of publications.
