### ISSUE TITLE
CEA seems to not be considering setbacks

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#585]
An error, difficult to track from the last improvement of the demand script. The cea is basically not using the setbacks anymore! @gabriel-happle coudl you help us to solve this issue? we need it for CISBAT..

From the picture one can see that the values assigned to th_set_C (what is selected from the controller) and theta_a (what gets into the RC model) are different for the time with setbacks!! el setback seleccionado aqui es de 5 C

![image](https://cloud.githubusercontent.com/assets/8973186/24611434/aba8e0a6-18b4-11e7-94ee-cfc203ac5529.png)

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I don't think there is an error. I never changed anything on how the temperature schedules are created. I attached one of the detailed reports that I recently created for the Zug Case study.
Check out `ta_cs_set`, `ta_hs_set` and `theta_a` in columns BV, BW and BX. Seems to work. For heating and for cooling.
[Bau H-2017-03-24-11-52-27.xlsx](https://github.com/architecture-building-systems/CEAforArcGIS/files/891861/Bau.H-2017-03-24-11-52-27.xlsx)

You can activate the detailed reports by `self.testing = True` in `globalvar`

The example you show looks to me as if you have a heating set point temperature of 5°C, but the building is actually 15°C. To me that makes sense, assuming capacity of thermal mass, outdoor air temperature higher than 5°C, etc. Maybe you can explain to me what you are exactly referring to.

By checking out other buildings, it seems that only certain functions have setbacks. I.e., the industrial type buildings in Zug don't have setbacks, the office buildings have. But I don't know how exactly it is supposed to be. Maybe you remember?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA There might be an issue where buildings are overheating during periods with a cooling set point. This is due to the rule that cooling systems are generally deactivated when the outdoor temperature is colder than the indoor temperature. Should we deactivate this rule?

def is_active_cooling_system(bpr, tsd, t):

    # check for cooling system in building
    # check for cooling season
    # check for cooling demand
    if helpers.is_coolingseason_hoy(t) \
            and has_cooling_system(bpr) \
            and tsd['T_ext'][t] >= tsd['ta_cs_set'][t] \
            and rc_model_SIA.has_cooling_demand(bpr, tsd, t):

        return True
    else:
        return False

**Comment by JIMENOFONSECA** [comment]
I believe if this is maintained we could compute the thermal comfort (i.e. hours outside of the setpoint and humidity levels). so, are the setback points influencing still the results in your opinon @gabriel-happle

**Comment by gabriel-happle** [comment]
I'm closing this @JIMENOFONSECA. OK?

**Comment by JIMENOFONSECA** [comment]
yes!
________________________________

**Comment by martin-mosteiro** [comment]
Sorry, what was the conclusion on this issue?
