### ISSUE TITLE
Ventilation control and energy bug fixes for CISBAT release

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#587]
After a meeting with @JIMENOFONSECA today we decided to quickly implement the following bug fixes in the ventilation calculation of the demand part for the CEA version we like to use for CISBAT.

a) Auxiliary electricity demand for all mechanical ventilation (not only AC) 
b) Bug fix in mechanical ventilation control
c) Bypass of HEX during cooling season, if outdoor conditions are favorable (kind of economizer)

This will most likely affect the results a bit.
@daren-thomas The goal is to create a pull request ASAP and release a CEA version we all can reference in our CISBAT papers.

**Comment by daren-thomas** [comment]
@gabriel-happle can this be closed?

**Comment by JIMENOFONSECA** [comment]
Yes!

Best, Jimeno

On 19 Apr 2017, at 20:14, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@gabriel-happle<https://github.com/gabriel-happle> can this be closed?
