### ISSUE TITLE
Use csv reader/writer instead of Pickle?

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#589]
I have been doing some digging on this and have found this reference.
http://tungwaiyip.info/blog/2010/05/12/python_csv_reader_is_much_faster_than_pickle 

It turns out csv reader/writer is faster than pickle, but the catch here is the format of the data will be all converted to string, which we then need to reconvert when we are using them again

**Comment by daren-thomas** [comment]
@BhargavaKrishnaSreepathi where do you want to apply this to?

**Comment by BhargavaKrishnaSreepathi** [comment]
saving the files in optimization, especially in master_main and further on in the plots

**Comment by daren-thomas** [comment]
Do you have data to support the change? Have you run a profiler and does it show that the saving of the files in `master_main` with `pickle` is a bottleneck? I'm asking, because I somehow doubt that this will lead to any improvement in the run time, but, I have not run a profiler myself and therefore don't know.

**Comment by BhargavaKrishnaSreepathi** [comment]
I have neither runt he profiler nor found that this was the bottleneck. I actually was trying to under the results obtained from optimization and found that the 'pickled' files are difficult to understand from naked eye and so tried 'csv reader/writer' which were quite helpful in directly relating the results. This is important as we can see the results in between generations without stopping the runs and figure out the mistakes (if any). But it had its own drawbacks as I listed above.

When me and @JIMENOFONSECA  were discussing about this, the issue of scalability has come up. And that was the reason I created this issue, with a lower priority.
For now I am providing an option which defaultly saves in pickle files, but when turned on, will save as both pickle and csv files.

**Comment by daren-thomas** [comment]
The reason why I'm interested in this topic is that it adds complexity. Complexity is not bad per se - it just needs to be justified. Options are often just what happens, when we don't take time to design.

I remember using a pickle file for the sensitivity analysis and in that case, the data being saved was not in table data format - it was a dictionary and `pickle` was a really easy way to save that to disk. If the file should have been readable and editable by hand, I would have used JSON for that case.

What kind of data are you pickling in the optimization? Dataframes?

**Comment by daren-thomas** [comment]
I suggest deciding on one format (CSV or pickle) and sticking with that. Readability counts (from the python zen) and The Art of Unix Programming also prefers text-based formats over opaque binary formats (such as the pickle provides). Depending on what kind of data you want to save, CSV or JSON could really be a better answer.

**Comment by BhargavaKrishnaSreepathi** [comment]
They are not Dataframes as all are of varying sizes. Optimization saves lists of varying sizes. One suggestion was to save each of them as pandas.dataframes and then save as csv files. This will give many files for the same generation, which might not be bad per se.

**Comment by daren-thomas** [comment]
JSON is really good at saving lists of varying sizes. This sounds like the tool to use for me - it would allow you to read it in an editor, but is just as easy to read/write as pickle. In fact, I believe the change would be minimal.

**Comment by BhargavaKrishnaSreepathi** [comment]
ok. Let me take a look at it and then implement it.

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas : it is really easy and good. I am implementing it in my branch. Thanks

**Comment by BhargavaKrishnaSreepathi** [comment]
Closing this issues as it is addressed in PR572. The files are now being saved as json files
