### ISSUE TITLE
Update "File histroy and credits" for all python files

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CEAforArcGIS#59]

**Comment by daren-thomas** [comment]
please let us not do this!!! we have github that can tell *exactly* what
changes where made to each file, when, and by whom. adding  this
(redundant) information to the file header just increases bureaucracy.

**Comment by shanshanhsieh** [comment]
sounds reasonable to me if github already documents every thing, shall i just close the issue?

**Comment by JIMENOFONSECA** [comment]
The question to me, is if both old and new modules will be correctly credited to their authors. It seems that the one who uploads the script gets the credit but nor the contributors. for instance: the work of Thuy-an, Tim, Florian for the Supply side etc.. which will be uploaded by us next....

**Comment by daren-thomas** [comment]
yes, please close the issue. instead, i'll create a new issue to add a
license header to all the files.

**Comment by JIMENOFONSECA** [comment]
not yet :-)))

**Comment by daren-thomas** [comment]
good point, jimeno. yes, I guess we therefore need to add a credits
section. can we please keep this as simple as possible? (I have seen it go
overboard in other projects with a detailed changelog for each edit)

do i understand you correctly: your main concern is to make sure every
contributor gets credit for their work on each file. so, a name, scope of
contribution and year would suffice?

**Comment by JIMENOFONSECA** [comment]
Surely it should suffice. and i believe it should be carried out function wise (at leas the big ones).
I saw it first in some scripts in TRnsys. I saw who developed in the 1990's, I then went to his article I got to contact the author for some doubts. He was super happy to see how his work still contributes to R&D after 25 years!.

It also helps to keep track once somebody takes the functions to another script. then we know who was responsible.

**Comment by daren-thomas** [comment]
ok. so then let us do it like that!
we add a section at the top for contributors and include information about
what functionality was added?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA Have a look at the core modules. I have added `__credits__` and other variables at the top of the files. We can also add these on a function basis for functions that involve calculations.

I have added myself as `__maintainer__` as I expect to be the person fixing bugs for the next twenty years. This is open for negotiation ;-)

I vote to close this bug.

**Comment by JIMENOFONSECA** [comment]
Cool great job!  :-)
