### ISSUE TITLE
User Manual modifications - Squarespace

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CEAforArcGIS#591]
Here are the points that have taken more time than expected to be finished in the CEA website, due to:
- Length of the data transfer process. Markdown in GitHub is different from the one in Squarespace.
- Some of the points (e.g. DBF reader) require someone with expertise on the topic to input the data.

Below are the remaining points to be tackled:
- How to create your own archetype?
- Finish the transfer of inputs and outputs to squarespace (e.g. PFloor... etc.)
- While presenting the process of running a quick simulation it would be great to know: Where and what are the data being created?
- In the 'Get Started' page, we are not providing any details about DBF reader, so should it be mentioned? It is in the first paragraph of the page. (@gabriel-happle  any idea who can assist on this point?)

**Comment by gabriel-happle** [comment]
@amraladdin Hi, I don't know if anyone else is using a dbf editor. I started to use it because I'm not too familiar with ArcGIS and it seemed a bit too much to use ArcGIS to just change one value in a shapefile for testing purposes. That is why I downloaded this little open source tool: https://sourceforge.net/projects/gtkdbfeditor/?source=typ_redirect
It looks like this and works fine. You simply directly open the file with *.dbf extension, modify values and save.
![image](https://cloud.githubusercontent.com/assets/17002288/24890974/7c566b1a-1ea5-11e7-995b-815c2713de98.png)
![image](https://cloud.githubusercontent.com/assets/17002288/24890983/93d18626-1ea5-11e7-8094-e38abb23dda9.png)

**Comment by JIMENOFONSECA** [comment]
@amraladdin what is the DBF reader about? you can read edit and create DBF from arcgis or even excel...

**Comment by JIMENOFONSECA** [comment]
@amraladdin there is no need to transfer one to one the content of gitbook. Now that we agreed to use Google presentations, you need to create a presentation about it. which allows you to include, normal tables, images, text, whatever...

**Comment by amraladdin** [comment]
@JIMENOFONSECA the DBF reader was one of the questions that @BhargavaKrishnaSreepathi asked to include in the user manual. As I mentioned before, I'm not familiar with it, so I was asking for support. Martin told me a couple of days ago that he could show me how it can be edited from ArcGIS.

Regarding the presentations: Oh Ok, I thought we will be working on both, the website + presentations. Sorry for misunderstanding... Then perhaps we can make this meeting we talked about to discuss about the presentations?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Are you sure you can edit DBF on Excel? My version of Excel (2013) can't open DBF. OpenOffice _does_ work... but then it messes up the column names, so it doesn't work.

Editing on ArcGIS works, as I mentioned to @amraladdin a few days ago. However, I wasn't able to delete records using ArcGIS - i.e., I could edit the values, but I couldn't delete buildings. Plus, I don't think you can rename columns on ArcGIS, can you?

So what usually happens is I end up using our dbfreader script instead...

**Comment by gabriel-happle** [comment]
@martin-mosteiro @JIMENOFONSECA @amraladdin 
- You can not edit DBF with Excel.
- You can not rename columns in ArcGIS. (but with the ET GeoWizard plugin you can ;) http://www.ian-ko.com/)

**Comment by amraladdin** [comment]
I believe this issue was fixed with the new FAQ presentations... @JIMENOFONSECA wouldn't you agree?
