### ISSUE TITLE
[gitbook] unit for ventilation rate per person

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/CEAforArcGIS#592]
In the gitbook, the ventilation rate is reported as litres per person per second
https://architecture-building-systems.gitbooks.io/cea-toolbox-for-arcgis-manual/content/building_properties.html

Should the unit not be l/p/s, as opposed to l.p.s

**Comment by JIMENOFONSECA** [comment]
Well noted!. it is just a matter of notation common in water systems. and actually it is not l.p.s., not l/p/s but lps
an example:

https://books.google.com.sg/books?id=lXcS8vH4ThcC&pg=PA199&lpg=PA199&dq=water+consumption+l.p.s&source=bl&ots=eFJZxkVH0_&sig=wDNnOSpHFDDEDr130Bh3tBdkADk&hl=en&sa=X&ved=0ahUKEwjw0KTNhJ7TAhUKPY8KHRU-D-kQ6AEIJzAF#v=onepage&q=water%20consumption%20l.p.s&f=false

@daren-thomas i could not access the gitbook anymore, anychance to implement the change?

**Comment by JIMENOFONSECA** [comment]
done
