### ISSUE TITLE
Organize cea/tests folder structure and documenting

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#598]
Daren gave us a great presentation about Tests in CEA. It would be great to complement this with some small documentation to the existing Test_ scripts. This will facilitate its further use and modification. THis entails

1. creating a subfolder structure for integration tests and unittests
2. labeling the script what creates the integration test data and what runs the test
3. adding a few lines on top of the integration test saying what it is and what data needs to be changed in case the output change.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas would you mind taking a look at this?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA you're fast! sure. I'll take care of this.

**Comment by daren-thomas** [comment]
Also document the jenkins setup, including the `ceajenkins.py` file (add it to the repository and create an installation guide) this might be a separate issue.

**Comment by daren-thomas** [comment]
Also update `cea test` to default to the `--reference-case only` option to speed up testing!

**Comment by daren-thomas** [comment]
pull request #696 addresses this issue
