### ISSUE TITLE
Shading_type, shading_position, window_to_wall_ratio - are set to a constant value 

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#6]
We should probably update the archetypes to include these variables. Today they are part of the user's input, and window-to-wall-ratio is considered fixed

**Comment by JIMENOFONSECA** [comment]
It requires chanches in -	q['fwindow'] = gv.window_to_wall_ratio in demand.py
once the window to wall ratio be included in the archetypes

**Comment by shanshanhsieh** [comment]
Uwall and Uwindows are now assigned according to archetypes. Should have the flexibility to change via user's input as a design parameter.

**Comment by JIMENOFONSECA** [comment]
not excatly, they can be extracted from  archetypes at first, but once in the properties file, the user can change them directly in the excel file
