### ISSUE TITLE
README.rst should explain what the CEA is (elevator pitch)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#608]
Currently it just says "this is the repository of..." which is not a good thing to say in this document because

1. if someone is looking at it in GitHub, well, then they already know it's a repository
2. this text is copied to PyPI as the description of the package

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can we change this?

**Comment by JIMENOFONSECA** [comment]
done!
