### ISSUE TITLE
IOError: [Errno 2] originating in NUS_weather.py file

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#609]
The full error is 

IOError: [Errno 2] No such file or directory: 'C:/Users/Bhargava/Desktop/Weather-Data/2005/W_20050102.xlsx'

This arises as it is hard coded in the file to access the weather files provided by NUS. This file is not necessary to be present in the CEA- master folder. Although I would have this file stored somewhere for future reference.

Do give your comments on a method to save these files @daren-thomas @JIMENOFONSECA . If the contributions -> legacy  folder is terminated for some reason, we can save these files in dropbox or on our server

**Comment by daren-thomas** [comment]
I like the idea of keeping the code that was used to create the data. How about... we add a folder `notebooks` that contain jupyter (ipython) notebooks for generating data etc. and use literate programming (documentation interspersed with the code) to describe this kind of data generation script.

The documentation should answer at least following questions:

- what is being done
- why it needs to be done
- any required stuff to get it running...

The source data file that caused the error in this isssue to arise should be part of the repository and not a local file on your pc. That way, the code is reproducible.

Reproducible research could also be done by moving the nus weather file and code to create it to a repository dedicated to that study...

**Comment by BhargavaKrishnaSreepathi** [comment]
I like the idea of `notebooks`. The data size is also not big for the current scenario, so should not be an issue for uploading. But it has numerous files (52 files).

**Comment by daren-thomas** [comment]
what about creating a subdirectory in `notebooks` with the same name as the `.ipynb` file and store the additional data there? this of course depends on you being allowed to publish this data. Otherwise, the `.ipynb` file can include a markdown section at the top detailing how to obtain the data required.

**Comment by BhargavaKrishnaSreepathi** [comment]
Closing the issue as the error is resolved. The creation of `notebook` is discussed in another issue
