### ISSUE TITLE
Provide a guide to show which python scripts generate the result files

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#613]
The guide should show the python file which corresponds to the saved file and where the file is going to be saved.

For example, `master_main.py` saves the results of optimization which include population, fitness, generation, network, tested pop for each generation in the format of `CheckPoint_` + generation number. This is being stored in the `get_optimization_checkpoint()` folder

**Comment by daren-thomas** [comment]
If all file locations are read and written through the `InputLocator` then this becomes easy - just check for the calls. It can even be automated...

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas : I am modifying the code to read and write the files through `InputLocator`. Can you refer me to the readings to do this process (of writing a guide) automatedly

**Comment by daren-thomas** [comment]
@BhargavaKrishnaSreepathi : check out `bin/extract_inputlocator_calls.ipynb` I think that does exactly this. BTW: while you're at it, you could move it to `notebook` and update it with the header template :)

**Comment by BhargavaKrishnaSreepathi** [comment]
Closing the issue as the PR is accepted
