### ISSUE TITLE
Doubt regarding the weather file use in cea test command

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#620]
I found that `cea test` command from the prompt is successful when the weather file is `Zug`. The command failed when the weather file is `Zug-2010` and `Singapore-2016`.

@daren-thomas are the test results corresponding to `Zug` weather file?
@JIMENOFONSECA any comments on this?

**Comment by JIMENOFONSECA** [comment]
Yes they are...

Best, Jimeno

On 26 Apr 2017, at 14:19, BhargavaKrishnaSreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


I found that cea test command from the prompt is successful when the weather file is Zug. The command failed when the weather file is Zug-2010 and Singapore-2016.

@daren-thomas<https://github.com/daren-thomas> are the test results corresponding to Zug weather file?
@JIMENOFONSECA<https://github.com/JIMENOFONSECA> any comments on this?

**Comment by BhargavaKrishnaSreepathi** [comment]
Aah. Ok Ok. May be in future we need to get results for other weather files and add to the test cases I guess.
