### ISSUE TITLE
'No module named decorators' error after installing cea with pandas version 0.20.0

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#628]
'No module named decorators' error after installing cea with pandas version 0.20.0

Do this: copy `C:\users\Gabriel\Anaconda2\envs\cea\pkgs\proj4-4.9.3-vc9_3\proj.dll` to `C:\users\Gabriel\Anaconda2\envs\cea\Library\bin` and make sure the second folder is in your system environment (restart pycharm) then it should work!

![pasted image at 2017_05_05 03_22 pm](https://cloud.githubusercontent.com/assets/17002288/25741881/670616b6-31bf-11e7-9259-dd2d81e4402a.png)

**Comment by daren-thomas** [comment]
wait. that's a different error than the one we were talking about before... so you upgraded to pandas version 0.20.0? I'll look into that.

**Comment by daren-thomas** [comment]
@gabriel-happle check out PR #629 for an update to the installation guide - for now, we need to force pandas to be < 0.20.

You might need to re-create the environment, but first check to see if `conda install "pandas<0.20"` will do the trick (don't forget the quotes) - that should downgrade pandas for you :)

**Comment by daren-thomas** [comment]
@gabriel-happle did PR #629 help? it does on my machine...

**Comment by gabriel-happle** [comment]
@daren-thomas I actually didn't try. I used `conda update pandas`, which installed pandas 0.19.2.
I get two warnings, but no errors.

WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set

**Comment by gabriel-happle** [comment]
@daren-thomas Should I try set up a new environment with the new guide?

**Comment by daren-thomas** [comment]
yes, please do.
