### ISSUE TITLE
ArcGIS interface for Solar Potential Calculation

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#633]
would @shanshanhsieh and @daren-thomas mind taking care of this?

**Comment by daren-thomas** [comment]
@shanshanhsieh maybe we can skype next week?

**Comment by shanshanhsieh** [comment]
@daren-thomas yes, how about this thursday?
Do you see this being finished in `Sprint May`?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh i think this is the interface we meant for the solar potential that can be created

**Comment by daren-thomas** [comment]
I definitely think it could be! where do i find the solar potential calculation? I couldn't find an open pull request...

**Comment by shanshanhsieh** [comment]
This issue can be implemented after #636 is finished.

Here are requirements of the interfact:

- *Input from users*: 
1. Grid size
2. Solar technology selection
3. Add technology specifications (optional)
- *Output to visualize*: energy generation potential from the selected technologies of each building or on each building surfaces.
- *Background processes*:
1. Run `radiation_main.py` (with the grid size input)
2. Change solar technology specifications 
3. Run solar technology scripts (`photovoltaic.py` `photovoltaic_thermal.py` `solar_collector.py`)
4. Visualize results on ArcGIS

**Comment by shanshanhsieh** [comment]
hey @daren-thomas , please take a look at branch i633, where I wrote the guide on how to run photovoltaic.py in docs/run_solar_technologies.rst- User input (the choice from the interface)
- Site specific input (draw the data according to the coordinate system, maybe we have to make new functions to automate the process? e.g. extract the first hour of sunrise at solstice)
- Default input (keep the constants)

**Comment by daren-thomas** [comment]
@shanshanhsieh check out the branch: it now includes an arcgis tool for the photovoltaic use case. is this what you had in mind? then i can implement the rest...

use `cea install-toolbox` to update the toolbox in arcgis (you don't need to restart arcscene, just refresh the toolbox in the interface)

**Comment by shanshanhsieh** [comment]
hey @daren-thomas , thanks for the update. what is the name of the arcgis gui for photovoltaic use? i can only see a box called `radiation` in the branch.

**Comment by daren-thomas** [comment]
hey @shanshanhsieh - did you run the `cea install-toolbox` command? That is what copies the `CityEnergyAnalyst.py` file to the "My Toolboxes" folder for ArcGIS to pick up. Also, you will need to refresh the toolbox in ArcGIS. Run this after every change to the interfaces...

I just checked the branch `i633-Interface-for-solar-potential`. The interface is there!

![image](https://user-images.githubusercontent.com/2969564/27070733-7d844b8c-501a-11e7-9bed-032895af5f84.png)

**Comment by shanshanhsieh** [comment]
hey @daren-thomas , i tried multiple times `cea install-toolbox` (including delete everything and re-run the command), but no luck. any other potential issues?
but i can see the class you created for `Photovoltaic` in `CityEnergyAnalyst.py` in pycharm (I also just made some modifications)

**Comment by daren-thomas** [comment]
check with the command `where cea` - it should point to the version inside your conda environment. you probably have it installed in multiple environments and have created a mess...

**Comment by daren-thomas** [comment]
@shanshanhsieh the pull request was merged... does that mean we can close the issue?

**Comment by shanshanhsieh** [comment]
@daren-thomas yes, closing the issue now : )
