### ISSUE TITLE
Switch between infiltration models

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#645]
The Demand script should offer the possibility to switch bettween ventilation models. 
for this. the interface to Arcgis should provide a list or a tick box indicating which infiltration model to use:

Model A. Simple steady-state
Model B. Dynamic

This will avoid commenting, commenting lines of code once one or the other models is going to be used. I would like to have this functionality to run some sensitivity analysis..

@daren-thomas @gabriel-happle I hope it is ok if I assign this issue to you. do you think it can be done for this sprint? if not please feel free to asign it to Singapore milestone

**Comment by daren-thomas** [comment]
See also #641 for a related issue

**Comment by gabriel-happle** [comment]
duplicate of #465

**Comment by gabriel-happle** [comment]
@daren-thomas let's talk about this and #251 on Friday 02/06? Can you do from 9:00-10:00?

**Comment by daren-thomas** [comment]
working on this in the branch `645-switch-between-infiltration-models`

**Comment by daren-thomas** [comment]
implemented in PR #674

**Comment by gabriel-happle** [comment]
closing this issue!
Yeah! Milestone achieved in time!
Thanks @daren-thomas
