### ISSUE TITLE
Radiation not working for Zurich case

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#648]
There is a memory error, it might have to do with the size of the case study, specially the district. we will check this into the code.

@chenkianwee is there a way to limit the resolution of the district.shp (context buildings) to a wider sensor grid, but keep that one of the Zone.shp smaller?

**Comment by chenkianwee** [comment]
Hi Jimeno, memory from where? From PythonOCC? It is definitely possible to vary the resolution.

**Comment by chenkianwee** [comment]
140 mb is ok I think in terms of geometry, but I have not run a solar simulation on such a big file before.  Ya sure, 4pm today ?

**Comment by JIMENOFONSECA** [comment]
sure, see you here!

Jimeno
________________________________

**Comment by JIMENOFONSECA** [comment]
I get this: Process finished with exit code -1073741819 (0xC0000005)

And it is happening when the next text is printed:

('Error status:', '- Ok')
('Can work?', True)
('Error status:', '- Ok')
('Can work?', True)
('Error status:', '- Ok')
('Can work?', True)
('Error status:', '- Ok')
('Can work?', True)
('Error status:', '- Ok')
('Can work?', True)
('Error status:', '- Ok')
('Can work?', True)
('Error status:', '- Ok')
('Can work?', True)
('Error status:', '- Ok')

In addition i opend  the cityGML file and it shows nothing. so there might be an error on how the file itself is being created right? @chenkianwee

**Comment by chenkianwee** [comment]
hmnnn Jimeno I am not sure what is happening. I need to look at the error in detail.

**Comment by JIMENOFONSECA** [comment]
i got the same error again :-((

**Comment by JIMENOFONSECA** [comment]
@chenkianwee so this is the profiler of the City GML creator create_gml.py file. Which is quite slow for several buildings. the bottle neck is definitely creating building windows and the intersect_shape_with_pt function... 50% of all the time!

![diagram](https://cloud.githubusercontent.com/assets/8973186/26234494/930b8060-3c97-11e7-8cd4-4115b529d36e.png)

**Comment by JIMENOFONSECA** [comment]
so i was able to correct that function and the bottle neck now is  th emake shell:
![diagram](https://cloud.githubusercontent.com/assets/8973186/26235394/6cf15c78-3c9d-11e7-9667-827ccd8e8df7.png)

**Comment by JIMENOFONSECA** [comment]
Ok the radiation script is working for the Zurich case, however it is quite slow. I think it needs some parallel computing. It did my best in refactoring but i will need an expert to jump in :-) @daren-thomas would you mind to giving me a hand on this? Here is a run of the Profiler.

![diagram2](https://cloud.githubusercontent.com/assets/8973186/26236638/f53a99e0-3ca3-11e7-80e2-9fed114d2fa2.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I've added it to my list, but for this sprint, I don't think I have time for improving speed - we can do that afterwards, as long as it runs!
