### ISSUE TITLE
fix preprocessing_main to include decentralized_main to avoid shipping of files with reference case

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#649]
Activating `decentralized_main` to generate 'DiscOP_buildingname_result' files

**Comment by BhargavaKrishnaSreepathi** [comment]
Hi @JIMENOFONSECA , this is the error I am facing, when I run the `optimization_main.py` in branch `i649-decentralized-buildings-preprocessing`. Please help me out . Thanks

  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 84, in <module>
Run decentralized model for buildings
    run_as_script(r'C:\reference-case-zug\baseline')
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 79, in run_as_script
    moo_optimization(locator=locator, weather_file= weather_file, gv=gv)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 50, in moo_optimization
    weather_file, gv)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\preprocessing\preprocessing_main.py", line 75, in preproccessing
    decentralized_buildings.decentralized_main(locator, building_names, gv)
AttributeError: 'module' object has no attribute 'decentralized_main'

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA : a follow up question. After running the `decentralized_buildings.py`, there are files generated corresponding to the number of buildings, but each file has 14 rows, 1 row corresponding to header and 13 (i don't know). The number 13 is hard coded in the code and no explanation is provided for why it is chosen as 13. It says at the start it is a combinatorial problem. Can you give your insights on this.

**Comment by JIMENOFONSECA** [comment]
So this is something we need to "decipher" form the code. but in essence, it is making a ranking of the best solution out of combining all possible supply systems for decentralized buildings. Such algorithm should be translated into a MILP formulation which could be a great point to get this skills of your on board ; ). I advice to look at that issue and update the decentralized buildings script. Which should be an optimization at the building scale of conversion technologies.

________________________________
