### ISSUE TITLE
Move vent control to ventilation?

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#655]
I wonder if the tab of ventilation control can be moved to that of ventilation and simplify the inputs. to only type_vent @gabriel-happle what do you think? I would need to check this for the issue #643 . we could sit down and check it also how we can rework it.

![image](https://cloud.githubusercontent.com/assets/8973186/26344269/96928bd8-3fd1-11e7-990c-2a8c2bee000f.png)

![image](https://cloud.githubusercontent.com/assets/8973186/26344282/a15cfcc4-3fd1-11e7-8f3f-edb8ed437014.png)

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA `type_ctrl` is not the control of ventilation. It's the control of the heating and cooling space emission systems used to calculate emission losses.
