### ISSUE TITLE
FAQ: How do the Life Cycle Assessment tool work?

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#657]
Esta se relaciona a los scripts the embodied, operation and mobility emissions
Un ejemplo de otra guia esta aqui: https://cityenergyanalyst.com/faq/

The guides can be created with access to the server and using google presentation ask me for the credentials

**Comment by martin-mosteiro** [comment]
Done. Need access to the server to upload them, though.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro could you provide me with a gmail account?
