### ISSUE TITLE
FAQ: How do the 2000-Watt Benchmarking tool work?

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#658]
This is related to the scenario plots or 200-watt benchmarking
Un ejemplo de otra guia esta aqui: https://cityenergyanalyst.com/faq/

The guides can be created with access to the server and using google presentation ask me for the credentials

**Comment by martin-mosteiro** [comment]
Done. Need access to the server to upload them, though. @JIMENOFONSECA

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro great!, would you provide me with a gmail account?
