### ISSUE TITLE
Life Cycle Assessment tools inconsistently named

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#663]
While doing the LCA FAQ (#657) I noticed that the LCA tools in the ArcScene toolbox could be named much more intuitively. At the moment, we have:

- **Embodied energy:** calculates the embodied primary energy demand and emissions
- **Emissions operation:** calculates the operation primary energy demand and emissions
- **Emissions mobility:** calculates the mobility primary energy demand and emissions

These should all have more similar names since they have similar purposes. Perhaps "Emissions embodied/operation/mobility" or "LCA embodied/operation/mobility".

Even better, maybe these three could be combined into a single tool (called, for example "Life Cycle Assessment") where you can check a box if you want the embodied, operation and mobility results to be generated (just like how right now you can select whether you want separate files to be generated for the emissions from heating, cooling, etc.)

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro I agree, Maybe we can create a sub folder inside the ArcGIS CEA toolbox. As well as in pycharm.

It can be something like:

/City Energy analyst Toolbox
//Demand
//Data Helper
// ....
//......
// Life Cycle Assessment
///construction and dismantling
///operation
///mobility

@martin-mosteiro woudl you work on it in a branch and ask @daren-thomas for help when wanting to do this subfolder in the ArcGIS toolbox?

@daren-thomas it think it is good we start doing subfolders (called toolsets in Arcgis) inside the CEA Arcgis toolbox, I expect the new scripts and tools to be organized into these toolsets.

An example of other toolboxes in arcgis that use subfolders (toolsets) is here:

![image](https://cloud.githubusercontent.com/assets/8973186/26612475/a26673c2-45e7-11e7-8515-e5afb958571d.png)

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA can! I've assigned this issue to myself.
@daren-thomas: can we create such a subfolder structure?
