### ISSUE TITLE
Understanding the substation.py and the doubts in its formulation

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CEAforArcGIS#667]
So to calculate the best configuration for a decentralized buildings, as per my understanding the following procedure is followed. @shanshanhsieh @JIMENOFONSECA: Do correct me if my understanding is wrong.

1. Firstly, the supply temperature for space heating, hot water, space cooling through grid are determined. This is calculated by seeing every hour of the year and the maximum requirement temperature for all buildings put together is chosen and 'DeltaT' is added/subtracted accordingly. This becomes the DHS_supply or DCS_supply.

2. These values are then used to calculate the Q_heating, Q_dhw, Q_cool for each building.

3. This is then fed to the `decentralized_buildings.py` where 13 combinations of heating systems are used to calculate the costs, co2 emissions, primary energy. This file only does for heating loads. What happens to cooling?

Another question being, why are we using the supply temperature as the maximum temperature needed at a particular hour for all buildings, even though it is a decentralized building? Should it not be maximum for that single building?

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi all points are right.

About your question. I think that is not/should not be the case. 

As discussed about two weeks ago. Would you mind to start doing a detailed workflow diagram of the optimization process so it is easier to understand and improve the current algorithm? This includes when the master and slave are called, when a network is set-up and when the seasonal storage is calculated etc...

you will have tons of tools to do this example:
![image](https://cloud.githubusercontent.com/assets/8973186/26707194/9c619990-4775-11e7-92e0-9c88cd386180.png)

**Comment by BhargavaKrishnaSreepathi** [comment]
closing as it is understood with the CEA/optimization work flow diagram
