### ISSUE TITLE
Hs in the building archetypes

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#687]
SINGLE_RES buildings built renovated after 2006 lave a _larger_ heated floor area (Hs=0.9) than any other SINGLE_RES buildings (Hs=0.85 regardless of construction or renovation year). @JIMENOFONSECA is there any reason for this? Seems counter intuitive.

Similarly, SERVERROOM's renovated after 2006 have Hs=0.9 whereas any other building or renovation year has Hs=1.

**Comment by JIMENOFONSECA** [comment]
I recall taking these values from SIA 380/1 but i might be wrong. Let me know of there is any other source.

For servers it should be 1 i guess

Best, Jimeno

On 20 Jun 2017, at 18:30, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


SINGLE_RES buildings built renovated after 2006 lave a larger heated floor area (Hs=0.9) than any other SINGLE_RES buildings (Hs=0.85 regardless of construction or renovation year). @JIMENOFONSECA<https://github.com/jimenofonseca> is there any reason for this? Seems counter intuitive.

Similarly, SERVERROOM's renovated after 2006 have Hs=0.9 whereas any other building or renovation year has Hs=1.
