### ISSUE TITLE
Application of archetypes to generate architecture properties doesn't make any sense!

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CEAforArcGIS#694]
The script in `properties.py` to generate the architecture properties is significantly flawed.

First and most importantly, **only the envelope renovation year is taken into consideration**. So, say, for a building from 1900 with windows renovated in 2010 but with no envelope renovation (i.e., `age['envelope'] = 0`) the building will be assigned single-glazed windows! Instead, the component type should be assigned by the year of renovation of each specific component!

Furthermore, the window-to-wall ratio should be assigned by construction year, not renovation year. So if an office building was built in 1910, the window-to-wall ratio will be 0.27, but if the same building is renovated in 2010, the window-to-wall ratio will be 0.4 (highly unlikely that new windows will be created...) Instead, the window-to-wall ratio should be assigned by year of construction.

Finally, it doesn't seem like the year of renovation of the basement affects any parameters: there is no `type_basement` in the envelope systems database.

I'm attaching a picture of an example I tested to see how buildings' architectural properties are assigned only by the year of renovation of the envelope (if renovated) or by the year of construction (if the envelope is not renovated).

@JIMENOFONSECA @gabriel-happle Or am I missing something here? Are the renovation years of these components at all considered in any other part of the code?

**Comment by martin-mosteiro** [comment]
![image](https://user-images.githubusercontent.com/18548065/27444923-39d859ae-5778-11e7-977e-048128325328.png)

**Comment by JIMENOFONSECA** [comment]
Hi martin,

Great you noticed it. I believe the main reason why the archetypes of renovation point to the envelope is that we thought this would be the most typical retrofit. But you are right it should be in a component basis. However this is a bit difficult to attain.

The age of each component are taken into account in the LCA asseessment. Including that of the basement.

Do you have something in mind to fix this?

Best, Jimeno

On 23 Jun 2017, at 00:26, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://user-images.githubusercontent.com/18548065/27444923-39d859ae-5778-11e7-977e-048128325328.png>

**Comment by martin-mosteiro** [comment]
Yeah, I figured that was the reason, but then the dates of renovation of all components other than the envelope only have an effect on the LCA calculation... would be better to be able to influence the energy demand as well, no?

I have some ideas for how to fix this.

**Comment by JIMENOFONSECA** [comment]
We might want to do something similar to what exists in the LCA embodied. I remember it makes joins with the database according to each one of the renovation years and then selected the value for each component. We might want to try this

**Comment by daren-thomas** [comment]
How about using the envelope renovation date as a fall-back for when a more specific renovation date is not known?

**Comment by martin-mosteiro** [comment]
Sounds reasonable: but "unknown" is not a valid input for the renovation dates at the moment.

**Comment by daren-thomas** [comment]
is there a value that represents unknown? or: no renovation date?

**Comment by martin-mosteiro** [comment]
0 represents "no renovation", but "no revoation" is not the same as unknown :)
