### ISSUE TITLE
CEA Planning V. 2.2.a4 does not install the toolbox for ArcGIS Desktop 10.5 (manual workaround)

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CEAforArcGIS#697]
Hi,
I downloaded and installed CEA Planning V. 2.2.a4 and ArcGIS but I can not find City Energy Analyst.pyt under My Toolboxes. I followed the installation guide. Did I miss something?
Best regards,
Kerem

![cea folder](https://user-images.githubusercontent.com/29708612/27577114-2e579f78-5b28-11e7-90b4-faa9bcf8b2fb.jpg)
![my toolboxes](https://user-images.githubusercontent.com/29708612/27577113-2e526f12-5b28-11e7-92aa-6449d0d83362.jpg)

**Comment by daren-thomas** [comment]
Hi. Can you please specify your ArcGIS version?

**Comment by kerembeygo** [comment]
Hi Daren, 
ArcGIS Desktop 10.5 Version 10.5.0.6491.

**Comment by daren-thomas** [comment]
Ah, I see, the toolboxes are installed in the folder for ArcGIS Desktop 10.4. Try copying the "C:\Users\**YOUR_USER_NAME_HERE**\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\City Energy Analyst.pyt" to "C:\Users\**YOUR_USER_NAME_HERE**\AppData\Roaming\ESRI\Desktop10.**5**\ArcToolbox\My Toolboxes\City Energy Analyst.pyt"

**Comment by kerembeygo** [comment]
Thank you it's there, but I received an error in radiation simulation.
![import error](https://user-images.githubusercontent.com/29708612/27588913-65acae08-5b52-11e7-9252-fbccc5dfbe1b.jpg)
![radiation](https://user-images.githubusercontent.com/29708612/27588924-6e0ee80e-5b52-11e7-84b9-5838126442b5.jpg)

**Comment by daren-thomas** [comment]
Moving second question to new issue #701, closing this one.
