### ISSUE TITLE
Import Error: no module named arcpy with CEA Planning V. 2.2.a4 on ArcGIS Desktop 10.5

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#701]
As described in #697, the radiation script seems to not run with an installation of CEA Planning V 2.2.a4, yielding the following error:

![image](https://user-images.githubusercontent.com/2969564/27629860-f6b125d6-5bf3-11e7-9edf-10a882edf62c.png)

![image](https://user-images.githubusercontent.com/2969564/27629872-fbc2dfa6-5bf3-11e7-82bd-57cdb5b46cb1.png)

@kerembeygo, I created this as a separate issue so that I can close your original issue.

**Comment by daren-thomas** [comment]
@kerembeygo: Can you please check your home folder (typically `C:\Users\kerembeygo`) for a file called `cea_arcpy.pth` - that file contains paths to the folders required to load the `arcpy` module. Please edit the file, replacing each occurrence of `Desktop10.4`  with `Desktop10.5`. Does that solve the issue for you?

**Comment by kerembeygo** [comment]
Yes, but I think there are other problems. 
![erasepoint](https://user-images.githubusercontent.com/29708612/27674139-016b4150-5cad-11e7-8cc2-a37b858c414c.jpg)

![radiation1](https://user-images.githubusercontent.com/29708612/27674162-1d0e9984-5cad-11e7-9c1c-11833ff82671.jpg)
![radiation2](https://user-images.githubusercontent.com/29708612/27674168-26341ac0-5cad-11e7-9475-67f163f229f5.jpg)

**Comment by daren-thomas** [comment]
@kerembeygo OK, so that means I can close this issue - sadly, now you have issue #699. We're working on it! I'm not sure about a workaround yet...

**Comment by daren-thomas** [comment]
I see PR #702 addresses the issue in #699 - I will create a new installer for you when that is merged.

**Comment by daren-thomas** [comment]
@kerembeygo can you try installing this release: https://github.com/architecture-building-systems/CEAforArcGIS/releases/tag/v2.3a2

I think it should solve your problems. This is a pre-release - please report back how it went for you! It should also automatically install for ArcGIS Desktop 10.5 - can you check that please?

**Comment by kerembeygo** [comment]
![rad1](https://user-images.githubusercontent.com/29708612/27710999-44e420c8-5d2a-11e7-8ee9-5a202711ffe4.jpg)
![rad2](https://user-images.githubusercontent.com/29708612/27711000-44ea07ae-5d2a-11e7-9b84-0b114a267017.jpg)

**Comment by daren-thomas** [comment]
can you try to first clean all the old versions away? it looks like you still have some old code on your system.

**Comment by kerembeygo** [comment]
It completes with some warnings.
![rad3](https://user-images.githubusercontent.com/29708612/27760126-89bd615e-5e48-11e7-8757-f50efef9fe08.jpg)
![rad4](https://user-images.githubusercontent.com/29708612/27760125-89b994fc-5e48-11e7-8ad4-40898beb49b1.jpg)

**Comment by daren-thomas** [comment]
That looks good! The warnings are just that: Warnings. But it seems it worked.
