### ISSUE TITLE
Document `PFloor` in Shapefile: buildings

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#72]
The current documentation says: "ratio of `Floor_ag` with a closed envelope."

What does that even mean? 

In my notes, I have: 

> 1: consider the whole building as inhabited.
> if 0.8: 80% is inhabited, 0.2 is not (counted from the bottom)

Also... can we have a better name? How does `PFloor` relate to what it is?

**Comment by JIMENOFONSECA** [comment]
...please suggest a name. 
...ratio of the (number of floors above ground) where the building has an external envelope.?

**Comment by JIMENOFONSECA** [comment]
* `PFloor`: `float`, $$[-]$$, ratio of `Floor_ag` with a closed envelope
  * **NOTE:** This counts for cases when there is a parking area in  the building. the area is usually not heated/cooled and does not have external walls.
