### ISSUE TITLE
Creat new models for different cooling systems

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CEAforArcGIS#77]
- cooling coils (ex. fins used in 3for2)
- mini split units (air conditioners/ heat pumps)

**Comment by 3for2** [comment]
Idea?: In 3for2, we started trying to develop surrogate/meta-models of entire ventilation units (e.g., 3for2 outdoor air unit, which includes rotary wheels, coils, etc.). The benefit of the metamodel was that it would provide a super fast way of modelling a complex thermosystem with basic inputs and outputs. The main methodology we looked at was support vector regression (SVR). If there is any appeal to this approach, let me know and we could work on it. The limitation with metamodels is that you need an equivalent software package (Matlab/Python) to generate and use it.. If that's an issue, I could think of building up robust empirical regression models of systems like 3for2.

**Comment by JIMENOFONSECA** [comment]
This is a year old issue. @shanshanhsieh what is the solution, intention or plan so far? maybe you would like to create issues to every single technology you want to add.

**Comment by shanshanhsieh** [comment]
Yes, we could close this one for now, new issues on individual technologies will be updated.
