### ISSUE TITLE
Implement "multiple.py" script into ArcGIS

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CEAforArcGIS#78]
the script "multiple.py" to run multiple scenarios is already in the cea folder

**Comment by daren-thomas** [comment]
this tool assumes a specific input folder structure. where is this structure documented? also, if this structure really is going to be a convention - why can't we make the tools really easy-peasy to use by only requiring the path to the scenario (and inferring the rest?)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, I don't think this is going to be part of the workshop - I therefore propose pushing it to the next milestone. What do you think?

**Comment by JIMENOFONSECA** [comment]
I agree,

Jimeno

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: is this still relevant?

**Comment by JIMENOFONSECA** [comment]
Well, it was a tool to make easier running multiple scenarios at the same time. Do we like to add this? If not, we can forget about it

Best, Jimeno

On 2 Dec 2016, at 23:22, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA>: is this still relevant?

**Comment by daren-thomas** [comment]
OK. We forget about it. I don't see the point.
