### ISSUE TITLE
Upgrade to ArcGIS Desktop 10.4

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#81]
The new version is now on IDES - we should upgrade before it becomes a problem.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: can we move this to the next milestone? getting the CEA installed for the workshop is hard enough as it is...

**Comment by JIMENOFONSECA** [comment]
totally! for the next milestone

**Comment by daren-thomas** [comment]
@JIMENOFONSECA check out pull request #266 that I have run on ArcGIS Desktop 10.4. The output stays the same. I am currently creating a branch of the documentation to merge with Installation Guide for 10.4.

**Comment by daren-thomas** [comment]
Documentation updated in a branch called `i81-upgrade-to-arcgis-10.4`. Note that you can't have both versions of ArcGIS Desktop installed side-by-side.
