### ISSUE TITLE
Find a way to better implement turned 'off' status of systems 

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CEAforArcGIS#84]
Maybe change ‘off’ status of temperature requirements from 0 to ‘NaN’ in order to implement minimum and maximum functions

**Comment by gabriel-happle** [comment]
Temperature set points of heating and cooling systems are now set to arbitrary very high or low values like 48­­°C or -22°C to represent turned 'off' status.
One way to change this would be to change these to numpy [`nan` ](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.isnan.html) or `inf`
Another way is to make two more parameters in the schedules with `True` and `False` values to represent the status of the heating and cooling system.
@JIMENOFONSECA, @daren-thomas, @shanshanhsieh what do you think is better?

**Comment by JIMENOFONSECA** [comment]
I am taking a look at this. we could define the operating dates of the system in a schedule and define when the setback be activated. Amir should be taking a look at this in his issues of setback temperatures


On 16 May 2016, at 1:59 pm, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


Temperature set points of heating and cooling systems are now set to arbitrary very high or low values like 48­­°C or -22°C to represent turned 'off' status.
One way to change this would be to change these to numpy nan <http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.isnan.html> or inf
Another way is to make two more parameters in the schedules with True and False values to represent the status of the heating and cooling system.
@JIMENOFONSECA<https://github.com/JIMENOFONSECA>, @daren-thomas<https://github.com/daren-thomas>, @shanshanhsieh<https://github.com/shanshanhsieh> what do you think is better?

**Comment by daren-thomas** [comment]
We could also create a function like "is-heating-system-on" that takes the date and other info (outside temperature? inside temperature?) and returns `True`/`False`.

First refactor the current work to use this. Reference the function from `gv` as with `calc-thermal-loads`.

Then, we can try out different methods. One is having a schedule like @JIMENOFONSECA says. Another could be a "smarter" approach based on the actual weather data.

What do you guys think?

(I am not a big fan of hard-coding heating and cooling seasons into the software. *espescially* given the nature of Singapore seasons...)

**Comment by JIMENOFONSECA** [comment]
I think that the season house should be an input of demand.py. The user should select the beginning and the end of the cooling season. which is usually given by a local policy. We should provide a default value. 

Two variables will be involved:

- beginning cooling season: 15/05/2016
- end cooling season: 15/09/16

then we transform these inputs into the variables liminf and limsup that calcThermal uses now

**Comment by JIMENOFONSECA** [comment]
The new pull request #195 makes changes to this. However, @amraladdin is working on a setback control temperature procedure #8 which should solve the problem.

**Comment by gabriel-happle** [comment]
This could be addressed via system control algorithms.
Using functions instead of arbitrary temperatures etc.
See #220

**Comment by gabriel-happle** [comment]
Working on this.
You can have a look in my sandbox in the master branch, if you are interested.
