### ISSUE TITLE
Upgrade to ArcGIS Pro

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CEAforArcGIS#91]

**Comment by JIMENOFONSECA** [comment]
This is a year old issue. @daren-thomas are we expecting this? I believe it would be a great add on. but i would get the issue out of the list if we do not plan to develop it any time soon.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I am currently working on the decoupling of CEA from ArcGIS which would make moving to ArcGIS Pro much easier. But personally I don't think it is important. If you like we can delete this.

**Comment by JIMENOFONSECA** [comment]
Yep i do not see it coming in the next couple of years...

Best, Jimeno

On 20 Mar 2017, at 21:48, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I am currently working on the decoupling of CEA from ArcGIS which would make moving to ArcGIS Pro much easier. But personally I don't think it is important. If you like we can delete this.
