### ISSUE TITLE
Read shapefiles with python library instead of ArcPy,

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CEAforArcGIS#98]
Pyhton has new libraries to read Shapefles (e.g., pyshp etc.) and transform the input directly into a dataframe. This could cut the vast amount of lines needed with the ArcPy reader. It also will help to be less dependent on ArcGIS in the future. @daren-thomas could b this an option to fix for milestone 1? I saw you were working a related topic: "refactored row indexing to field_lookup

**Comment by daren-thomas** [comment]
yes it could. i have read shapefiles in python before (oh no! i had to
write my own library then, but that was before i started at this chair) and
don't see much problems either way. sure, we can check out the new
libraries and use them. this should also speed up the scripts, i think, as
we don't have to start arcgis in the background. i'm all for it!

**Comment by JIMENOFONSECA** [comment]
Great!
I will propose a library as i am necessarly working with them while fixing issues in the properties file. #99

Sent on the road

**Comment by JIMENOFONSECA** [comment]
found Geopandas. included in next versions
